### ISSUE TITLE
Need docs for send email with any provider such as [send grid]

### ISSUE THREAD

**Issue by ahmedabdelhafez** [supabase/supabase#10030]
hello dears:
please add more clear documents that explains how to send email with sendgrid 

thanks

**Comment by zernonia** [comment]
You can checkout [supabase-mailer](https://github.com/burggraf/supabase-mailer) by @burggraf

**Comment by KevinBrolly** [comment]
Thanks for the docs suggestion, in the time since this issue and now we have made further enhancements to our documentation. Since this issue is more than a year old I believe it is now stale, and I am going to close it.

Further documentation suggestions and PR's are always welcome. If this issues should be reopened please let us know.
