### ISSUE TITLE
Selfhosted storage getPublicUrl {"statusCode":"400","error":"ENOENT: no such file or directory

### ISSUE THREAD

**Issue by 1270514689** [supabase/supabase#10328]
Selfhosted storage getPublicUrl

bucket name：bucket
path：public/pic001.jpg

{"statusCode":"400","error":"ENOENT: no such file or directory, open '/var/lib/storage/stub/stub/bucket/public/pic001.jpg'","message":"ENOENT: no such file or directory, open '/var/lib/storage/stub/stub/bucket/public/pic001.jpg'"}

I used the default docker-compose.yaml  and the createSignedUrl is good.

**Comment by GaryAustin1** [comment]
You also asked this in discussions. Is the bucket set to public?

**Comment by 1270514689** [comment]
yes，the bucket is public

**Comment by GaryAustin1** [comment]
Sort of unclear how the url is coming about.
getPublicUrl for storage-js has this for generating the URL
```
data: { publicUrl: encodeURI(`${this.url}/object/public/${_path}${downloadQueryParam}`) },
```
this.url is the storage url, then it should have `/object/public/bucket/public/pic001.jpg`

I don't know what the storage url looks like for a local implementation, but your url is missing the hard coded ` /object/public` that getPublicUrl generates.  

Then I assume your path `/public/pic001.jpg` you intend to have a "folder" name in the path of "public".  Folders don't really exist in storage and are just part of the path, so that is not an issue if that is how you uploaded the file.

**Comment by 1270514689** [comment]
@GaryAustin1 thank you. I test the getPublicUrl again by your tips.
When getPublicUrl(path) the path is 001.jpg, I got the url is "http://192.168.2.61:8000/storage/v1/object/public/bucket/pic001.jpg",and that is good,
 and that my supabase docker machine corresponded path is /home/supabase/docker/volumes/storage/stub/stub/bucket/pic001.jpg
But if the path is public/001.jpg,  and the public url is "http://192.168.2.61:8000/storage/v1/object/public/bucket/public/pic001.jpg" can not visit. and that docker real path is /home/supabase/docker/volumes/storage/stub/stub/bucket/public/pic001.jpg
I also change the path name to "my/pic001.jpg" and get public url and can visit.
So that I think that if my path name included "public/" that get public url can not visit ,but the docker volume real path is exist. So I think I think it is my path name's problem.
