### ISSUE TITLE
[Critical] Auth Service frequently terminating connection due to idle-session timeout

### ISSUE THREAD

**Issue by gascenciom1998** [supabase/supabase#10387]
# Bug report

## Describe the bug

Auth Service terminating connection due to idle-session timeout frequently, not letting users log in

The error object is attached in the image.

Customer Support said they increased the max pool size as a temporary fix but that did not make a difference and they have been unresponsive since.

## To Reproduce

1. What for supabase logs to show the idle session timeout error on the auth service
2. Run the following snipet to generate a magic link
```
The auth service frequently throws an idle connection session timeout error. It affects us when we call this:
const { data, error } = await supabaseAdmin.auth.api.generateLink(
    'magiclink',
    internalUserEmail,
    {
      redirectTo: ROOT_URL,
    },
  )
```
3. Magic Link is not generated and the error object shows the following:
<img width="1063" alt="Screen Shot 2022-11-17 at 1 29 48 PM" src="https://user-images.githubusercontent.com/30400139/202528548-8781a6a9-39a6-47c2-83db-7cb5f2dd52ce.png">

## Expected behavior

A magic link is returned to the data objec

## Additional context

I contacted customer support and as a temporary fix they increase the pool size, that did not really make a difference. I tried contacting them again providing more information on what I could find but they have been unresponsive,

**Comment by kangmingtay** [comment]
closing this since we managed to resolve the issue through email previously - please let us know if you're still facing problems with this.

for anyone else facing this issue, you can use the following SQL statement to check if there is a system-wide `idle_session_timeout` applied to your postgres database

```sql
select * from pg_settings where name = 'idle_session_timeout';
```

Supabase doesn't set this value by default and it could be set when restoring from a database dump obtained from somewhere else. This setting causes underlying connections to be closed which messes with the connection pool that gotrue uses.
