### ISSUE TITLE
Ability to toggle on/off extensions

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#105]
We can allow toggling on/off of the extensions in an `extensions` schema, [recommended here](https://stackoverflow.com/questions/12986368/installing-postgresql-extension-to-all-schemas/43937189#43937189), which will avoid polluting the `public` schema. We can also use this schema as a "catch all" for our admin tasks so that we don't pollute the REST API

## Requirements

- [x] set up of `extensions` schema by default in [postgres](https://github.com/supabase/postgres)  
- [ ] move the "notify_schema_reload" function to this schema 
- [x] add toggle on/off functionality to [pg-api](https://github.com/supabase/pg-api)
- [ ] update the UI
- [ ] regression: if this schema isn't present when the user toggles on/off, we should create it.

## Questions

- Are there any plugins which are schema-specific? 

## Prior research

Angelico's research here: https://github.com/supabase/postgres/issues/10. Here we concluded that we would use templates for any non-modifying extensions like the Procedural Languages (plpythonu, plv8, etc.), so that new schemas aren't polluted.

In this issue we are taking an opinionated approach that extensions should live in a separate schema, and then they can be accessed by extending the search_path

**Comment by steve-chavez** [comment]
> Are there any extensions which are schema-specific?

Extensions usually define a placeholder `@extschema`(1) in their install files that allows them to be installed on any schema(`CREATE EXTENSION postgis WITH SCHEMA extensions`). But I've seen some extensions like pipelinedb and timescaledb that install their own schemas(they ignore the `WITH SCHEMA` modifier).

(1): https://www.postgresql.org/docs/12/extend-extensions.html#EXTEND-EXTENSIONS-RELOCATION.

**Comment by dragarcia** [comment]
The usage of the schema `extensions` should be okay and viable with a minor tweak to what needs to be done. Wrt to the [SO post](https://stackoverflow.com/questions/12986368/installing-postgresql-extension-to-all-schemas/43937189#43937189):

### Creating the schema
```sql
create schema extensions;
```

### Providing rights
```sql
-- make sure everybody can use everything in the extensions schema
grant usage on schema extensions to supabase_admin, postgres;
grant execute on all functions in schema extensions to supabase_admin, postgres;

-- include future extensions
alter default privileges in schema extensions
	grant execute on functions to supabase_admin, postgres;

alter default privileges in schema extensions
	grant usage on types to supabase_admin, postgres;
```
`public` before is a role that [refers to all other roles available](https://www.postgresql.org/docs/current/ddl-priv.html#:~:text=The%20special%20%E2%80%9Crole%E2%80%9D%20name%20PUBLIC%20can%20be%20used%20to%20grant%20a%20privilege%20to%20every%20role%20on%20the%20system). Here, we restrict access to extensions to the roles/ users `supabase_admin` and `postgres`. If we want to add more, we can just add the role name to the command, or create a role specific to extensions access.

### Setting the search path
```sql
set search_path = public, extensions;
```
We set it as such because:
- `search_path` is [used as a checklist](https://www.endpoint.com/blog/2012/11/15/postgresql-searchpath-behaviour) for schemas to apply a query to whenever queries do not specify a schema.
- Typical behavior when writing SQL queries usually does not involve having the schema name inside. for eg.
```sql
select * from table_name
```
- As such, assuming that the `public` schema is the default schema in use, setting the schema `public` before `extensions` allow queries to be performed first on `public` before `extensions`.
- This is important when creating tables. Having `extensions` before `public` or not having `public` at all will result in future tables being written in the schema `extensions`.
- Not important for other types of queries, since if the table/ function does not exist in the search path, it will just go down the list until an appropriate one is found.

**Caveat**
When creating or dropping extensions, the schema `extensions` would need to be specified
``` sql
create extension unaccent schema extensions;
```
Failure to do so would result in the extension being written in the schema `public` instead.

### Creating extensions
``` sql
create extension pg_stat_statements schema extensions;
```

From here, extensions are now housed in the schema `extensions` and can be accessed by the users `supabase_admin` and `postgres` without the need to specify the schema.
```sql
select * from pg_stat_statements;
```

### Conclusion 
> Requirements
> - [ ] set up of extensions schema by default in postgres
> - [ ] move the "notify_schema_reload" function to this schema 
> - [ ] add toggle on/off functionality to pg-api
Should all be feasible and can be done with the above steps. I confirm as well that this has no clashes whatsoever with Postgres templates.

**Comment by kiwicopple** [comment]
@phamhieu could also be an easy one on the dashboard:

1. Turn on an extension in the `extensions` schema:

https://github.com/supabase/pg-api/blob/1c10b942cddd47c90d5c3f82457a44868f1e1205/test/integration/index.spec.js#L398

2. Turn off an extension: 

https://github.com/supabase/pg-api/blob/1c10b942cddd47c90d5c3f82457a44868f1e1205/test/integration/index.spec.js#L423

Thoughts on a popup confirmation too? I think we don't want them accidentally disabling an extension when it is in use

**Comment by kiwicopple** [comment]
Released! Thanks @phamhieu
