### ISSUE TITLE
Can't multi select, or select all on Supabase Storage dashboard UI

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#10510]
# Bug report

## Describe the bug

You can not do the following:

- "select all" in storage viewer.
- select individual items, so you can do block actions like "download all"

https://user-images.githubusercontent.com/8291514/203757563-f36bae8d-b68a-4356-9680-06e058d2a7b6.mov

## Expected behavior

to multi select items

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by raph941** [comment]
This issue seems to be specific to folders/directories within the storage dashboard UI. Selecting all currently doesn't work if there are only folders listed and ignores the folders if the list contains a combination of files and directories. 

At the moment, looks like only Rename/Delete actions are supported directories. I would love to pick this up, although would also like to get some context on the following:

1. What bulk actions should be available if a user selects a list containing only folders?
2. What bulk actions should be available if a user selects a list containing folders and files?

**Comment by adamulan** [comment]
Hey @MildTomato, I am looking at this issue and right now you can do:
![image](https://user-images.githubusercontent.com/84980432/222927255-1962cc10-e624-4a7a-ad7f-41d69d6a0e5d.png)
and this will give you a zip with:
```
  - folder5
       - folder8
            - image3.png
       - image2.png
  - image1.png
```
but if there was an image in folder6 you wouldn't be able to select it at the same time because you can only select items that you can see in the columns. Is that the desired behavior or do you want to be able to select multiple folders?
