### ISSUE TITLE
Option to set longer auth session

### ISSUE THREAD

**Issue by EskelCz** [supabase/supabase#11014]
# Feature request
Can we please get more options for setting longer auth session? Now the maximum is just two weeks. I think many people would appreciate options for much longer login persistence. It's less hassle for our users.

## Describe the solution you'd like
A month, multiple months, maybe even year or infinite.

The original thread where this was discussed, now closed and the author doesn't react to requests for reopening:
https://github.com/supabase/supabase/issues/319

**Comment by kiwicopple** [comment]
Hi all, this has been answered a few times. When you use JWTs, they issue 2 types of token:

- `access_token`: is a short-lived token that is used to authenticate a user's request when accessing a resource. It typically has a limited scope, such as allowing a user to read or write a specific resource. 
- `refresh_token`: a long-lived token that is used to obtain a new access token. When an access token expires or becomes invalid, the user can use the refresh token to get a new access token without having to re-authenticate. This helps to keep the user authenticated and avoid the need for them to constantly enter their login credentials.
When a user signs in they are issued both, and then the refresh token is used to get "fresh" access tokens. 

*There is no expiry for the refresh_token.* If you are having issues with logged-out users, it's because the refresh is not happening properly. I recommend checking out our Auth Helpers to see the best practice to avoid this.

> Now the maximum is just two weeks

This time period is for the `access_token`. It is generally considered safer to use shorter expiry times for access tokens because they reduce the window of opportunity for an attacker, are easier to revoke if necessary, and can improve the user experience.

Hope that clears up any confusion!

**Comment by EskelCz** [comment]
I see, that certainly does clears thing up. I must be having issues with the refresh, I'll check the docs then.
Thanks a lot for the explanation!

**Comment by benrugg** [comment]
I understand the `access_token` and `refresh_token` expiration durations. But for clarification, how long can a user stay signed in without having to reauthenticate (with email/pass or OTP)?

**Comment by kiwicopple** [comment]
the `refresh_token` has no expiry period, so in theory "indefinitely"
