### ISSUE TITLE
Run studio without docker - storage has an issue

### ISSUE THREAD

**Issue by berbagimadani** [supabase/supabase#11067]
# Bug report

I run studio using npm run dev, not using docker from supabase.
when i go to storage page and create new bucket it shows error.

## Screenshots

![Screenshot from 2022-12-17 14-11-19](https://user-images.githubusercontent.com/4327476/208360845-583ddaaa-759a-4528-a178-53c763d4767d.png)

**Comment by berbagimadani** [comment]
Solved: 
docker restart storage

**Comment by activenode** [comment]
This bug misses a complete description. It's not possible to follow up what you mean. Please add "steps to reproduce" accordingly.

**Comment by MildTomato** [comment]
I think this may be a documentation issue and also an issue in Studio itself.

1. Need to document the different modules that are self-hosting. This may also include using your own storage S3 bucket, rather than using whatever is in docker ? (I'm not sure, that's a guess, but I assume this stuff can be documented). 

2. Should be easy in Studio to disable modules if you're not interested in self-hosting. For example, you could in theory just use your own postgres database (without using our docker setup) and that's all you want to use.

**Comment by berbagimadani** [comment]
> I run studio using npm run dev, not using docker from supabase. when i go to storage page and create new bucket it shows error.

I am sorry, 
issue has SOLVED:
by restart container storage. docker restart supabase-storage

**Comment by berbagimadani** [comment]
> Just to better understand what is happening here, @berbagimadani are you following the '[self hosting with docker](https://supabase.com/docs/guides/resources/self-hosting/docker)' setup?

I am sorry,
issue has SOLVED:
by restart container storage. docker restart supabase-storage

**Comment by berbagimadani** [comment]
> This bug misses a complete description. It's not possible to follow up what you mean. Please add "steps to reproduce" accordingly. It's not clear what is not working, it's not clear what error message you get and it's not clear what "has an issue" means.

I am sorry
issue SOLVED with container restart.
docker restart supabase-storage

**Comment by activenode** [comment]
@MildTomato  please close.
