### ISSUE TITLE
Add/Change Magic link sign in flow

### ISSUE THREAD

**Issue by socramm9** [supabase/supabase#11256]
# Feature request

## Is your feature request related to a problem? Please describe.

At the moment the user is required to open the magic link on the same device they want to sign in. This could be annoying if the user has no mail provider set up on his desktop or is using a public computer. 

## Describe the solution you'd like

It wold be nice to be able to use any device to confirm an sign in attempt.

## A clear and concise description of what you want to happen.

1. User opens WebApp on a Desktop and clicks sign in with magic link.
2. WebApp waits for confirmation 
3. User takes out his phone an clicks on the link send by supabase
4. WebApp receives credentials from supapase 

## Additional context

I was inspired by the sign in flow from https://vercel.com/login/email and want to simplify the email auth. flow for my users

**Comment by ruggi99** [comment]
Hi @socramm9.
What you are asking is already possible to do.
If I'm understanding it correctly, you are asking for an OTP sent via email that you can enter in a public computer.
This is possible via these 2 APIs: [link1](https://supabase.com/docs/reference/javascript/auth-signinwithotp) and [link2](https://supabase.com/docs/reference/javascript/auth-verifyotp).
In order to enable it, you have to update the email template and include `{{ .Token }}` somewhere.
I think it's not well documented how to achieve this, but I tried in my project and it works well.
I tried only with Javascript library `supabase-js`, should work also for Dart.
Don't know if there's already a nuilt-in auth flow that requires no custom javascript logic.

**Comment by socramm9** [comment]
Yes Tanks I could Try using OTP for now. So if I understand correctly the user receives an email but instead of a link he gets a password. 

It would be nice to have the option to skip this Stepp like in vercel. Don’t know how big of a security concern it would be to implement such flow

**Comment by alaister** [comment]
Hi @socramm9,

I think the OTP solution will be your best option for now. Thanks for the suggestion @ruggi99!

I'm going to go ahead and close this. If the OTP solution isn't fit for your use case, might I suggest opening another issue in the [supabase/gotrue](https://github.com/supabase/gotrue) repo and include this feature suggestion and why the OTP didn't work for you. Cheers!
