### ISSUE TITLE
Flutter web app using the Auth reset password - no 'passwordRecovery' event is received by client

### ISSUE THREAD

**Issue by davoutuk** [supabase/supabase#11613]
I am building a Flutter web app and using Supabase for user authentication.

When I call the 'resetPassword' method like:

 await Supabase.instance.client.auth.resetPasswordForEmail(anEmail);

... an email is received.

However, when I click on the link in the  reset password email,  I would on the client side expect to see 'passwordRecovery' event.

No such event arrives.

**Comment by dshukertjr** [comment]
Hi @davoutuk ,

Would you be able to share the piece of for the widget where you have that auth listener set? Also, would you be able to check which gotrue version you are using for your app? You can check this in your pubspec.lock file/

**Comment by yutech23** [comment]
> Hi @davoutuk ,
> 
> Would you be able to share the piece of for the widget where you have that auth listener set? Also, would you be able to check which gotrue version you are using for your app? You can check this in your pubspec.lock file/

Hi I have same problem. when I was click link, I get it error

**** SupabaseAuthState handleDeeplink http://localhost:3000/#/resetPassword%23access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjgxMDk3MDA2LCJzdWIiOiIzM2U3M2I3Yy1kOTViLTQ4NWQtYjMyNi1iMzQxMzFhYzNmMzgiLCJlbWFpbCI6Inl1c3VmY29za3VuMUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvdHAiLCJ0aW1lc3RhbXAiOjE2ODEwOTQwMDZ9XSwic2Vzc2lvbl9pZCI6ImFjYmIzOGE1LTdjMjktNDg2OS1hOTgyLWY2OTU3ZWYyNTRiOSJ9.uOch7CNxAYmzk1KbUi86L8U3NTZPkDjEGbT2Bgsm3uk&expires_in=3000&refresh_token=4pN4gjxgOPlOLnWJUkR21g&token_type=bearer&type=recovery
onReceivedAuthDeeplink uri: http://localhost:3000/#/resetPassword%23access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjgxMDk3MDA2LCJzdWIiOiIzM2U3M2I3Yy1kOTViLTQ4NWQtYjMyNi1iMzQxMzFhYzNmMzgiLCJlbWFpbCI6Inl1c3VmY29za3VuMUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJvdHAiLCJ0aW1lc3RhbXAiOjE2ODEwOTQwMDZ9XSwic2Vzc2lvbl9pZCI6ImFjYmIzOGE1LTdjMjktNDg2OS1hOTgyLWY2OTU3ZWYyNTRiOSJ9.uOch7CNxAYmzk1KbUi86L8U3NTZPkDjEGbT2Bgsm3uk&expires_in=3000&refresh_token=4pN4gjxgOPlOLnWJUkR21g&token_type=bearer&type=recovery
AuthException(message: No access_token detected., statusCode: null)
packages/gotrue/src/gotrue_client.dart 769:32                                                                     [_notifyException]

Can you share full example for flutter. Because doc is not descriptive.

**Comment by dshukertjr** [comment]
@yutech23 
We are working on a full example with different auth flows. Will share once it's done. 

In the mean while, is the URL that you shared Flutter Web?  If you are on Flutter Web, you need to use path URL strategy for the password reset link to work. 
https://docs.flutter.dev/development/ui/navigation/url-strategies

**Comment by yutech23** [comment]
> @yutech23 We are working on a full example with different auth flows. Will share once it's done.
> 
> In the mean while, is the URL that you shared Flutter Web? If you are on Flutter Web, you need to use path URL strategy for the password reset link to work. https://docs.flutter.dev/development/ui/navigation/url-strategies



> @yutech23 We are working on a full example with different auth flows. Will share once it's done.
> 
> In the mean while, is the URL that you shared Flutter Web? If you are on Flutter Web, you need to use path URL strategy for the password reset link to work. https://docs.flutter.dev/development/ui/navigation/url-strategies

Hi  Yes it is flutter web. I did what you said. it worked (url-strategies) localhost .But when i upload it to the server it doesn't work. An error occurs. The address bar gives a 404 error when we type the web address directly or go with the reset link.

**Comment by yutech23** [comment]
I solved the problem. The problem is that when using strategy in flutter, a single page action is required on the web server.
