### ISSUE TITLE
Self-Hosted Studio makes requests to `localhost:8000` instead of `EXTERNAL_API_URL`

### ISSUE THREAD

**Issue by globemediaofficial** [supabase/supabase#11656]
# Bug report

## Describe the bug

When loading tables and buckets, the `Studio` makes requests to `http://localhost:8000/storage/v1/bucket` and `http://localhost:8000/rest/v1/` instead of `https://kong.example.com/rest/v1/`. This means that if I visit the `Studio` externally it will be stuck on `Connecting to default project` because only the host computer can reach `localhost`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the master branch
2. Create subdomains that point to point `8000` and `3000`
3. Use the subdomain that points to `8000` as `API_EXTERNAL_URL` and `SUPABASE_PUBLIC_URL`  in `.env`
4. `docker compose up -d`
5. Visit the `3000` subdomain on the host computer and it works but you will see in `Network` that the requests are made to `localhost:8000`
6. Visit the `3000` subdomain on a different computer and it does not work,
    - You will see in `Network` that the requests are made to `localhost:8000`
    - External computer cannot reach that
    - Everthing will show `Connecting to default project`

## Expected behavior

The `Studio` should use the correct URL to make requests.

## Screenshots

![image](https://user-images.githubusercontent.com/109893647/212433889-24dde24a-02aa-4ccb-9f81-4b259c81a410.png)

## Additional context

I know that this is a bug and not an issue with my configuration because it worked before AND my configuration still works when I run the `Studio` locally. According to [a comment on a separate bug fix](https://github.com/supabase/supabase/pull/11331#issuecomment-1375561791), this bug was introduced a few weeks ago on the docker image.

**Comment by globemediaofficial** [comment]
> Ok, but what I'm saying is that you probably have to set up environment variables before building the studio image, IMO.
> In NextJS environment variables are not read runtime at client side and from what I've seen, the environment variables you are using are client side. So they are "injected" at buildtime

@ruggi99 
I used `Docker compose down` and then `Docker compose up -d` which has always worked for me in the past when I changed variables.

**Comment by serebano** [comment]
@ruggi99 is right
studio .env has the following:
# TODO: evaluate these variables at runtime instead
# https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables

@globemediaofficial 
in the past it worked for me too, but now only solution that i found is to build studio

**Comment by ruggi99** [comment]
@serebano, what you found is true but it doesn't fit in this issue.

Now I found why it may have broke and why it worked before as said by @globemediaofficial 
Actually I think that your PR #11331 broke this behavior because you changed the first line in `constants.ts`.

Now we are using `NEXT_PUBLIC_SUPABASE_PUBLIC_URL` and it is known that it is evaluated at build time, where `SUPABASE_PUBLIC_URL` is evaluated at runtime. So we should revert that change to make it working again.
This is why `constants.ts` is used server side and it makes no sense to use a client side environmente variable

I'v read your PR template and I don't get why it wasn't working for you (you said that it couldn't access the variable).
Can you try reverting that change locally (only `constant.ts` file) and try again?

**Comment by ruggi99** [comment]
So if you read again my message, I'm saying that you changed the `contants.ts` file, not `.env` file. I think the error is that change

**Comment by ruggi99** [comment]
Ok, I think I've understood the problem going on.
The fact is, simplying a bit, that the protocol to be used for only storage and rest routes is calculated at buildtime (at buildtime the env var is always `http://localhost:8000` and therefore always http as you said).

To fix this I will send a PR where the protocol is calculated at runtime clientside and I hope will fix it.
As you said, the commit https://github.com/supabase/supabase/commit/0868ee96f27333cd541dd5d512368a584a510210 is the source of the problem because of the difference between builtime and runtime (didn't noticed yesterday).

But your PR still needs to be reverted because is a no-op fix.

Sorry for the inconvenience, will try to explain me better in the PR template.
