### ISSUE TITLE
Bug when linking self-hosted instance to Keycloak : 405 PATCH METHOD NOT ALLOWED

### ISSUE THREAD

**Issue by KevinHamonApp** [supabase/supabase#11764]
# Bug report

## Describe the bug
I am on self-hosted instance of Supabase. 
I was trying to link it to my Keycloak instance.
From the Admin UI, path : /project/default/auth/settings
I want to add Keycloak as provider. When saving, I receive an error from server : 405 Method Patch not allowed.
You'll find the description of the error attached. 

I doubled-checked, the PATCH request go through my proxy and reach Supabase server. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to /project/default/auth/settings on self-hosted instance
2. Put Keycloak information
3. Save the configuration

## Screenshots
![image](https://user-images.githubusercontent.com/74555017/213481496-f67700d5-890d-4cfe-9646-a19826b05ae6.png)

## System information

- OS: Ubuntu 22

**Comment by GaryAustin1** [comment]
Unless something has changed recently in self-hosted you have to handle all set up thru config files.
Did you get to the link thru the dashboard or just enter it directly?
https://github.com/supabase/supabase/discussions/4421

**Comment by kiwicopple** [comment]
As Gary mentioned - for self-hosting, you can set up all Auth providers using Env Vars, rather than the dashboard. This is  because there are many ways for you to self-host, and we can't write a "configuration management" API for all the various ways that developers might choose to store their secrets (.env? AWS secrets manager? Doppler? SOPS? etc...)

You can find a full list of env vars in the GoTrue README: https://github.com/supabase/gotrue
