### ISSUE TITLE
Reference environment variables in Docker's kong.yml

### ISSUE THREAD

**Issue by JoshElias** [supabase/supabase#12416]
# Chore

## Describe the chore

I think the `keyauth_credentials` for the `anon` and `service_role` keys in the Docker Kong configuration should reference the existing environment variables `ANON_KEY` and `SERVICE_ROLE_KEY` respectively, rather than being hardcoded. 

https://github.com/supabase/supabase/blob/master/docker/volumes/api/kong.yml#L8-L12

## Additional context

I came across this when I was attempting to create my own JWT_SECRET which required me to regenerate the `ANON_KEY` and `SERVICE_ROLE_KEY`. This resulted in the Supabase Studio web client not being able to connect to the default project because it was using the hardcoded values instead of the environment variables in `kong.yml`.

**Comment by Lan-Hekary** [comment]
I did some investigation on the matter and it turns out that `kong.yml` is passed as a `KONG_DECLARATIVE_CONFIG` file.
Unfortunately Kong Declarative Config files [does not support environment variables](https://discuss.konghq.com/t/using-environment-variables-in-kong-configuration-file-in-db-less-mode/7653/2)
There is a hint in the link above for the solution using `envsubst` command but unfortunately it's not supported in the official docker image for Kong.
There is an [image](https://github.com/carnei-ro/kong-interpolation) that can do just that, but it's older and this is too much changes for my taste anyway.

The simpler workaround I used for this is to use this little [hack](https://unix.stackexchange.com/a/294837):
`eval "echo \"$(cat ~/temp.yml)\"" > ~/kong.yml`
executing it before the entry point for Kong substitute the environment variables in the file.
Also `kong.yml` should reference the environment variables and we should pass them in the `docker-compose.yml` file as well.

I will make a pull request with this solution.
