### ISSUE TITLE
Edge function returning SSE connection causes other function calls to hang indefinitely

### ISSUE THREAD

**Issue by TimoWilhelm** [supabase/supabase#12474]
# Bug report
I have two edge function deployed.

One is just a simple echo bot, while the other one returns an Server-Sent Events connection that pushes messages every second. 

## Describe the bug

If the SSE function is running, trying to call the other function results in the connection stalling and being aborted after ~90 seconds.

However, this only happens on the same connection. If I open the page with another Browser, the other function completes as normal.

## To Reproduce

I created an MRE here https://github.com/TimoWilhelm/mre-supabase-sse-edge-function

To test it, just open the index.html in a browser.

1. Click on the 'Echo' button (the response will be printed in the browser dev tools console)
2. Click on 'Start SSE'. You should see the streamed responses appearing in the textbox
3. Now if you try to click in the 'Echo' button, the call will timeout (you can check it in the networking tab of the browser dev tools)

You can also deploy the functions in the repo yourself and update the function endpoint + anon key.

## Expected behavior

Other functions should still be reachable while the SSE function runs.

## Screenshots

![error](https://user-images.githubusercontent.com/22396907/219346663-c7d08c81-6bd5-4c31-96d8-8ea74b3bde43.png)

## System information

- OS: Windows
- Browse: chrome, firefox

## Additional Information

This issue does **not** happen when the functions are running locally using `supabase functions serve`.

**Comment by laktek** [comment]
This is due to HTTP/1.1 has limited number of connections per browser session and SSE consuming it. We are looking into moving Edge Functions to use a HTTP/2 proxy. Meanwhile, as a temporary workaround you can create a 2nd project in Supabase and use it for your other edge function calls (two projects will have different domains, which will allow you to bypass the connection limits).

**Comment by TimoWilhelm** [comment]
Thanks for the reply! Multiple projects isn't really an option for me so I guess I'll have to deploy these functions directly to deno deploy and bypass Supabase entirely.

Do you have any insight how far HTTP/2 support for functions is away: weeks, months or years?

I'm guessing it's something where outside contribution is not possible, right?

This [Blog Post](https://supabase.com/blog/openai-embeddings-postgres-vector#streaming-results) from the Supabase blog makes it sound like SSE would be a viable option but it doesn't mention any of these limitations.

**Comment by marc-tech** [comment]
Hey I have the same probleme :

I HAVE :
A supabase edge function with oak server, I make a fetch to openai completion api in stream mode (that return a RedableStream) :
```
import 'xhr_polyfill'
import { serve } from 'std/server'
import { CreateCompletionRequest } from 'openai'

serve(async req => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers':
          'authorization, x-client-info, apikey, content-type'
      }
    })
  }
  const { query } = await req.json()

  const completionConfig: CreateCompletionRequest = {
    model: 'text-davinci-003',
    prompt: query,
    max_tokens: 256,
    temperature: 0,
    stream: true
  }

  return fetch('https://api.openai.com/v1/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${Deno.env.get('OPENAI_API_KEY')}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(completionConfig)
  })
})
```

PROBLEMES : 
1) When deploy in production, I can't run two request in parallel to my completion endpoint (the seconde request is waiting the first one to be completed)

2) When I start a stream request and close my browser tab, to reopen it,  all the edge functions hang (spin, pending) for almost 2min

I NOTICE : 
1) I recode all my logic with the handle fetch api (nuxt /api or next/api ) and deploy on vercel (using vercel edge function) and it's working fine

2) when I use 2 different browser (chrome, safarie) they are not blocking at the same time
 for example I can block the chrome browser and the safarie one still okey and vis versa (I can also block all two browser)
 
 I try every possible way to solve this issue (refacto all my code, try on other, cloud service...)
 and I don't really know where the issue comes from, my guess is that supabase edge function are mybe using http 1 and runing into this probleme : 
 "
[19.6.2](https://www.rfc-editor.org/rfc/rfc2616#section-19.6.2) 
Compatibility with HTTP/1.0 Persistent Connections

   Some clients and servers might wish to be compatible with some
   previous implementations of persistent connections in HTTP/1.0
   clients and servers. Persistent connections in HTTP/1.0 are
   explicitly negotiated as they are not the default behavior. HTTP/1.0
   experimental implementations of persistent connections are faulty,
   and the new facilities in HTTP/1.1 are designed to rectify these
   problems. The problem was that some existing 1.0 clients may be
   sending Keep-Alive to a proxy server that doesn't understand
   Connection, which would then erroneously forward it to the next
   inbound server, which would establish the Keep-Alive connection and
   result in a hung HTTP/1.0 proxy waiting for the close on the
   response. The result is that HTTP/1.0 clients must be prevented from
   using Keep-Alive when talking to proxies.

   However, talking to proxies is the most important use of persistent
   connections, so that prohibition is clearly unacceptable. Therefore,
   we need some other mechanism for indicating a persistent connection
   is desired, which is safe to use even when talking to an old proxy
   that ignores Connection. Persistent connections are the default for
   HTTP/1.1 messages; we introduce a new keyword (Connection: close) for
   declaring non-persistence. See [section 14.10](https://www.rfc-editor.org/rfc/rfc2616#section-14.10).

   The original HTTP/1.0 form of persistent connections (the Connection:
   Keep-Alive and Keep-Alive header) is documented in [RFC 2068](https://www.rfc-editor.org/rfc/rfc2068). [[33](https://www.rfc-editor.org/rfc/rfc2616#ref-33)]
"

if i get more time around I will try to make a reproduction repo 🌮

**Comment by TimoWilhelm** [comment]
I just tested it again today and it seems to work now 🎉
