### ISSUE TITLE
Permission denied for view view_name

### ISSUE THREAD

**Issue by pckimlong** [supabase/supabase#12475]
# Bug report

## Describe the bug

In the past, I've dropped and re-created view normally without any problem, I know why around this week I've tried to drop my old view and create new one with the same name, It got me the error above which say permission denied

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to superbase dashboard and SQL 
2. Create a view
3. Call it from flutter sdk

## Expected behavior

Returns records without given permission denied error

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

Note that only new created view throw this error, All view I've created in the are just working normally

**Comment by GaryAustin1** [comment]
You could run this `select * from  pg_catalog.pg_views` in the SQL eidtor to see if the owners are different (supabase_admin, postgres) which would be a clue it might be caught up in this: https://github.com/supabase/supabase/discussions/9314

**Comment by pckimlong** [comment]
It showed up that the view I've tried to access has the same viewowner as other views which is "Postgres"

**Comment by pckimlong** [comment]
I run this `grant all privileges on all tables in schema public to postgres, anon, authenticated, service_role, supabase_admin;` and it solved my problem.

**Comment by GaryAustin1** [comment]
Are you using Prisma?

**Comment by pckimlong** [comment]
No I am not. I use flutter to connect with supabase

**Comment by GaryAustin1** [comment]
You may want to restart your instance.  

If you create a new table and the problem comes back, definitely something strange going on with your instance.
The command you ran only fixes current tables and it is not clear which role was the issue.

I'm linking this as it provides the grants needed on public schema for all tables/functions and also modifies any future tables to have the correct grants.
https://supabase.com/docs/guides/integrations/prisma#troubleshooting
