### ISSUE TITLE
Realtime Subscriptions not working locally

### ISSUE THREAD

**Issue by ThisIsSimmon** [supabase/supabase#12544]
# Bug report

## Describe the bug

"SUBSCRIBED" is returned to the client side, but the event cannot be listen.
and I don't know why, but the realtime.subscription table does not exist in the local DB.

It is working fine in production.

## To Reproduce

1. Checked "Enable Realtime" for the table in local Supabase Studio
2. Write the following code
```tsx
'use client';

import { createBrowserSupabaseClient } from '@supabase/auth-helpers-nextjs';

export default function Layout({ children }: { children: React.ReactNode }) {
    const supabase = createBrowserSupabaseClient({
        supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL,
        supabaseKey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    });

    useEffect(() => {
        const channel = supabase
            .channel('companies')
            .on(
                'postgres_changes',
                {
                    event: 'UPDATE',
                    schema: 'public',
                    table: 'companies',
                },
                (_) => {
                    console.log('do something');
                },
            )
            .subscribe((status) => {
                console.log('Channel status', status);
            });
        console.log('Channel info', channel);

        return () => {
            supabase.removeAllChannels();
        };
    }, []);

    return { children };
}
```
3. `yarn build && yarn start`

## Expected behavior

Able to listen for changes in the database.

## Screenshots

![CleanShot 2023-02-20 at 13 02 26](https://user-images.githubusercontent.com/23468188/220010923-73a3d22c-f5f1-43af-be3d-31437cf8e1d1.png)

## System information

- OS: macOS 13.2
- Browser: chrome 109.0.5414.119
- Version of supabase-js: 2.8.0
- Version of Node.js: 16.14.2
- Version of auth-helpers-nextjs: 0.5.4
- Version of Next.js: 13.1.7-canary.7
- Version of Supabase CLI: 1.38.4

**Comment by Geczy** [comment]
works for me

**Comment by Geczy** [comment]
just ran into a realtime subscription not working for my production backend server...

**Comment by femans** [comment]
+1. I tried with the example in the documentation of realtime, by simply logging any event to the console. It works for remote, (hosted by supabase), but not locally.  
I also find that the realtime-enabled tables are all realtime-disabled after migrating to local docker instance. But even after enabling them again, realtime does not work.

**Comment by dallastjames** [comment]
Been running into this as well since I updated my CLI from 1.17.x to 1.45.1. The realtime connections work sometimes, usually immediately after restarting the containers. `supabase db reset` doesn't fix it but doing a full `supabase stop` + `supabase start` will get them working again for a few minutes maybe before they just stop working again.

OS: MacOS 13.2
Supabase CLI: 1.45.1
@supabase/supabase-js: 2.12.1

**Comment by bigbizze** [comment]
I found a ghetto workaround here: https://github.com/supabase/supabase/issues/6290#issuecomment-1601861087

**Comment by nbarrow-inspire-labs** [comment]
@bigbizze I believe the issue was fixed here: https://github.com/supabase/cli/issues/1073#issuecomment-1538819824

**Comment by bigbizze** [comment]
I am on `^1.68.6` and was still experiencing the issue

**Comment by Geczy** [comment]
im no longer experiencing the issue either, but i also didn't update my supabase version. its still "^2.21.0" https://github.com/dotabod/backend/blob/master/package.json which makes me think this was fixed in a backend update on the supabase end

**Comment by tayfunyil** [comment]
I have the same issues with subscription. Kind of disappointing. Seems to be a problem people have since last year, if I am not completely wrong ... Downgrading did not help either ...

**Comment by Geczy** [comment]
I switched to Supabase triggers and my problem is gone. Webhooks solve the day

**Comment by tayfunyil** [comment]
> I switched to Supabase triggers and my problem is gone. Webhooks solve the day 

Currently I do not really understand how triggers and webhooks can replace subscriptions. I am developing a hybrid app in Ionic with Vue3.

Each App instance was supposed to subscribe to changes on a table, so I can differentiate whether the new data belongs to this particular user and then update its local data immediately. 

I don't get how Triggers and Webhooks help solving this ...

**Comment by tayfunyil** [comment]
Currently I do not really understand how triggers and webhooks can replace subscriptions. I am developing a hybrid app in Ionic with Vue3.

Each App instance was supposed to subscribe to changes on a table, so I can differentiate whether the new data belongs to this particular user and then update its local data immediately.

I don't get how Triggers and Webhooks help solving this ...

**Comment by nbarrow-inspire-labs** [comment]
Here are the generally troubleshooting steps I use when trying to debug Realtime issues, which have proven pretty helpful so far (some may sound mundane, but I tend to make dumb mistakes myself and this list usually helps my catch them)
1. is Realtime enabled on the specific table (I cannot tell you how many times I forget to check the box turning it on)
2. did I remember to call the `.subscribe()` method at the end of the function creating the subscription (this is for JavaScript, I am not familiar with other frameworks for Supabase)
3. The `.subscribe()` method has a callback for status updates, perhaps the subscription is failing for a network/firewall issue; i.e., something like: ```javascript
.subscribe((status, err) => { 
  if(err) console.err("SUBSCRIPTION ERROR:". err);
  else console.log("SUBSCRIPTION STATUS CHANGED:", status);
})
```
4. is the id I chose for the subscription (in javascript, the ID use in `supabase.channel(SUBSCRIPTION_ID). ...` showing up under the `public.realtime` table? 
5. are the filters applied locally the same/correctly showing in the `public.realtime` table? 
6. have I misspelled or improperly formatted the filter for the subscription (not much type-checking in JavaScript/TypeScript since the filter is a raw string, so the simplest formatting error or column-naming error can cause the subscription to behave in unexpected ways)
7. is the realtime container running (stop and restart supabase, use docker's CLI or GUI to make sure all supabase containers are running, and none have failed)

Hope this helps; this list is not exhaustive, but 90% of the time is enough to catch the errors I'm experiencing.

**Comment by tayfunyil** [comment]
Thank you very much for your response, taking a deeper look at the callback from the subscribe helped I think. What I see here is that the Subscription Status changes a few seconds later after I see "SUBSCRIBED". 

First it's subscribed and realtime works as I see new messages and a few moments later it changes to "CLOSED" and nothing works 🤔

**Comment by nbarrow-inspire-labs** [comment]
@tayfunyil are you using React/NextJS? If so, make sure your component is not unmounting and causing the subscription to close. Also, I find that if I re-use the same channel name/ID that it causes issues, so I almost always use a random UUID for channel names (https://www.npmjs.com/package/uuid). This sounds like you're possibly having a second subscription taking-over/re-using a same channel name, I'd suggest always using a random one.

**Comment by tayfunyil** [comment]
I am using Ionic 7 with VueJS 3. The component where I use the supabase client does definitely not unmount. To be sure I used the onUnmounted-Hook to give me some kind of feedback in case the current component unmounts, but as I assumed, it's not unmounting.

I used the subscription in differnt hooks as well as from the Pinia interface to the localstorage, but none did work. It is closing the subscription always after exactly 10 seconds. 

I was talking to someone from supabase itself with regard to this problem. They told me to try the [Supabase Inspector](https://realtime.supabase.com/inspector) for mocking. Everything works fine from the inspector talking to my supabase instance.

**Comment by saltcod** [comment]
Hi all — going to close this issue as it's been several months with little activity. 
If related issues pop up, please feel free to reopen.

**Comment by soulofmischief** [comment]
@saltcod This is still an issue.

https://github.com/supabase/cli/issues/1851

**Comment by arthurliebhardt** [comment]
Still not working for me locally

**Comment by arthurliebhardt** [comment]
I could fix it for me, I updated the supabase cli, deleted all container did a fresh supabase init and then it worked.

**Comment by encima** [comment]
@soulofmischief let's track that bug in the issue you linked and close this one out.

This issue is a catch-all for realtime not coming up locally and seems to be resolved in the latest versions of the CLI.
