### ISSUE TITLE
`AuthApiError: Signups not allowed for otp` when using `signInWithOtp` with `shouldCreateUser: false`

### ISSUE THREAD

**Issue by rcrogers** [supabase/supabase#13066]
# Bug report

```
> supabase = require('@supabase/supabase-js').createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY)
> await supabase.auth.signInWithOtp({ email: 'foo@bar.com', options: { emailRedirectTo: 'https://example.com/welcome', shouldCreateUser: false } })
{
  data: { user: null, session: null },
  error: AuthApiError: Signups not allowed for otp
      at /Users/rcrogers/Code/fortue-mono/node_modules/@supabase/gotrue-js/src/lib/fetch.ts:42:16
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    __isAuthError: true,
    status: 400
  }
}
```

## System information

- OS: macOS 13.0 (22A380)
- Version of supabase-js:
  - "@supabase/supabase-js@npm:^2.11.0"
  - "@supabase/gotrue-js@npm:2.14.0"
- Version of Node.js: v18.14.2

**Comment by kangmingtay** [comment]
Hi @rcrogers, this is intended behaviour. The `shouldCreateUser` option was added because `signInWithOtp` creates a user by default if the user doesn't exist yet. By setting`shouldCreateUser = false`, it blocks `signInWithOtp` from creating a new user. 

This means that you will need to call the sign up method first, verify the email / phone number and then call `signInWithOtp` to login.
