### ISSUE TITLE
Is it possible to use supabase in the browser without a build process?

### ISSUE THREAD

**Issue by richcorbs** [supabase/supabase#136]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**

I'm new to supabase and it looks supa promising. Haha. Can't wait to play with it more especially with authn and authz being added this week!

My project is small and simple and I'm using alpine.js for the client in the browser. I don't have a build step/process. Is there a way to use supabase from CDN or unpkg.com or similar?

**Comment by awalias** [comment]
great question @richcorbs and something I've been wanting myself as well,

I'll see what we can do this week and will update here

**Comment by kiwicopple** [comment]
Looks like we're missing some [browser targets](https://babeljs.io/docs/en/babel-preset-env) to the babel file - https://github.com/supabase/supabase-js/blob/master/.babelrc

Here are some alternative steps, if we want to migrate to a TS builder (could also progress this:  https://github.com/supabase/supabase/issues/122#issuecomment-671066956)

1. Change the index.js to index.ts
2. Add a `tsconfig.json` with a `module` = `"umd"` and which allows JS so that we can do this incrementally (example here: https://github.com/supabase/pg-api/blob/develop/tsconfig.json)
3. Update package.json to include new Typescript build steps (example: https://github.com/supabase/pg-api/blob/develop/package.json)

**Comment by thorwebdev** [comment]
@richcorbs in the meantime, maybe you can use something lightweight like https://parceljs.org/ to package your vanilla JS app? Here an example: https://codesandbox.io/s/vanilla-supabase-js-with-parcel-j47j4?expanddevtools=1&fontsize=14&theme=dark

**Comment by phamhieu** [comment]
@richcorbs you can use `npm run build:umd` to export standalone supabase.js and use in your project.

[supabase_v0.35.0.js](https://gist.github.com/phamhieu/444060a562a77fe38867c864a43a79e0)

```
<script>
  var client = Supabase.createClient(YOUR_ENDPOINT, YOUR_KEY)
  async function test() {
    var result = await client.from('locations').select("*").limit(17)
    console.log(result)
  }
  test()
</script>
```

**Comment by richcorbs** [comment]
Thanks @phamhieu! I'll give that a try.

**Comment by kiwicopple** [comment]
@phamhieu do you know how we can push this to unpkg cdn?

We could also add it to the homepage docs, similar to how what Thor did here:

![image](https://user-images.githubusercontent.com/5748289/90049864-07e2c380-dd08-11ea-93ab-870f7822781a.png)

**Comment by soedirgo** [comment]
We just need to include a `umd` or `dist` folder in the npm package ([ref](https://unpkg.com/#workflow)). There's also https://jsdelivr.com.

I'll try supporting CDNs when I do the transition of postgrest-js & supabase-js to TypeScript.

**Comment by phamhieu** [comment]
@kiwicopple you can deploy a new supabase-js npm package and umd should be included already

**Comment by kiwicopple** [comment]
Hey @richcorbs, this is now done! Check out our homepage

![image](https://user-images.githubusercontent.com/10214025/91636493-a2931000-ea33-11ea-86d5-796124711b76.png)
