### ISSUE TITLE
[studio] Breadcrumbs in invalid state when going back to /projects route

### ISSUE THREAD

**Issue by 97amarnathk** [supabase/supabase#13659]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Breadcrumbs retain the last seen org and project even when going back to studio home page

## To Reproduce

1. Go to https://app.supabase.com/projects
2. Click on any project
3. Go back
4. Breadcrumb will be `<org>/<project>/projects`
5. On refreshing, breadcrumbs become `Supabase/Projects`

## Expected behavior

Breadcrumbs should be `Supabase/Projects` on the studio home

## Screenshots
<img width="1150" alt="Screenshot 2023-04-12 at 10 19 07 PM" src="https://user-images.githubusercontent.com/17611634/231526980-ab7cfc1e-75c5-4c45-be1a-8efb0cfa9948.png">

## System information

- OS: macOS
- Browser: chrome
- Version of Node.js: 18

**Comment by 97amarnathk** [comment]
Current org and project are fetched from store here.
https://github.com/supabase/supabase/blob/master/studio/components/layouts/ProjectLayout/LayoutHeader/LayoutHeader.tsx#L23

**Comment by MildTomato** [comment]
I think this is just a bug that is mistakenly showing the project name on the home screen when it shouldn't do.
Rather than trying to change what is on the homepage breadcrumb, we should just be showing the below.
<img width="390" alt="Screenshot 2023-04-17 at 3 05 43 PM" src="https://user-images.githubusercontent.com/8291514/232409857-6c73d841-1b42-4a02-805a-5cf9b743aa64.png">

**Comment by 97amarnathk** [comment]
The current breadcrumb state is derived from `projectRef`, `organization`. This is set inside the withAuth.
