### ISSUE TITLE
Announcement Banner Not Keyboard Accessible

### ISSUE THREAD

**Issue by mantism** [supabase/supabase#13934]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Announcement banner cannot be reached via keyboard (arrow keys or tab) and cannot be clicked through via enter

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'supabase.com' or 'supabase.com/docs' and press tab or shift + tab

- Focus ignores announcement banner completely

## Expected behavior

Since the announcement banner is clickable and acts as a link, should be able to navigate to the banner via keyboard and press enter to navigate to the launch-week page

## System information

- OS: macOS
- Browser (if applies) [chrome, safari]

**Comment by gregnr** [comment]
Hey @mantism nice work and thanks again for helping with this (https://github.com/supabase/supabase/pull/13894 reopened & merged).

Can you confirm if this issue is still required? I did a quick test and the banner appears to be keyboard accessible via the changes in https://github.com/supabase/supabase/pull/13894.

**Comment by mantism** [comment]
Yes! Looks good to me now as well 😃
