### ISSUE TITLE
Stability guarantees for database schemas

### ISSUE THREAD

**Issue by dbmikus** [supabase/supabase#14628]
# Stability guarantees for database schemas

## Describe the problem

In a few places in our app, we create views that rely on Supabase schemas and tables in Postgres. For example, views into `auth.users`. I am not sure what the backwards compatibility and stability guarantees are for these database definitions. For API clients, I can rely on [semver](https://semver.org/), but I cannot do this for the database.

## Describe the improvement

Add a description about the backwards compatibility and stability guarantees for database tables or views. What tables, views, schemas, and functions can my app depend on existing?

Additionally, if some database tables are likely to undergo changes, it would be nice to have views that are stable.

**Comment by encima** [comment]
You can depend on tables within the `Auth` schema to be mostly stable but you should not rely on them existing as they are not exposed by the API. They are used for auth flows only. See this [document](https://supabase.com/docs/guides/auth/managing-user-data) on managing user data and using triggers to copy relevant user data into the `public` schema for your use.

 The `public` schema is empty by design and for you to use as you see fit.
