### ISSUE TITLE
Clarify JWT Expiry in Settings

### ISSUE THREAD

**Issue by emschwartz** [supabase/supabase#1474]
# Improve documentation

## Link 

`https://app.supabase.io/project/{project ID}/auth/settings`

## Describe the problem

Underneath the JWT Expiry setting, it says "How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one week)." Does this affect how long users stay logged in for, how long email magic links are valid for, or both?

## Describe the improvement

It would be great to provide an additional comment about what this JWT is used for, or link to somewhere else that it's described in greater depth.

**Comment by MildTomato** [comment]
@kangmingtay Can you verify on the comments above.

#team-frontend can handle changes to description in studio

**Comment by chrisb2244** [comment]
It seems like the token I have in localstorage is valid for the time listed in that field (1 hour, for the default) - the cookies for refresh and access both have the same expiry/max-age, around 24 hours.

Can those cookie expiry times be easily manipulated?
As an aside, what's the purpose (probably obvious, so maybe I'm missing something simple) for having the access and refresh tokens (in cookies) both have the same max-age? Isn't a short-lived access and longer refresh token more typical?

**Comment by kangmingtay** [comment]
Hi @chrisb2244, the max-age value on a cookie just represents when the cookie will expire and not when the token expires. We do use the concept of a short-lived access token vs a long-lived refresh token. 

The access token expiry can be configured via the JWT expiry setting on our dashboard. As for the refresh token, it's a one-time use only cookie and does not have an expiry.

**Comment by saltcod** [comment]
A better description has been added addressing the original concern on this one. I'm going to mark this as closed, but feel free to reopen if I'm missed anything here.

**Comment by oscar-o-oneill** [comment]
I just want to confirm, but what is the maximum JWT Expiry?

Because when I go to https://supabase.com/dashboard/project/XXXX/auth/sessions
I see a "_Time-box user sessions. The amount of time before a user is forced to sign in again. Use 0 for never_."

So is this correct that this means maximum JWT expiry could be set to 0, which means it never expires?

I see on https://supabase.com/docs/guides/auth/sessions

that "_Supabase Auth can be configured to limit the lifetime of a user's session. By default, all sessions are active until the user signs out or performs some other action that terminates a session._" 

So I think actually JWT expiry can be set to 0, or forever!
