### ISSUE TITLE
Handling the Password Reset for a user by Supabase itself.

### ISSUE THREAD

**Issue by MBSA-INFINITY** [supabase/supabase#15718]
**The Problem**
The function `supabase.auth.reset_password_email(email)` only sends a reset mail to the particular email address mentioned with a `PASSWORD_RECOVERY` event but not actually handles the password reset of that account itself, unlike **firebase**. This function `reset_password_email()` should not only just send a password reset mail but also handle password reset with a unique form link specific to that user, so that the particular user can change the password. I hope that clarifies the problem.

**The Solution**
The function `reset_password_email(email)` should generate a unique `supabase form link` which would contain a form to reset the password and this link should be sent to the particular mail as a password reset mail. Once the password is reset successfully, user would be redirected back to the main application. This way supabase users wouldn't have to worry about password reset themselves by handling the `PASSWORD_RECOVERY` event. They just have to call this function and rest, supabse would handle. ***I would be more than happy to take up on this issue and contribute to the supabase community!***

***Firebase Authentication***  have this function `send_password_reset_email()` that does the same thing described above, hence as an alternative to Firebase, `Supabase` should also provide this provision!

**Additional context**
Do checkout this Loom:- [Firebase Password Reset Flow](https://www.loom.com/share/211759ff187e4a8f9dd5d14dd434c7e5)!

Checkout this [Discussion](https://github.com/orgs/supabase/discussions/15717)

@kiwicopple @Ziinc

**Comment by MBSA-INFINITY** [comment]
@gregnr should I take up this issue and start working on it?

**Comment by MBSA-INFINITY** [comment]
> @MBSA-INFINITY thanks for offering! Let's wait for the @supabase/auth team to take a look before working on anything.

is there any update from @supbase/auth team @gregnr ?

**Comment by MBSA-INFINITY** [comment]
> > @MBSA-INFINITY thanks for offering! Let's wait for the @supabase/auth team to take a look before working on anything.
> 
> is there any update from @supbase/auth team @gregnr ?

@gregnr sir?

**Comment by gregnr** [comment]
@MBSA-INFINITY not yet, thanks for your patience!

**Comment by kangmingtay** [comment]
Hi @MBSA-INFINITY, thanks for bringing this up. We have plans to add this internally, however, the team doesn't have the bandwidth right now to tackle this immediately. Seems like firebase serves the form from a `firebaseapp.com` subdomain - if we were to add this in the future, it would have to be an internal change made by the team since it requires code changes to key components of our infrastructure.

**Comment by MBSA-INFINITY** [comment]
Hey @kangmingtay, Thanks for the Update! This addition to the password flow would be an important one, because then users wouldn't have to handle the password reset themselves by capturing the `PASSWORD_RECOVERY` in their frontend! Anyway, Please let me know, if I can contribute to the community in future for this or any other feature development!

**Comment by MOHIDQ** [comment]
Any updates on this feature? @kangmingtay Seems like a very important feature to have for user auth since as of now the update/reset password mechanism is not ideal especially for production. 

Not sure if this would be a simpler solution but Supabase could send a unique code that can be entered by the user and that code is required when trying to update the password for a user rather than having to reroute the user from the email and listen for PASSWORD_RECOVERY event. This solution could work for both change password for authorized user sessions and for forgot password scenarios.  Could also have it where current password is required in the update password request but that would only work for authorized user session.

**Comment by kangmingtay** [comment]
@MOHIDQ have you checked out our [password reset guide](https://supabase.com/docs/guides/auth/auth-password-reset) yet? you don't have to listen for the event and you should be able to redirect the user directly to a page to update their password

**Comment by kiwicopple** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved in the guide that @kangmingtay mentioned

Please do not hesitate to ping me if it is still relevant, and I will happily reopen and it.
Cheers!
