### ISSUE TITLE
Link to documentation from dashboard

### ISSUE THREAD

**Issue by zlwaterfield** [supabase/supabase#162]
# Improve documentation

Currently, there is no link to the documentation on the dashboard. I need to open a new tab, go to the homepage, and click on documentation. I think it should be added to the dashboard for quick access.

What are your thoughts on adding it to the right side of the nav beside the feedback input?

![Screen Shot 2020-08-31 at 9 46 56 AM](https://user-images.githubusercontent.com/6392501/91726895-f3f3ea00-eb6e-11ea-9faf-d629c9d08b6a.png)

**Comment by kiwicopple** [comment]
I'm a big fan of minimal clutter. Little helper links like this add up over time and you end up with little icons and links everywhere.

Ideally our auto-generated docs can become a better resource than the docs on supabase.io - especially since they get the privilege of an entire icon on the sidebar. I'm guessing you're going to supabase.io because the auto docs aren't detailed enough yet?

**Comment by zlwaterfield** [comment]
Correct, that is a good point since there are auto-generated docs it may make more sense to document the shortcomings of them and update them so they are sufficient. I will close this and come up with a list of things that may be needed for parity.
