### ISSUE TITLE
`useEffect` is not recommended in React 18 for data fetching

### ISSUE THREAD

**Issue by Lantianyou** [supabase/supabase#16267]
Hi, `useEffect` is not recommended in React 18 for data fetching.  As explained here in React docs, https://react.dev/learn/synchronizing-with-effects#fetching-data

https://github.com/supabase/supabase/blob/e76b4655c3a60e8b0cc39c3c884f874d763609df/apps/docs/pages/guides/getting-started/tutorials/with-react.mdx#L130

I am starting a new project, and will be happy to submit a PR to change the following docs. But I will be use `swr` as client-side data fetching libs, so one more dependencies. 

React is one of the most popular libs for Web Developers, and React 18 has been stable for more than one year. I think this section of the docs is probably read by thousands of developers daily. So it would be really nice I have the chance to improve the docs for the supabase open source project.

**Comment by gregnr** [comment]
Hey @Lantianyou, thanks for the issue! I think the recommendation isn't as much about avoiding `useEffect` for data fetching as much as it for avoiding it for [data transformation and handling user events](https://react.dev/learn/you-might-not-need-an-effect#how-to-remove-unnecessary-effects).

With that said dedicated data fetching libraries like `swr` and `react-query` are definitely recommended for most apps. For the sake of simplicity in the quickstarts/tutorials though, I'd prefer to keep as few external dependencies as possible so that there are less moving parts for the developer to manage (then they can always refactor after).

I think there are 2 things we can do to improve the current docs:
1. The React docs you linked do recommend adding an ignore condition to the `useEffect` that might be worth adding
2. We can add in a side note (admonition) recommending a dedicated data fetching library like `swr` or `react-query`

More than happy to review a PR for this!

**Comment by Lantianyou** [comment]
Fully agree, for the sake of simplicity, I added 1 in the doc, since the doc is about `supabase`. Here is the PR: https://github.com/supabase/supabase/pull/16385

Thanks @gregnr . Happy to contribute
