### ISSUE TITLE
Bug: Entering Double Quotation Mark in the Input Field of the Command Menu Causes Application Error

### ISSUE THREAD

**Issue by ratnaraj7** [supabase/supabase#16506]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application.
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

## Describe the bug

When entering a double quotation mark (") in the input field of the command menu, it throws an error: "Application error: a client-side exception has occurred (see the browser console for more information)."

## To Reproduce

Steps to reproduce the behavior on the Supabase documentation website:

1. Go to the [Supabase documentation](https://supabase.com/docs).
2. Open the command menu.
3. In the input field of command menu, type a double quotation mark (").
4. Observe the error message.

## Expected behavior

The input should accept double quotation marks without throwing an error.

## Screenshots

https://github.com/supabase/supabase/assets/102022870/cafc1c10-96fb-4a6b-b35f-93cd2b1bedd8

## System information

- OS: Arch
- Browser: Chrome
- Version of supabase-js: Not applicable (issue observed on Supabase documentation website)
- Version of Node.js: Not applicable (issue observed on Supabase documentation website)

**Comment by nwaliaez** [comment]
Hello everyone,

After investigating, I believe this might be a limitation within the library itself (cmdk-supabase), rather than an issue with this repo. As a quick workaround, I've managed to restrict users from inputting double quotes, which seems to prevent the error. However, I'm aware that this isn't the ideal approach.

Since I'm relatively new to open source, I'm unsure about the best way to proceed. Should I attempt to make changes to the cmdk-supabase library to address this issue directly? if anyone has suggestions for a better workaround, I'd greatly appreciate the advice.

Thank you in advance for your help and guidance!

**Comment by saltcod** [comment]
hey @nwaliaez would be ideal to commit to this repo instead of cmdk-supabase if possible. We had to fork that repo because of a compatibility issue, but intend to eventually deprecate it and move back to using the cmdk package.
