### ISSUE TITLE
table edit text column should show as multiple rows

### ISSUE THREAD

**Issue by babyface001** [supabase/supabase#1694]
github issue textarea has 8 row by default.

**Comment by kiwicopple** [comment]
Hey @babyface0-0 - thanks for dropping in! can you please elaborate one what you want to be improved? Perhaps with a few screenshots?

**Comment by babyface0-0** [comment]
@kiwicopple 

![image](https://user-images.githubusercontent.com/34022395/119351243-da816800-bcd2-11eb-9f58-ce3c1958c19a.png)


here text column show N rows by default not just one.

**Comment by babyface0-0** [comment]
I know I can drag it bigger, but it 's good if it shows like above screenshot.

**Comment by kiwicopple** [comment]
Hey @babyface001 - we'll likely keep this as a single-line textarea

The reason is that there is no difference between `varchar` and `text` in postgres (`varchar(200)` is essentially a `text` column with a lenght constraint of 200). It's very common to declare all columns as text - eg


```
create table profiles (
 first_name text not null,
 last_name text
)
```

In the example above, it would be a bit odd to give `first_name` an 8-line text area. I guess we could check if there are any constraints, and show a text area which roughly matches the constraint length, but it's a bit more than we are planning to do (for now). 

I'll close this for now, but keep it in mind that the UX could be improved
