### ISSUE TITLE
Updating email and password in the context of 3rd party provider

### ISSUE THREAD

**Issue by babyPrince** [supabase/supabase#17070]
# Improve documentation

## Describe the problem

How do you handle updating (change) the user email when the user registered with a 3rd party provider? Does a provider always have an email associated? If, for example, the user registered with Google as provider, will updating the email field to "email@mydomain.com" change the provider type to "email"?

Also if updating the email from gmail (quick login or passwordless) to something else, what happens with the password? Do I need to write some custom flow that detects a switch from 3rd party provider to email and then add a prompt step for the user to create a password?

## Describe the improvement

Currently from dashboard > Api Docs > User Management the docs only cover this:

```
const { data, error } = await supabase.auth.updateUser({
  email: "new@email.com",
  password: "new-password",
  data: { hello: 'world' }
})
```

I'm not sure if I'm missing something in the docs tho

**Comment by encima** [comment]
Hi @babyPrince,

Thanks for opening! To answer your question briefly: you do not need to worry about any of these things.

For more detail: you do not need to worry because the 3rd party provider is responsible for those changes. 

If they change their details then the login flow will begin again for them to re-authenticate with Supabase. `email` is not a unique identifier for the user, that is managed by the `identities` table that will have all the information about the different providers that a user has logged in with. 

It is also worth noting that the `email` in the `users` table does not necessarily need to match the user's email with their provider.

I will close this as resolved for now but please do comment if you think it should be clarified further or open a PR if you want to add to the docs.
