### ISSUE TITLE
Feedback button vanishes from Dashboard when opened in mobile.

### ISSUE THREAD

**Issue by NANDINI-star** [supabase/supabase#17705]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Here's the feedback button on Dashboard when screen width > 768px
<img width="1056" alt="Screenshot 2023-09-25 at 11 15 46 PM" src="https://github.com/supabase/supabase/assets/56165694/25f7b49b-2d33-433f-894f-d0474bc72a67">

Here's the issue, when screen width < 768px the feedback button vanishes.
<img width="1056" alt="Screenshot 2023-09-25 at 11 17 11 PM" src="https://github.com/supabase/supabase/assets/56165694/459e6e6c-f38a-4188-99b6-a94c79ba138d">

## To Reproduce

Open Dashboard in mobile, or try to check the responsive dimensions from browser devtools.

## Expected behavior

Feedback button should always be available, no matter what the screen size.

**Comment by MildTomato** [comment]
Hi everyone. 

We are aware of this issue. I think it was hidden to accommodate the breadcrumbs in the top bar which become wider and take up more room on the projects pages. So by changing this, we are are creating a new problem with the org/project and soon to be added 'branch' dropdown for Supabase Branching since they won't have any room.

If it's OK with everyone, we have an ongoing larger discussion regarding navigation UI which will tackle problems like this so everything is consistent between mobile and desktop, as well as hopefully vastly improving the UX of going between projects and organizations and branches.

I'm going to close this one for now but I'll link to the issue from our internal documentation.
