### ISSUE TITLE
User null when following email verification link

### ISSUE THREAD

**Issue by danvoyce** [supabase/supabase#18004]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

I'm using NextJS app router and `@supabase/auth-helpers-nextjs` to sign up users with their email.

When a user verifies their account by clicking the link in their email, I'm checking to see if the `user` exists when they land on the page like so:

```js
export default async function SignInPage({
  searchParams,
}: {
  searchParams: {
    [key: string]: string;
  };
}) {
  const supabase = createRouteHandlerClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (user) {
    redirect("/");
  }

  return <SignInForm />;
}
```

The `user` object initially is `null`. But if I refresh the page then the `user` object returns correctly. 

Any thoughts?

## Expected behavior

`user` object should exist on the first load of the page when following the verification link

**Comment by dijonmusters** [comment]
Hey @danvoyce 👋 Thanks for reaching out!

The user should be available on first render. A couple of things to check:
- looks like this page is a Server Component, rather than a Route Handler, so should be using the `createServerComponentClient` function to create a Supabase client
- make sure you have implemented a code exchange Route Handler - https://supabase.com/docs/guides/auth/auth-helpers/nextjs#managing-sign-in-with-code-exchange
- when signing the user up, the `emailRedirectTo` url needs to point to that code exchange route - https://supabase.com/docs/guides/auth/auth-helpers/nextjs#server-side

So the email the user receives on sign up points to the `/auth/callback` route in your application, and this is where you redirect to whichever page you want them to land on when the auth flow completes. When they are redirected, the user and session should be available on first render 👍

Another good one to try would be create a new Next.js app with this command:

```
$ npx create-next-app@latest -e with-supabase
```

And create a `.env.local` file with a `NEXT_PUBLIC_SUPABASE_URL` and `NEXT_PUBLIC_SUPABASE_ANON_KEY` that point to your Supabase project. Then you can test whether everything is working there and compare the codebases to see where the issue is.

Let us know how you go! 🙌

**Comment by danvoyce** [comment]
Thanks so much @dijonmusters! 

My example was a little different as I'm using `react-hook-form`. However with enough prodding I finally managed to get it to work 🤗

The missing piece of the puzzle was the `emailRedirectTo` property and the `callback` api route.

All working very nicely now!
