### ISSUE TITLE
Docs: document the new setAuth() function

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#1818]
# Chore

## Describe the chore

https://github.com/supabase/gotrue-js/blob/99a11bbdc62700dc2621f522ac1fea5d905c6cc6/src/GoTrueClient.ts#L301

## Additional context

This allows users to "set" the logged in user based on an access token. Most useful for Server Side (extract the access token out of the cookie, then set the user before sending a request)

**Comment by Vandivier** [comment]
I took a crack at this but it actually doesn't work for me - could be my use case I'm in a static nextJS app and I have the session in a cookie but I can't get the supabase client to rehdrate/recognize it

I also notice the currentSession gets created and assigned the auth_token correctly as a bearer, but the actual bearer token is not updated - not sure if that's a problem. See the pic below in case the didn't make sense.


I wonder if making `private _saveSession(session: Session)` to set the whole session instead of just the token would help

Here's a bit of the code I tried:
![image](https://user-images.githubusercontent.com/5559355/120909445-20c7b700-c643-11eb-8140-f223acd7f854.png)

and here's a censored partial of the resulting SupabaseAuthClient where you can see the Bearer isn't updated (again, maybe intentional, but also my request is failing for perms with the service account so this sync fail is my best guess)

![image](https://user-images.githubusercontent.com/5559355/120909507-c3803580-c643-11eb-9b20-5a96ee7c7995.png)

**Comment by farzd** [comment]
not working for me either

```
const supabase = createClient(supabaseUrl, supabaseKey)
supabase.auth.setAuth(access_token);
 const user2 =
  const user =  supabase.auth.api.getUserByCookie()
```

**Comment by abacaj** [comment]
Can confirm `setAuth` doesn't update the anon key and my insert returns error:
>  message: 'new row violates row-level security policy for table "xxx"',

**Comment by kiwicopple** [comment]
Hey @abacaj - would you mind opening an issue for this in the gotrue-js repo? This issue is just for tracking the documentation (which is now completed actually)

It would be good to include some steps to replicate your problem too - I suspect that you are calling `supabase.api.XXX()`, one of the API methods? I can see in the code that only the `GoTrueClient` auth is updated inside the `setAuth()` function, and perhaps you also want the `GoTrueAdmin` headers to be updated too

**Comment by abacaj** [comment]
Turns out it was just user error, setAuth is correctly updating the access token per user for me. I had a incorrect policy.
