### ISSUE TITLE
signInWithOtp using cross browser/device results in 'Never' value in auth.users table

### ISSUE THREAD

**Issue by InterviewAI** [supabase/supabase#18832]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When the user attempts to sign in with OTP, they input their email, receive an email with a link, and then get redirected to our site signed in. However, this only works if the user has their email service open on the same browser that our web application is open on. In the case, let's say, gmail is open in Safari and they send the link in Chrome, the user hits the landing page not signed in. In addition, there is a 'Never' value in the "Last Sign In" column of the auth.users table. We hadn't had this problem until Nov 3. Before that point the only values we observed in the "Last Sign in" column were dates and the "Waiting for verification" badge. I have not seen any mention of the "Never" value in documentation.

I attempted using the fix mentioned in previous bug issues of setting up an intermediate page that the verification email points to and handle verification redirect with a button. This did not fix the issue. It seems like the token isn't compatible between browsers/devices. 

## Expected behavior

The user is able to sign in on any browser and device and be able to consume the verification link that is sent to them.

## System information

- OS: macOS ( however, observed on Safari and on mobile)
- Browser:  chrome, safari
- Version of supabase/supabase-js: 2.38.0
- Version of Node.js: [e.g. 18.13.0]

**Comment by duarte-moneymade** [comment]
There is any update on this? I'm facing the same behavior.

**Comment by rdewolff** [comment]
We are facing now the same issue with www.baboom.app for our bed story generator app 👀

Any update on this?

**Comment by richard-edwards** [comment]
I'm having a similar issue. I'm generating an OTP request on Firefox and clicking the activation link in Brave. On the backend I'm getting the following in the auth logs. I get redirected to my confim page `http://localhost:3000/confirm?code=d566d8a1-11ee-4361-81b3-970b7eb14b9d` so my confirm page just stays waiting for the user login event but it never happens, presumably because of that error but I don't get any error codes passed to confirm so I have nothing to tell the user. To them it just looks like a normal login that sits and waits. Why isn't the confirm page getting error, error_code and error_description like when the token is expired etc.

I understand it needs to be done through the same browser as requested but I'm trying to simulate that and handle the error properly. I guess I could set a timer and if the user object doesn't materialize I can just assume it was a different browser and give them that as a hint.

```
[
  {
    "component": "api",
    "error": "400: code challenge does not match previously saved code verifier",
    "level": "info",
    "method": "POST",
    "msg": "400: code challenge does not match previously saved code verifier",
    "path": "/token",
    "referer": "http://localhost:3000/",
    "remote_addr": "172.21.0.1",
    "time": "2024-04-17T22:21:32Z",
    "timestamp": "2024-04-17T22:21:32Z"
  }
]
``

**Comment by flogy** [comment]
As @andrewmcoupe correctly stated, this is not possible using PKCE flow. As an addition, you could use the [implicit flow](https://supabase.com/docs/guides/auth/sessions/implicit-flow) to get this working.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
