### ISSUE TITLE
Local Dev - Schema dropdown not sorting

### ISSUE THREAD

**Issue by scottpopa1** [supabase/supabase#19022]
I am on my locally hosted Supabase (version 1.112.0). 
I click on the database tab in the nav bar and then click on Tables.
Every table in every schema shows up. When I click on the dropdown and select a different schema, nothing changes. All tables in every schema still shows up. 
![Supabase1](https://github.com/supabase/supabase/assets/94011747/d9bf1ba3-6c76-4373-8301-a321612617c6)
![Supabase2](https://github.com/supabase/supabase/assets/94011747/bd1a5ec3-85a4-4dc5-af16-00f3bcaa7394)

**Comment by Hallidayo** [comment]
Hi @scottpopa1 - Are you still having this issue? I've just tried this locally but it seems the sort is okay.

**Comment by jfoucher** [comment]
Same, here, I have two local instances with the official `docker-compose.yml` file and both exhibit the same behaviour. The same thing happens when adding a foreign key, changing the selected schema from the dropdown menu does nothing 
![image](https://github.com/supabase/supabase/assets/152015/6f909a90-a1ab-422e-89ec-fce78923becc)

**Comment by saltcod** [comment]
This should be resolved on the latest release. Please reopen if you're still seeing this after updating.
