### ISSUE TITLE
uploaded mp4 file is not displaying on desktop

### ISSUE THREAD

**Issue by Lukaso777** [supabase/supabase#19201]
### Discussed in https://github.com/orgs/supabase/discussions/19195

<div type='discussions-op-text'>

<sup>Originally posted by **Lukaso777** November 24, 2023</sup>
I uploaded an MP4 file using my phone, and it displays correctly on the phone. However, when I try to play the video on my desktop, it is not achievable. The video has a status of 206 (Partial Content), and only the sound from the video is playable.

I can see connection to the issue [https://github.com/orgs/supabase/discussions/1739](url), but it is not resolving by problem.</div>

**Comment by GaryAustin1** [comment]
206 is a standard response for media players requesting partial parts of the file.
This seems more like a compatibility issue with your video player or codecs than a bug.  
Since you have a discussion open I'm going to close this here as it is duplicate and this is mainly for issues specific to Supabase code.
