### ISSUE TITLE
Insert row does not show any fields

### ISSUE THREAD

**Issue by styxlab** [supabase/supabase#1940]
# Bug report

## Describe the bug

When I press "Insert row" in the supabase dashboard a side menu would appear with all the fields in the table. This window does not show any fields anymore, so it#s not possible to create a new row in the dashboard.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to a table
2. Click on "Insert row"
3. See side window with now fields
4. Press Save and see error

## Expected behavior

Able to insert row to table in supabase dashboard.

## Screenshots

![image](https://user-images.githubusercontent.com/19638263/121776514-95dc4480-cb8d-11eb-8b6b-e84cf0f8ec5b.png)

## Additional context

This issue is relatively new and appeared a couple of days/few weeks.Problem could be related to a new Prisma schema that uses camel case fields. However, everything works expected when I use direct SQL in the supabase CLI.

**Comment by kiwicopple** [comment]
Hey @styxlab  - I'm not able to replicate this one (or your other issue). 

If possible, could you please run a `pg_dump` of your schema and drop it here so that we can see the structure of your schema. It should be soemthing like this:

```
pg_dump \
-h db.PROJECT_REF.supabase.co \
-U postgres \
-n public \
--clean \
--schema-only \
> supabase_schema.sql
```

**Comment by i-pip** [comment]
I suspect this happens if the table in question was created directly using SQL. 
When you create a table using the new table dialog in the dashboard the primary key has a default value which is auto-generated. When you insert a new row with `null` values, the id is not null, but if the table was created directly with SQL and not the `New table` dialog then the ID field might not have a default value resulting in a null on the ID field tool and thus the error `null value in column "id"`

**Comment by styxlab** [comment]
@kiwicopple + @i-pip: Thanks so much for looking into this issue! Here a link to the schema:

https://github.com/styxlab/supabase_issues/blob/main/supabase_schema.sql

The schema was created with `prisma migrate`, so yes , it was created using SQL and not in the Admin interface. One thing that has changed in the schema is that the user id is now a 'text' field (rather than an INT), but that had previously worked on other tables too.

**Comment by kiwicopple** [comment]
I ran [these lines of text](https://github.com/styxlab/supabase_issues/blob/faad60b5f1a030ff9bf2bb194a7ea2ca3f5a517c/supabase_schema.sql#L204-L222) on a Supabase project and the side panel seems to have picked up the columns:

![image](https://user-images.githubusercontent.com/10214025/121800919-11f68b00-cc67-11eb-9c25-fdd57c9502c8.png)

My guess now is that Prisma is messing with the permissions somehow so that they are not appearing.

Also @styxlab - is there any reason why you have made the PK a `text` field which is not auto-generated? while that's technically not what you're asking in this issue it's a strange choice for a primary key field

**Comment by styxlab** [comment]
Prisma definition looks like, e.g for User
```
model User {
  id            String    @id @default(cuid())
}
```
so a cuid() should be created for each id.

I am basically using a schema as proposed by next_auth here: https://next-auth.js.org/adapters/prisma

Sorry for the indirection, but will definitely try to get this sorted out.

**Comment by styxlab** [comment]
Here is the corresponding prisma schema:
https://github.com/styxlab/supabase_issues/blob/main/schema.prisma

**Comment by styxlab** [comment]
I am now able to cosistently reproduce this problem.

1. Create a new database on supabase.io
2. Create new tables with prisma using `npx prisma migrate dev --name init` 

Note that everything is working fine as expected

3. Clear the database content with prisma: `npx prisma migrate dev --name init`

After that Admin interface seems corrupt and you cannot insert new fields in the interfeace (direct queries to the database seem to work fine).

Plaease confirm if you can reproduce the issue on your end with these 3 simple steps and let me know if you need more info from me.

**Comment by styxlab** [comment]
Can now reproduce the issue without prisma:

1. Create a new database on supabase.io
2. Run the following script to create a table:
```
-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN');

-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "role" "Role" NOT NULL DEFAULT 'USER',

    PRIMARY KEY ("id")
);
```
3. Delete all tables with:
```
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;
```
4. Repeat step 2 to create the table again

After that Admin interface seems corrupt and you cannot insert new fields in the interface.

**Comment by rsdavis** [comment]
I have run into this as well. I set up two environments, one for dev, one for prod, both using prisma. Prod still works fine, but dev does not. The "insert" drawer that opens from the right does not contain any fields. I'm not sure if its related, but before opening the draw I see an error in the dev console.

![Screen Shot 2021-06-20 at 9 58 09 PM](https://user-images.githubusercontent.com/5125437/122701396-c6b61c80-d212-11eb-950d-fc32c11e81f0.png)

Using Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by inian** [comment]
Hi all, this happens because there are a few roles and permissions required for postgrest to function correctly.  

Can you run [these sql commands](https://github.com/supabase/cli/blob/bcf6a8a51885233514cdffe6c516d3c94b6df595/src/templates/init/docker/postgres/00-initial-schema.sql#L13-L25) again and see if it fixes the issue? They are usually run when a project is created in Supabase.

**Comment by styxlab** [comment]
@inian: Thanks for the suggestion, but this script doesn't fix the problem.

**Comment by steve-chavez** [comment]
@styxlab Please also try running this statement:

```sql
grant all on all tables in schema public to anon;
```

**Comment by rsdavis** [comment]
@steve-chavez 

> ```sql
> grant all on all tables in schema public to anon;
> ```

Worked for me

**Comment by styxlab** [comment]
That fixes it for me too, but that's a bit too much granting, isn't it?

**Comment by steve-chavez** [comment]
> but that's a bit too much granting, isn't it?

Yeah, that happens because the dashboard depends on postgrest's OpenAPI output, which in turn depends on the JWT role privileges - `anon` for this case. This will be fixed by solving this [issue](https://github.com/PostgREST/postgrest/issues/1449), then giving privileges to `anon` won't be necessary.

**Comment by MildTomato** [comment]
This issue looks like it's resolved.

Feel free to reopen the issue if this needs more investigation or support
