### ISSUE TITLE
SQL Editor Bug; Wrong line highlighted, in case of error

### ISSUE THREAD

**Issue by electrolyte-orb** [supabase/supabase#19569]
wrong line is highlighted in case of error in query: 

<img width="674" alt="image" src="https://github.com/supabase/supabase/assets/55880176/31065e50-d5c6-429a-aecd-4279f788f9b7">

bug happens only when executing selected query
Expected: error at Line 1 should automatically be translated to error at line 6

**Comment by tranhoangvuit** [comment]
Hi @electrolyte-orb, can you try it with the latest version? I tested it locally, and it still cannot produces errors. Is it possible that the issue is related to our search in the browser?

<img width="1661" alt="image" src="https://github.com/supabase/supabase/assets/21276822/330d1562-9bd2-4ae9-ba36-6c4e1681dc4b">

**Comment by electrolyte-orb** [comment]
@tranhoangvuit your screenshot already shows the error: See the HIGHLIGHTED line... It SHOULD be 6, but it is highlighting at 1
