### ISSUE TITLE
Default column type (bool) doesn't save

### ISSUE THREAD

**Issue by hobbleabbas** [supabase/supabase#1963]
# Bug report

When creating a new column, the default is set to `bool`. However it doesn't register the default value to a True/False select column, and so if you try and create a bool column you get an error unless you switch the column type to another and switch it back.

## To Reproduce

1. Go to table editor and press the new column button
2. Set any name, leaving type to `bool`
3. Click save

## Expected behavior

The default should either be 'Select' or have the True/False default value set.

## Screenshots

Default setup:
<img width="669" alt="Screen Shot 2021-06-13 at 7 39 52 PM" src="https://user-images.githubusercontent.com/74548347/121825215-2181ce00-cc7f-11eb-8f0c-85c88d5cfcbe.png">

Error message: 
<img width="370" alt="Screen Shot 2021-06-13 at 7 40 20 PM" src="https://user-images.githubusercontent.com/74548347/121825224-32324400-cc7f-11eb-918e-de336bf2b938.png">

## System information

- OS: macOS
- Browser (if applies) Safari
- Version of supabase-js: NA
- Version of Node.js: NA

**Comment by zernonia** [comment]
I believe you already have data in that table. Since adding new column that does not `Allow empty`, Postgres will prompt error because it does not know what value to assign to those rows of data. So, you need to either:

1. put a default value (true/false)   OR
2. select `Allow empty` checkbox`  OR
3. (worst) the all the data in the table

Hope it helps!

**Comment by rancherosauce** [comment]
@zernonia I'm facing the same issue and I deleted data since there weren't many rows. But True/False didn't work for me and neither did "Allow Empty". Keeps giving me the same error posted here.
