### ISSUE TITLE
auth event "SIGNED_IN" triggers on tab change (unexpected behavior)

### ISSUE THREAD

**Issue by pixelsage** [supabase/supabase#19825]
# Improve documentation
https://supabase.com/docs/reference/javascript/auth-onauthstatechange

## Describe the problem

Auth event `SIGNED_IN` fires when you change to another tab and back. @silentworks mentioned that this is "expected behavior" (https://github.com/supabase/supabase/issues/7250)

This does not match the label `SIGNED_IN`. The label suggests that a user (who was not previously signed in) signs in. Otherwise, you would also expect `SIGNED_OUT` to trigger when tabs are changed. The existence of `INITIAL_SESSION` does not make this any clearer.

## Describe the improvement

I propose one of two changes:

1. Change the label `SIGNED_IN` to something else that provides a clearer intent of the event. But this may introduce breaking changes.
2. Add clarification in the documentation as to when `SIGNED_IN` actually fires, since the label itself is unclear.

**Comment by MarcusTXK** [comment]
I agree that the `SIGNED_IN` event's label may be misleading currently. Enhancing the documentation for clarity seems like the better approach, as it avoids potential breaking changes associated with renaming the event.

If this issue is still open, I'd be glad to contribute by working on updating the documentation.
