### ISSUE TITLE
Inconsistent Login Behavior After Updating User Email in Supabase

### ISSUE THREAD

**Issue by firstpersoncode** [supabase/supabase#19839]
Description:
I have encountered an issue when using Supabase where, after updating a user's email address, I am able to log in with both the old email and the new email for the same user. This behavior is observed in the context of users who have registered using Google authentication.

Steps to Reproduce:

- Register a user using Google authentication in a Supabase-powered application.
- Log in with the registered user.
- Update the user's email address using `supabase.auth.updateUser` API.
- Attempt to log in using Google authentication with both the old and new email addresses for the same user.

Expected Behavior:
After updating the user's email address, the login should only be possible with the new email address, and the old email address should no longer be valid for authentication.

Actual Behavior:
Both the old and new email addresses are allowing successful authentication for the same user after the email address has been updated.

**Comment by encima** [comment]
Hi @firstpersoncode,

Thanks for opening this. This is expected behaviour. The user's email is in the `user` table but different login methods are stored in the `identities` table. As the email is for the user, it is used with the `email` login method but the `Google` identity is linked to the user's `ID`.

`updateUser` only impacts the `email` provider so it would not affect other `providers`.

I hope this clarification makes sense.

Also, if I misunderstood the issue and different Google accounts are linked to the same user then let me know and we will reopen!

**Comment by johnstonisaac99** [comment]
@encima Is there a way to prevent this behavior. For example my user is able to login with Google using test@test.com and login with test2@gmail.com via email. This is the same user. I think this will cause confusion on the user end. 

Any suggestions on making sure their login email and social Google login email stay the same?

**Comment by johnstonisaac99** [comment]
@firstpersoncode Did you come up with a solution to prevent this, so that social auth email and login email are the same? Thanks

**Comment by laygir** [comment]
I am having similar issues with my users. They want to change the email of their account which was previously used and changed by another account. Even though the user migrated to another email, previous email is still failing when claiming.
