### ISSUE TITLE
bug: SQL editor falsely giving success message

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#202]
# Bug report

(From our community)

## Describe the bug

Errored "commands" are currently showing as success. e.g the screenshot says "Success":

![image](https://user-images.githubusercontent.com/10214025/93278789-31f03f80-f7f8-11ea-8b53-c77be03d0aea.png)

Likely it is caused by the `number` type.

```
CREATE TABLE rows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  component_count number, -- error proably from here
  customer text,
  page integer references pages (id),
  components integer[]
);


```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to SQL Editor
2. Run the command in the screenshot
3. Results pane shows "Success"

## Expected behavior

Show the correct error

## Additional info

- Related: https://github.com/supabase/pg-api/issues/55

**Comment by sarupbanskota** [comment]
![image](https://user-images.githubusercontent.com/3149580/93310831-db0a5a80-f837-11ea-92f8-dd462c630efd.png)

Here's another example where I tried to drop my "pages" table.

I have another table who has foreign keys depending on pages, and that's why the drop failed. But the result says "success".

Can we pipe the response from PSQL and render that instead?

**Comment by awalias** [comment]
![image](https://user-images.githubusercontent.com/458736/94792165-28c3bd00-040b-11eb-8485-6cbffb2bbecc.png)
 fixed thanks to @phamhieu and @soedirgo
