### ISSUE TITLE
How to resume project

### ISSUE THREAD

**Issue by nicitaacom** [supabase/supabase#20378]
![I got this](https://i.imgur.com/nh7iJ5J.png)

I got this when I want to resume my paused project

I have 2 projects in this organization - as I see system think that I'm going to create third project - but I just want to unpause current

**Comment by KevinBrolly** [comment]
Hey @nicitaacom - since this is a issue is with your specific account and the hosted platform you might be better to open a support ticket at [supabase.help](https://supabase.help/) so that we can see specific details of your account.

I will also say there is a maximum of 2 unpaused free projects per account, so you may have to pause one of the current 2 projects in your organisation to unpause the third one.
