### ISSUE TITLE
Request to be able to delete user

### ISSUE THREAD

**Issue by zlwaterfield** [supabase/supabase#205]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, there is no way to delete users. Previously I was able to do `DELETE * FROM "users" where email = ${email}` but that is no longer working.

## Describe the solution you'd like

Can we enhance the user's table to add the abilities to remove the users?

**Comment by kiwicopple** [comment]
Good idea @zlwaterfield - we should also give the ability to "add" users from the dashboard

> . Previously I was able to do DELETE * FROM "users" where email = ${email} but that is no longer working.

Seems odd, but I imagine it's because there is a table referencing the user, so it won't delete the user. If that is the case, you can specify the "referencing" tables to remove rows when you set them up using the `CASCADE` command:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/10214025/93731158-70be3500-fbfe-11ea-890c-660557db7cb4.png">

**Comment by kiwicopple** [comment]
Forgot to loop back here! This is now in the dashboard - 

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/10214025/102911772-79e9c700-44b7-11eb-9df5-fd6c5e2ca010.png">


You will still have to handle any situations where you reference the `auth.users` table though. Eg, you will have issues trying to delete a user that you are referencing from the `public` schema
