### ISSUE TITLE
Log Explorer -  `Insert Source` should insert source at cursor or in FROM clause

### ISSUE THREAD

**Issue by robpetty** [supabase/supabase#20883]
# Bug report

I noticed a small UI issue in the Logs Explorer feature, specifically related to Insert source.

## Describe the bug

- Navigate to Logs->Query
- Change Insert source.

Expected to insert source where cursor is currently or, alternatively, replace the source in the `from` clause

<img width="545" alt="image" src="https://github.com/supabase/supabase/assets/1473437/0bf9f1cc-eb21-40fe-9beb-26aa582971a6">

Actual:

Appends to end of text regardless of cursor position

<img width="496" alt="image" src="https://github.com/supabase/supabase/assets/1473437/9a55cb78-a926-4ab6-9a35-e527815b244d">

## To Reproduce

1. Navigate to Logs Explorer and see default query
2. Select new source from `Insert Source`

## Expected behavior

Query is correct.

## Screenshots

See above.

## System information

- OS: macOS
- Chrome Version 121.0.6167.85 (Official Build) (arm64)

**Comment by encima** [comment]
Hi @robpetty,

Thanks for reporting. This is a bug but, I think, not in the way you reported.
- `Insert source` - purely adds the source selected (although the bug is that is could/should replace the current source in the `from` clause)
- `Templates` - This is the button you are looking for and this creates correct queries

I will update this issue to to reflect this

**Comment by robpetty** [comment]
@encima thanks for the explanation.  Makes sense.

**Comment by santosh2345** [comment]
I want to solve this issue and contribute.

**Comment by encima** [comment]
@santosh2345 Excellent! Feel free to open a PR and mention this issue in the description

**Comment by joshenlim** [comment]
Resolved by https://github.com/supabase/supabase/pull/21114
