### ISSUE TITLE
[Dashboard] layout bug, site wide notification banners not in flex box

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#20902]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

- Flex Layout issue when notification banners are shown 
- This means the bottom part of the side bar is not visible when the banner is shown.
- Whole layout of banners and dashboard nav and main probably need to be in a flex box.

<img width="1673" alt="Screenshot 2024-01-31 at 11 54 40 PM" src="https://github.com/supabase/supabase/assets/8291514/50aafa8c-9670-41e4-90ca-779d4f288721">

https://github.com/supabase/supabase/assets/8291514/780c078c-34e2-4124-95cf-250006b09098

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to dashboard when notifcation banner is shown

**Comment by UtkarshDixit-py** [comment]
Hi @MildTomato, I am interested in working on this. Please assign the issue to me.

**Comment by MildTomato** [comment]
@UtkarshDixit-py we currently only assign issues to active maintainers or regular contributors.

Feel free to post a PR and we'll review 🚀 😃

**Comment by UtkarshDixit-py** [comment]
@MildTomato Can you expand a little bit more on the bug?

**Comment by MildTomato** [comment]
updated issue description

**Comment by pandey079** [comment]
Hi @MildTomato, I am interested in working on this. Please assign the issue to me.

**Comment by MildTomato** [comment]
https://github.com/supabase/supabase/issues/20902#issuecomment-1919618965

**Comment by SwapnilSonker** [comment]
getting error when setting up the environment to solve the bug, how should I set up the supabase to run on my localhost @MildTomato, tell me please..

**Comment by SantoshPisini** [comment]
@MildTomato Are you still seeing this issue? 

I'm unable to repo this.
[side_nav_issue.webm](https://github.com/supabase/supabase/assets/39261271/ca40e851-16e6-452c-af5a-f91f0dd4705c)

**Comment by Mohammed-Yasin-Mulla** [comment]
I was able to solve this partically,
I had first artifically put the banner in by removing the condition 
![image](https://github.com/supabase/supabase/assets/55092280/9f70857c-e9e7-4a0a-91d1-88c6e17e9cdd)

I had added the value to `appHeaderHeight` helping in resolving the scroll issue
![image](https://github.com/supabase/supabase/assets/55092280/29da86a4-345e-4bab-8baf-1d7f6a2d8111)

This a screen recording of the fix: 
https://github.com/supabase/supabase/assets/55092280/cffa6f25-8d0c-423a-b749-06ce943c60a8

**Comment by MildTomato** [comment]
Nice one @Mohammed-Yasin-Mulla 

Can anyone solve this without 'magic numbers'

feels like we should just be using flex box and not having to dictate any height of anything.

**Comment by Mohammed-Yasin-Mulla** [comment]
Actullay yes, I taught of doing that, will move into that direction

**Comment by Mohammed-Yasin-Mulla** [comment]
@MildTomato, I have been trying multiple ways to sove this issue but was unable to do so.
here's a summary of the approaches we've tried to make a child element take up the remaining height of the screen in a parent div:
1. **Flexbox with `flexGrow: 1`**
2. **JavaScript to set the height dynamically** 
3. **CSS Grid with `gridTemplateRows: 'auto 1fr'`**: I tried to use CSS Grid to create a layout with two rows: one for the header and one for the content. I then set the height of the content row to `1fr` to make it take up the remaining space. 

The 3rd approch seems to be more promising but I still dint get the desired result.

As far as I know, please correct me if I am wrong. Flex does not risctict elements to be only inside the screen height, which makes the elements overflow. 
further more inspecting each element from the panel,
the child element takes up height that it requires to fit in even if the parent is height is shorter.

![image](https://github.com/supabase/supabase/assets/55092280/fc5f0790-f3e8-4638-8f19-8f8df6838ddf)
![image](https://github.com/supabase/supabase/assets/55092280/419341ba-8ca9-4929-a37e-865c2889d847)

I think we should seperate the side bar to be a different element  rather than combing the conent page with the side bar in one parent `div` if that makes any sense  (which is increasing the side bar height )

**Or**

We can stick with the initial approce of calucating the screen height correcly 😅 

File names where changes were done in:
- `AppLayout.tsx`
- `AppBannerWrapper.tsx` (where the banner and the rest of the children are)

If there are any other alternative approces please do share I will give it a short.

**Comment by charislam** [comment]
The trick to making flex work is to set min-height 0 on the element you want to restrict:

<img width="561" alt="image" src="https://github.com/supabase/supabase/assets/26616127/946d108c-0708-4283-aeed-d3cda7a05cc0">

**Comment by Mohammed-Yasin-Mulla** [comment]
Thank you for the advice @charislam,
It worked. I have also attached a video on how it would look like if multiple banners were present.

**Comment by nidhipawar5** [comment]
Interested in working on this. Thanks

**Comment by joshenlim** [comment]
Resolved by https://github.com/supabase/supabase/pull/21069
