### ISSUE TITLE
bug: Can not delete a user: `property is_anonymous should not exist`

### ISSUE THREAD

**Issue by kishanhitk** [supabase/supabase#21844]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am unable to delete a user. Getting this error. This is happening since I upgraded my project to pg `15.1.1.24`. 
![image](https://github.com/supabase/supabase/assets/41117038/98d1d45c-2628-418e-a661-3e05cde7fc7d)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a supabase project (ignore if you already have a project)
2. Update the pg version to 15.1.1.24
3. Try to delete the user, and you will get the error.

## Expected behavior

The deletion should work.

## System information
Postgres version: 15.1.1.24

## Additional context

This is most probably related to this PR(https://github.com/supabase/gotrue/pull/1460). The anonymoys signin has been implemented in gotrue, but the supabase dashboard APIs has not been updated accordingly yet.
Discord discussion thread: https://discord.com/channels/839993398554656828/1215312132900392981/1215312132900392981

**Comment by kangmingtay** [comment]
hey @kishanhitk, we've just put out a fix for this - it was an issue with validation on the platform API

**Comment by tecoad** [comment]
@kangmingtay i am running a supabase project with a colleague, but i noticed seeds are faling because my database has the column auth users.is_anonymous and his doesnt.

Tried to upgrade supabase CLI and rerun docker, however no success. For some reason his schema doesnt have that field.

Can you clarify this?

**Comment by tecoad** [comment]
@kangmingtay  i am running a supabase project with a colleague, but i noticed seeds are faling because my database has the column auth users.is_anonymous and his doesnt.

Tried to upgrade supabase CLI and rerun docker, however no success. For some reason his schema doesnt have that field.

Do you have any clue on this?
