### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by SlavenDj** [supabase/supabase#22045]
I have found some UI bugs on this URL:
![image](https://github.com/supabase/supabase/assets/53652906/b6ea7b73-eb88-44e0-b42e-a9a3ae962ab7)
![image](https://github.com/supabase/supabase/assets/53652906/8c596a54-61f0-4a89-8dbd-9eb08477a582)
![image](https://github.com/supabase/supabase/assets/53652906/f1ff06a5-1248-4342-9d71-a810e3a4cbe7)
![image](https://github.com/supabase/supabase/assets/53652906/c9967f6c-b601-4dcc-a647-95df5eab3db3)

https://supabase.com/dashboard/project/buinnmiljwmjndusside/logs/explorer

I think it is beacuse of unstable network but I can not be sure. It happends both on stable and unstable networks, at least to me. I would like to know what info would you need from me to help you fix this UI bugs.

Syntax headlining is normal after I change the tabs on the side bar of the app:
![image](https://github.com/supabase/supabase/assets/53652906/1dcbc22f-8f06-4c19-8318-1f7d9d1a0522)
.mtk1 class was set to have prop color:#000 and after color:#d4d4d4

Also this should be improved:
![image](https://github.com/supabase/supabase/assets/53652906/2f60fbcb-c81d-491f-9032-b4c8c2f4b1f2)

**Comment by christianhubbard** [comment]
I have noticed similar UI bugs and I have tried to make a PR to fix at least one part of this. 

The issue is the `sameWidthasTrigger` default prop on the popover component. I think that this should default to false.

https://github.com/supabase/supabase/blob/b4fde9b3c79da5b2cbf44e259b39c1f2dc819724/packages/ui/src/components/shadcn/ui/popover.tsx#L28
