### ISSUE TITLE
docker-compose.yml pass true values as strings

### ISSUE THREAD

**Issue by cabiamdos** [supabase/supabase#22571]
when doing `docker-compose up -d`
![image](https://github.com/supabase/supabase/assets/82284393/540a4607-58fd-495d-ad3b-e9d269771cfc)
```
      NEXT_PUBLIC_ENABLE_LOGS: true
  LOGFLARE_SINGLE_TENANT: true
      LOGFLARE_SUPABASE_MODE: true
``` 
should be passed as strings like this 'true' because docker compose doesn't alllow to pass boolean values (https://devops.stackexchange.com/questions/537/why-is-one-not-allowed-to-use-a-boolean-in-a-docker-compose-yml)

And also I had to remove name: property

**Comment by encima** [comment]
Thanks for opening. 

- Can you explain the problem you had?
-  Was an error printed when running the commands?
-  What system are you running?
- Was it the latest commit?
- Is this using Docker or Orbstack or Podman or something else?

Docker Compose does support booleans (there are no official docs to say otherwise), it is only the YAML spec that requires specifying in case the parser has issues. In these cases, the keys are correct and picked up:

<img width="563" alt="image" src="https://github.com/supabase/supabase/assets/517923/d29e3615-aefa-4d3e-bc3a-8ca4dd0b52f7">

**Comment by cabiamdos** [comment]
okay as you can see I run out of space. I am running the latest supabase commit,
![image](https://github.com/supabase/supabase/assets/82284393/b753fbad-80f9-4cf6-9f0f-9821b509bb6d)
this was exactly the error.

But I believe it is because I installed doing `sudo apt install docker.io docker-compose` instead of following this guide (https://docs.docker.com/engine/install/). I didn't followed this guide because I was using kali linux (in the example above), parrot and arch linux which none of them appear them as a installation.

Now I opened a new container with ubuntu and followed that guide to install docker.
![image](https://github.com/supabase/supabase/assets/82284393/307129de-5b5d-40bd-9e74-745d965c5ad4)

But I believe that was the problem. In any case if you are using `docker-compose` instead of the new `docker compose` plugin you need to do what I said. Now I couldn't finish it at all because I run out of space. I also mounted up with docker-compose (in my kali machine), the interface worked and all the containers worked but I had more errors. And I tried removing the postgres from supabase and using my external one but I was having lot of problems too although I changed the wal_level and looked at the containers logs. Thanks
