### ISSUE TITLE
Performance Advisor "Auth RLS Initialization Plan" Warning 

### ISSUE THREAD

**Issue by lakeesiv** [supabase/supabase#23185]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

With the new performance advisor, I get the following for my table

![image](https://github.com/supabase/supabase/assets/71339072/1f2aa061-48a2-456b-ad6b-2edad98b4e6a)

After updating the RLS policy:
![image](https://github.com/supabase/supabase/assets/71339072/f403eba5-cada-4ff9-89fc-0e1864a47b13)

The warning on the performance advisor does not go away

Seems like I am not the only one who has this error: https://www.reddit.com/r/Supabase/comments/1ca5gri/auth_rls_initialization_plan_warnings_not_going/

## To Reproduce

-  Have a table with rows that can only be edited by a user with their user_id 
   eg: Table called `feedback` with rows: `feedback_id: int8`, `user_id: uuid` with forgein key to `auth.users.id`, `content: text`
- Apply the RLS rule for enforcing updates
```sql
create policy "allow users to edit their own feedback" on "public"."feedback" as permissive for update to authenticated using ((( SELECT auth.uid() AS uid) = user_id));
```

## Expected behavior

Warning goes away

## System information

-  Issue with hosted Supabase

**Comment by cyluss** [comment]
Yes I noticed the behavior too. I avoided warnings by extracting whole using conditions into 'security definer' functions, or db function that inspects auth informations and returns boolean.

Please start from approach 2 is_admin function in the [RLS best practice discussion](https://github.com/orgs/supabase/discussions/14576). And please be advised that it has somewhat steep learning curve. IMO It should be a part of documentation but it is what it is for now.

**Comment by encima** [comment]
@cyluss is right here, the linked guide is optimal and it is linked in the docs as a reference but maybe should be more explicit. Ideas and PRs are welcome here! Will leave this open for ideas.

**Comment by cyluss** [comment]
@encima You are right, [RLS performance recommendation](https://supabase.com/docs/guides/database/postgres/row-level-security#call-functions-with-select) guide is indeed linked under Issue section. Usually I skip to Resolve section
![image](https://github.com/supabase/supabase/assets/41672371/b346dc93-0372-440f-b1f6-5799e8f9067d)

I see some improvements to [advisor document](https://supabase.com/docs/guides/database/database-advisors?queryGroups=lint&lint=0003_auth_rls_initplan#how-to-resolve): 
1. Add 'Use security definer functions' recommendation. Currently the document says only 'call functions with select'
2. Add Reference section. Since readers are navigated from Supabase dashboard in this scenario, it is better to guide readers to locate relevant document.

I also see a small fix for Overview panel in [advisor issue view](https://supabase.com/dashboard/project/ovldsgmrhhthxznqvatn/advisors/performance?preset=WARN)

- Change docs link in Issue section to 'Learn more' inline element, to make the style consistent among the sections and make the link easy to spot

**Comment by cyluss** [comment]
Since [database advisor page](https://supabase.com/docs/guides/database/database-advisors) loads individual pages from `supabase/splinter` project, relavant documentation changes must be applied to the repository

**Comment by cyluss** [comment]
The fix for overview panel cannot be applied due to the following:
1. Description section is implemented with markdown component, therefore only standard HTML elements can be used.
2. LinterGrid have exactly one external link per lint info.

I expect that documentation change will cover the problem scope.

**Comment by cyluss** [comment]
@lakeesiv I was not able to reproduce the behavior now, could you please check again whether the issue still affects your project?

**Comment by lakeesiv** [comment]
Can confirm the issue is now gone!
