### ISSUE TITLE
500 errors on Edge Functions again.

### ISSUE THREAD

**Issue by jamesshamim123** [supabase/supabase#23288]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The same issue is appearing as happened earlier this week. Edge functions returning 500 errors. 

## To Reproduce

Execute edge functions

## Additional context

This is the same issue that was widely reported earlier this week and fixed. It seems to have happened again. I'm in Australia so will be on your Singapore servers.

**Comment by bnielsencodes** [comment]
I seem to be experiencing the same thing. I followed the _user management app with next.js_ tutorial on localhost it worked fine, but now I'm getting a 500 error with the message "Error: Your project's URL and Key are required to create a Supabase client!" when deployed with Vercel.

**Comment by encima** [comment]
Thank you for reporting this!

However, for time-sensitive issues and issues related to hosted services, it is best to open a support ticket as the issue here does not necessarily related to the code in this repo or is something that can be fixed with a PR.

To check if there are any recognised issues or incidents, check out our [status page](https://status.supabase.com/)
