### ISSUE TITLE
Supabase dashboard login screen doesn't redirect after singin

### ISSUE THREAD

**Issue by Honzoraptor31415** [supabase/supabase#23665]
# Bug report: Supabase dashboard login screen doesn't redirect after singin

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The [sign in](https://supabase.com/dashboard/sign-in?) often doesn't redirect you after clicking "Sign In", when signing in with email and password.

## To Reproduce

1. Go to [the signin page](https://supabase.com/dashboard/sign-in?)
2. Fill in your email and password in the fields
3. Click "Sign In"
4. Wait a few seconds
5. You should be redirected, but nothing happens
6. Click the "Sign In" again and see this error:
![error-screenshot](https://github.com/supabase/supabase/assets/151644171/607959b5-81c2-4b55-887e-428da19e2f7b)
saying that you're already logged in

## Expected behavior

It should redirect you to the [dashboard](https://supabase.com/dashboard/projects)

## System information

- OS: Windows
- Browser: chrome

## Additional context

This happens only with email and password login, not with oAuth. Also after you click the "Sign In" for the 3rd time, it usually works.

**Comment by encima** [comment]
Hey there,

To confirm, this is happening on the dashboard and not within your own projects using Auth, is that right?

**Comment by Honzoraptor31415** [comment]
> Hey there,
> 
> To confirm, this is happening on the dashboard and not within your own projects using Auth, is that right?

Yes, of course, why would I link you to the supabase dashboard, if it was a problem with my project.

**Comment by simonha9** [comment]
I can take this - the issue description is not quite correct, there is nothing wrong with the signin page itself, I am able to sign in when the link is as such: https://supabase.com/dashboard/sign-in? , sometimes there is a `returnTo` query param in the link like https://supabase.com/dashboard/sign-in?returnTo=%2Fprojects and signing in with this will still work.  

The issue (afaict) is when the `returnTo` parameter is `sign-in` so you sign in and return to the same page, which is why there is no redirect.  The only place I've found this to be the case is when the user clicks `Log Out` and gets redirected to https://supabase.com/dashboard/sign-in?returnTo=%2Fsign-in and now we have the issue described
