### ISSUE TITLE
I cannot login using AUTH ui via email. 

### ISSUE THREAD

**Issue by RobicaCodeaza** [supabase/supabase#25910]
# Bug report

## Describe the bug

When i am using Auth Ui I am trying to login via basic email , I even confirm the mail but the app doesn't sign in. However when I am using google sign in the user gets updated and it will log to my app.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by encima** [comment]
Hey there, thanks for opening.
We are gonna need a bit more info to help with this, please.
Your app has the code to handle the sign in so that is the place to start!

It sounds like you are receiving the email? If you refresh the page, is the user logged in?

Can you provide:
- the framework you are using
- the related snippet
- the error you are seeing

**Comment by Hallidayo** [comment]
Hi all, I'm going to move this over to the auth-ui-repo (thanks @FatumaA)

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
