### ISSUE TITLE
When update not allowed by RLS, it passes without errr message

### ISSUE THREAD

**Issue by step135** [supabase/supabase#27391]
I am not able to distinguish when update succeeds or not.

**Comment by Hallidayo** [comment]
Hi @step135 - thank you for opening the issue, Could you provide a bit more information:

- Where are you getting this issue?
- Could you post the error message you are getting?
- Any screenshots/videos as well please

**Comment by Hallidayo** [comment]
Hi @step135 - Could you send over a specific example please?

**Comment by step135** [comment]
Why specific example? It happens with every possible example!!!

**Comment by Hallidayo** [comment]
Hi @step135 - If this is happening everywhere, please provide the steps you followed when creating a new project, tables created and the RLS policies in place. 

If we cannot reproduce then we cannot help I am afraid.

Alternatively, if this is happening on hosted Supabase, you could open a Support ticket so that the team can help you debug your project.

**Comment by step135** [comment]
Why should I need any help? Yes, it is on hosted Supabase, but why should it matter??!!! Instead of writing again and again you never tried to replicate this issue. How is it possible? Then it doesn't make sense to continue the discussion with you.
