### ISSUE TITLE
Fresh install Supabase follow the official guide faced TONS OF ERRORS

### ISSUE THREAD

**Issue by joewin319** [supabase/supabase#27589]
Hi all, i want to test supabase on my own ubuntu VM. i just follow the instruction here https://supabase.com/docs/guides/self-hosting/docker. Without changing anything, i follow these steps.
<img width="203" alt="image" src="https://github.com/supabase/supabase/assets/79684516/694ebd30-bdb1-4638-a522-6df2dcfc71bc">

These are the container status:
<img width="266" alt="image" src="https://github.com/supabase/supabase/assets/79684516/a766f4c3-3f29-44d9-a840-ca9bf9ab6590">

This is the supabase-analytics logs :
<img width="269" alt="image" src="https://github.com/supabase/supabase/assets/79684516/f7d0dfba-4572-492e-82a3-adddcd665ab2">

I suspect it crashed in supabase-analytics which contribute to the storage-api, realtime-dev.supabase-realtime, supabase-rest, supabase-kong keep restarting.

May i know what should i do to solve this issue?

I had try to resolve by:
docker system prune -a
rm -rf docker/volumes/db/data
docker compose up

I also try to exec it into supabase-db:
ALTER USER supabase_admin WITH PASSWORD 'your-super-secret-and-long-postgres-password';

But the problem stil presists. My situation is difference from the other post is that i did not change any credential, i followed the official guide to fresh install.

**Comment by tranhoangvuit** [comment]
Hi @joewin319, I tried to reproduce the issue by following your steps, but it worked fine on my local machine. Can you try again with this command to clear your local environment first:
```
# Stop docker and remove volumes:
docker compose down -v

# Remove Postgres data:
rm -rf volumes/db/data
```
and if the error still occurs, can you share with us the log details from log-flare or any other error logs? Your uploaded image is quite small, making it hard to see the details.

**Comment by SebasScript** [comment]
there is a related issue here in the supabase cli repo

[Error 502 Cannot access logs in Local Development #2509](https://github.com/supabase/cli/issues/2509)

The problem seems to be coming from some recent changes due to which the monitoring service (supabase vector) requires the use of docker socket access which is granted by docker by default and is also managed differently on windows vs osx.
It also seems that the socket access can only be granted on docker desktop  (see comment on the linked issue) when one has an enterprise subscription, which could explain why its working for some while not for others (maybe supabase team has docker enterprise subscription). I have the same problem since i updated to latest version of cli a couple days ago.

only fix right now it to use

```
supabase start --ignore-health-check
```

Supabase cli  will still run the other containers but the monitoring service wont work, which is a hassle because can't monitor any queries in local dev at the moment.

**Comment by encima** [comment]
Hello, it seems there are a few open issues about this so, in an effort to clean up, we will consolidate to this one [here](https://github.com/supabase/supabase/issues/26785#issuecomment-2227119475).

The issue is mostly solved and a fix for the frontend query is coming soon.

As for the Docker issues, those are docker specific and I am unable to reproduce using Podman or Orbstack on OSX.
