### ISSUE TITLE
CORS Error for Auth Request from React app to local Supabase

### ISSUE THREAD

**Issue by edward-20** [supabase/supabase#28008]
## Describe the bug
In my react app, I make a request with the supabase client to the auth service running locally (created with `supabase start`). As a result I get:
![cors_supabase](https://github.com/user-attachments/assets/2e3be317-fd3f-456d-a29a-99ad569d6db1)
'Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:54323/auth/v1/signup. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 404.'

## To Reproduce

Here's the exact code (React) causing the error:
```
  const handleSubmit = async (event) => {
    event.preventDefault();
    let {data, error} = await supabase.auth.signUp({
      email,
      password
    })
    if (error) {
      alert(error.message)
    } else {
      navigate('/user')
    }
  };
```

## Documentation
I have read:
https://supabase.com/docs/guides/cli/config
To see which configurations I need to change to permit CORS request. Here's the relevant section of my config.toml

```
[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
```
which I believe should be correct in order to receive a successful preflight-cors response.

This doc on [cors for edge functions](https://supabase.com/docs/guides/functions/cors) isn't relevant to my issue.

## Issues raised that have been similar
I've read these issues that are similar:
[Exactly the same problem,  Self-hosted with docker: Where in the config do I allow CORS requests for the auth server? #15867](https://github.com/supabase/supabase/issues/15867)
The solution was related to port visibility in vscode, but that didn't seem to be relevant or resolve my issue above. 

[Similar but receiving the CORS Error with the REST API,  Supabase CORS Error on REST API Requests: No 'Access-Control-Allow-Origin' header is present #7627](https://github.com/supabase/supabase/issues/7627)
The solution seemed to be quite specific and related to CAPTCHA inflating the JWT and Supabase being unable to handle a request with such a large payload. But that's not the case for my issue. 

## System information

- OS: Windows and WSL
- Browser: Firefox
- Version of supabase-js:  "@supabase/supabase-js": "^2.44.2",
- Version of Node.js: v21.1.0

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

**Comment by ritanshu747** [comment]
To resolve this issue with Supabase, you need to ensure that Supabase is configured to include the necessary CORS headers in its responses. Based on the information you've provided and the Supabase documentation, here's how you can address it:
Configuring CORS in Supabase

    Check Supabase Documentation: According to Supabase documentation, you need to configure CORS settings for your project. Typically, this involves specifying the allowed origins for CORS requests.

Supabase Dashboard:

1-Navigate to your Supabase project dashboard.
2- Look for a section related to CORS settings. It's usually under project settings or API settings.

Edit CORS Settings:

1. Add http://localhost:3000 (or https://localhost:3000 if using HTTPS locally) to the list of allowed origins. This is necessary  because your React application is hosted on localhost:3000 and is making requests to localhost:54323.


    Save Changes:

1.  After adding http://localhost:3000 to the CORS settings, save the changes. Supabase should now include Access-Control-Allow-Origin headers in its responses when requests come from localhost:3000.

**Comment by edward-20** [comment]
There doesn't seem to be any CORS settings nor settings in general in Supabase Studio.
![Uploading absence_of_settings.png…]()

**Comment by encima** [comment]
Hey @edward-20,

That is right, as you are running it locally, the hosted Settings pages are not available but you have configured this correctly using the `config.toml` file.

Are you running Firefox within WSL? It might be that the network is not configured to be available outside of WSL so the CORS request is failing.

**Comment by edward-20** [comment]
I am running Firefox, but just on Windows.

**Comment by encima** [comment]
@edward-20 thanks! keep us posted with any updates plz!

**Comment by matthewhoth** [comment]
@edward-20 Did you ever get this up and running?

PS, you couldn't find CORS in Supabase because the first guy's reply was ChatGPT generated and it just made up that section.

**Comment by 20IR** [comment]
Hi, has anyone solved this?

**Comment by edward-20** [comment]
Hey, really sorry 20IR, but I installed Firefox on wsl and it seemed to work. Please lmk if I can help

**Comment by dorage** [comment]
I struggled with this problem for a long time today.
I'm leaving this here in case anyone needs help.
Port 54323 is default port for the studio ui.
Port 54321 is default api port
`http://127.0.0.1:54321` should be the supabase url for supabase client.

**Comment by Karl-EdwardFPJeanMehu** [comment]
Bump!

**Comment by dhertzb** [comment]
I'm running my project on the github codespace, it maps the ports in diferent domains.

My front end **localhost:3000** is translated to **https://didactic-space-couscous-5x4xwgvxx7qcv75r-5173.app.github.dev/**

I tried to configure the config.toml to the following:

```
[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "didactic-space-couscous-5x4xwgvxx7qcv75r-5173.app.github.dev"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["didactic-space-couscous-5x4xwgvxx7qcv75r-5173.app.github.dev"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true
```

but I still receiving the cors error when I try to login 

![Image](https://github.com/user-attachments/assets/5323981d-c480-4538-a761-17d584f11cda)

**Comment by younes-ammari** [comment]
I happens to me too
i'm running supabase locally in my server (127.0.0.1), i can access the supabase server using my server ip, but when i try to upload file to the bucket i gives me error:

> demo:1 Access to XMLHttpRequest at **'http://server_ip/storage/v1/upload/resumable'** from origin **'http://server_ip:54323'** has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource


first i had other issue whenever i upload file says:  'http://127.0.0.1/storage/v1/upload/resumable'  not found, which i solved by changing the 127.0.0.1 value in config.toml to use my server ip ..

but i still have the CORS isseu, i couldn't find where to configure it !!!

so any updates!

**Comment by dmaass01** [comment]
I do have the same issue; cannot run the authentication when supabase is running locally (while it works without issues in production). The is the error message:

Refused to connect to 'http://127.0.0.1:54321/auth/v1/token?grant_type=password' because it violates the following Content Security Policy directive: "connect-src 'self' https://*.supabase.co https://*.linkedin.com https://linkedin.com https://*.licdn.com https://api.linkedin.com https://accounts.google.com wss://*.supabase.co chrome-extension: http://localhost:* ws:".

Fetch API cannot load http://127.0.0.1:54321/auth/v1/token?grant_type=password. Refused to connect because it violates the document's Content Security Policy.

config.toml is configured correctly in terms of url / ports

There just seems no way to adjust the Content Security Policy to include 127.0.0.1:54321

**Comment by ChuckJonas** [comment]
Anyone have any updates on this?  Or a workaround?  I've developed locally in the past, but just recently started running into this issue.
