### ISSUE TITLE
Storage Invalid S3 Access Keys Generated Supabase.com

### ISSUE THREAD

**Issue by j-mendez** [supabase/supabase#28039]
# Bug report

When created a S3 access key and trying to migrate data over to a Cloudflare R2 the migration fails with. It looks like Supabase Storage on the hosted website supabase.com is generating invalid access keys that do not work. 

![access key issue cloudflare](https://github.com/user-attachments/assets/3456d425-eafa-46d8-9fb8-4c342b333d88)

**Comment by encima** [comment]
hey @j-mendez 

Can you please provide more details and steps to reproduce.

How are you migrating over to R2? What URL are you providing and/or region?

If it is easier, please follow the issue template

**Comment by j-mendez** [comment]
> hey @j-mendez
> 
> Can you please provide more details and steps to reproduce.
> 
> How are you migrating over to R2? What URL are you providing and/or region?
> 
> If it is easier, please follow the issue template

Hi, I am trying to migrate using the GUI. You put the following in the screenshot. I am putting the bucket name that I have on supabase storage and the keys generated from the S3 access key section. You do not provide a URL or region. If you try to do any simple migration it will fail even on new accounts to R2.

![R2 migration screenshot with S3 fields on access key, secret key and storage bucket](https://github.com/user-attachments/assets/9dfe1442-cbc5-497f-a23b-2e542b284176)

**Comment by encima** [comment]
Hi @j-mendez 

That is expected, because you are specifying `Amazon S3`, without an s3 compatible endpoint then R2 will only try to authenticate with AWS S3 buckets. R2 only [supports](https://developers.cloudflare.com/r2/data-migration/super-slurper/) migration from AWS S3 and Google Cloud Storage.

I am afraid you need to open this as a feature request with them or use other tools, such as:
- [rclone](https://rclone.org/)
- [AWS CLI](https://aws.amazon.com/cli/)
- [Filezilla](https://filezilla-project.org/)

**Comment by smaldd14** [comment]
For those running into a similar issue migrating supabase storage to R2, [this link](https://github.com/orgs/supabase/discussions/26806#discussioncomment-10434221) describes a situation I ran into

Basically, you can use rclone to migrate, but you need to be on version 1.67.0 of rclone because it looks like supabase is still using aws sdk v1.
