### ISSUE TITLE
Generate types using Swagger OpenAPI specification fails

### ISSUE THREAD

**Issue by tmm** [supabase/supabase#281]
# Improve documentation

## Link 

[Generating Types > Generate database types from Swagger OpenAPI specification](https://supabase.io/docs/client/generating-types/#generate-database-types-from-swagger-openapi-specification)

## Describe the problem

Following documentation to generate types and receiving an error that `'definitions' are missing from schema`:

```
> npx @manifoldco/swagger-to-ts https://project.supabase.co/rest/v1/?apikey=anon-key --output types/supabase.ts
npx: installed 73 in 3.632s
✨ swagger-to-ts 2.0
This library has been updated to 2.0 with improved generation. If you experience issues you can use the deprecated v1 with `npx @manifoldco/swagger-to-ts@1 …`
🤞 Loading spec from https://project.supabase.co/rest/v1/?apikey=anon-key…
Error: ⛔️ 'definitions' missing from schema https://swagger.io/specification/v2/#definitions-object
    at generateTypesV2 (/Users/tom/.npm/_npx/70318/lib/node_modules/@manifoldco/swagger-to-ts/dist-node/index.js:189:11)
    at swaggerToTS (/Users/tom/.npm/_npx/70318/lib/node_modules/@manifoldco/swagger-to-ts/dist-node/index.js:370:32)
    at /Users/tom/.npm/_npx/70318/lib/node_modules/@manifoldco/swagger-to-ts/bin/cli.js:49:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I checked that `project` and `anon-key` are correct. The types I am specifically trying to generate are for auth `User` and `Session`.

## Describe the improvement

n/a

## Additional context

n/a

**Comment by kiwicopple** [comment]
Hey @tmm - as a first step, when you go to `https://project.supabase.co/rest/v1/?apikey=anon-key` on your browser, is it successfully pulling up the swagger/JSON for your project?

**Comment by carllippert** [comment]
Hey @kiwicopple I'm seeing this as well now. 

Been using doc recommended procedure wonderfully for weeks including yesterday evening: i.e. 
npx openapi-typescript https://<my project>.supabase.co/rest/v1/?apikey=<key> --output types/supabase.ts"

Went to link, types are being properly generated. 

Only thing I did was create a new table "user_settings".
Decided there could be some constraints somewhere on the "user" name in table names so dropped that no fix. 
Also turned RLS on and off for said table. 
Tried adding a row to previous working table. Showed up in website but no longer making it to client via npx openapi-typescript. 

No updates seem to have been deployed to openapi-typescript. 
Error message seems false since swagger version exist in generated document
![image](https://user-images.githubusercontent.com/16457876/134089566-c45cb65b-51a1-4d17-affc-217bf7fc1e70.png)

Any help appreciated. 

error: 
`yarn update-types
yarn run v1.22.11
$ npx openapi-typescript https://mflpglabgygmyocbzjrm.supabase.co/rest/v1/?apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyODU1MTc5MywiZXhwIjoxOTQ0MTI3NzkzfQ.-UFKIYvy_zkN10rZzaV_OqgEbAfUBbSwALNavZqKP34 --output types/supabase.ts
npx: installed 81 in 3.96s
✨ openapi-typescript 4.0.2
🔭 Loading spec from https://mflpglabgygmyocbzjrm.supabase.co/rest/v1/?apikey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyODU1MTc5MywiZXhwIjoxOTQ0MTI3NzkzfQ.-UFKIYvy_zkN10rZzaV_OqgEbAfUBbSwALNavZqKP34…
Error: 🚏 version missing from schema; specify whether this is OpenAPI v3 or v2 https://swagger.io/specification
    at Object.swaggerVersion (/Users/ccaarrll/.npm/_npx/44572/lib/node_modules/openapi-typescript/dist/cjs/utils.js:70:11)
    at openapiTS (/Users/ccaarrll/.npm/_npx/44572/lib/node_modules/openapi-typescript/dist/cjs/index.js:89:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async generateSchema (/Users/ccaarrll/.npm/_npx/44572/lib/node_modules/openapi-typescript/bin/cli.js:73:18)
    at async main (/Users/ccaarrll/.npm/_npx/44572/lib/node_modules/openapi-typescript/bin/cli.js:123:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by carllippert** [comment]
Just wanted to add that I'm up and running today without any known solve. it works again. Did upgrade macOS version. Perhaps just a case of ghosts in the wires. Carry on. 🚀

**Comment by captDaylight** [comment]
I'm seeing the same error `version missing from schema; specify whether this is OpenAPI v3 or v2 https://swagger.io/specification`

When I run my url in the browser I'm seeing `{"swagger":"2.0", ....` so I'll cross my fingers that @carllippert 's ghosts will help me too...

**Comment by sasweb** [comment]
Just a short hint for others who may stumble upon this thread: for me it helped to put my api key in quotes like `npx openapi-typescript https://project.supabase.co/rest/v1/?apikey="yourapikeygoeshere" --output types/supabase.ts`.

No ghosts :)

**Comment by tomsoderlund** [comment]
With `openapi-typescript` v6.0.0, they broke support for Swagger 2.0 (“Swagger 2.0 and older no longer supported. Please use v5.”). Use `npx openapi-typescript@5.4.0` to work with Supabase’s API.

Here’s my `yarn api` command I use for fetching the latest types (in `package.json`):

    "scripts": {
      "api": "eval $(grep '^SUPABASE_URL' .env.local) && eval $(grep '^SUPABASE_API_KEY' .env.local) && npx openapi-typescript@5.4.0 ${SUPABASE_URL}/rest/v1/?apikey=${SUPABASE_API_KEY} --output types/supabase.ts"
      // and then lots of other scripts
    }

**Comment by TomasHubelbauer** [comment]
For anyone wondering how to hit this locally, just access http://localhost:54321/rest/v1/ without passing `?apikey` (that will give you an error even if you pass the one from `supabase status`).
