### ISSUE TITLE
unable to see edge functions in local development studio + when doing supabase login it only goes to supabase url and not to self hosted version

### ISSUE THREAD

**Issue by SerjoA** [supabase/supabase#28934]
i dont know if both of the above are bugs or issues but i cant find anything in the docs.
how do i login to my self hosted version?
how to see edge functions in local superbase studio or in self hosted studio ?

**Comment by encima** [comment]
Hi there,

Thanks for reporting!

To confirm, the studio shows the SQL editor but functions are deployed via the CLI locally. The documentation is [here](https://supabase.com/docs/guides/functions/quickstart), have you checked that?

What are you expecting to see in the studio? It could be that your analytics are not enabled and that would need to be turned on to see logs from the edge functions?

**Comment by SerjoA** [comment]
i have 2 setup's on my local machine - one local studio one self hosted.
both dont show the functions in the ui only when i deploy to supabase live i see it in the live dashboard

**Comment by RoPB** [comment]
Was this solved? Thanks

**Comment by Abhishekpatel123** [comment]
I’m facing the same issue.

In the local and self-hosted Supabase setup, I’m unable to see the Edge Functions. Do I need to enable something for this?

Additionally, I’d like to know how we can login and link a self-hosted Supabase instance with the local Supabase setup, especially since we don’t have a project ref.

Does anyone have any insights on this?

**Comment by lockykeaney-convincely** [comment]
I have a similar issue where I can't access any of the settings for Authentication. Like the local dashboard has stripped back features

**Comment by Christophershivers** [comment]
> I have a similar issue where I can't access any of the settings for Authentication. Like the local dashboard has stripped back features

I'm also having the same problem

**Comment by rodneybetts** [comment]
> I have a similar issue where I can't access any of the settings for Authentication. Like the local dashboard has stripped back features

Same here

**Comment by Christophershivers** [comment]
> > I have a similar issue where I can't access any of the settings for Authentication. Like the local dashboard has stripped back features
> 
> Same here

Actually I figured it out. For some odd reason, on the self-hosted version of supabase, you don't have access to Oauth options on the dashboards. You have to set that information in the docker-compose.yml file. I got google auth working like that. you can create a docker-compose.override.yml file to add the other Oauth providers, instead of directly messing with the docker-compose file.

**Comment by eLBirador** [comment]
same issue here

**Comment by stefanorumi7** [comment]
Same issue here in local development

**Comment by alohamonius** [comment]
same issue here

**Comment by MattFaz** [comment]
+1 cant see any edge functions despite me having 4, that are working...

**Comment by kmadhu0** [comment]
+1 to this issue. Local Supabase dashboard shows nothing even though I have 2 functions served using Supabase CLI

**Comment by nik** [comment]
+1 here...

**Comment by Moto42** [comment]
Same Issue

**Comment by LucaL1fe** [comment]
+1

**Comment by tomledude** [comment]
+1 supabase edge functions work locally but they are not visible in the UI

**Comment by aantti** [comment]
Soon 🖖

**Comment by Moto42** [comment]
Thank you aantti.
