### ISSUE TITLE
SupaSocialsAuth Google OAuth Safari error (Flutter)

### ISSUE THREAD

**Issue by bugvad** [supabase/supabase#29056]
# Bug report

- [ v] I confirm this is a bug with Supabase, not with my own application. 
- [ v] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

SupaSocialsAuth button click leads to "Safari cannot open the page because the address is invalid" on second and all next attempts. 

```
            SupaSocialsAuth(
              socialProviders: [
                OAuthProvider.google,
              ],
              colored: true,
              redirectUrl: kIsWeb
                ? null
                : 'com.example.myappname://callback',
              onSuccess: (Session response) {
                Navigator.pushReplacementNamed(context, '/bottomNavScreen');
              },
              onError: (error) {},
            ),
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Launch iOS Simulator
2. Try to click Continue with Google
3. Get error message from Safari

## Expected behavior

Succesful authorisation

## System information

- OS: macOS

**Comment by monicakh** [comment]
The iOS app uses Safari (or an in-app browser) to authenticate because Google OAuth. After you complete the authentication, it should return to the app using the callback URL, but if this isn’t set up properly Safari doesn’t know how to handle it leading to the error you're seeing. 

You should check the Xcode project configuration

![image](https://github.com/user-attachments/assets/23a501e8-e73d-4b7d-8236-4eac9e866b28)

and make sure the custom URL scheme that you use is [registered](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app#Register-your-URL-scheme) under the URL Types section.

Also, if Safari is restricted or disabled on your device, the OAuth flow cannot proceed. To check this, follow these steps:

- Go to iPhone Settings > General > Restrictions.
- Find Safari and make sure it is allowed or turned on (swipe to green).
- Exit settings and retry the authentication flow.

**Comment by bugvad** [comment]
@monicakh URL Scheme in Xcode is already set (

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by brian316** [comment]
This is still an issue. iphone simulator open safari browser to do sign in and get same error
