### ISSUE TITLE
Extensions not working when installed outside the 'extensions' schema. 

### ISSUE THREAD

**Issue by AmeanAsad** [supabase/supabase#29988]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When installing the `pgvector` extension from the supabase dashboard, you get to choose which schema you want it installed in. If it is installed on a schema that is  *not* the `extensions` schema, it simply fails to register.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

#### Install pgvector
1. Go to 'Database'
2. Click on 'Extensions'
3. Scroll down to 'vector'
4. Install under a new schema called `vector_db`

#### Create a table
1. go to 'SQL Editor'
2. try and run the following code

```
create table vector_db.test_rag (
    id text primary key,
    vec vector(512) not null,
    metadata jsonb not null default '{}'::jsonb,
);
```

An error should pop up claiming that type `vector` does not exist. 

## Expected behavior

- if there is a choice to select which schema an extension should be installed in, then it is expected for the extension to work in that specified schema.
- if there are extensions that have to be installed in certain default supabase schemas (such as the `extensions` schema, then that should be highlighted in docs, or the UI should block the user from installing it in other schemas. 

## Screenshots

Enable the extension under a new schema
<img width="495" alt="Screenshot 2024-10-18 at 2 04 47 PM" src="https://github.com/user-attachments/assets/6338da3f-a4bb-4905-97ee-b2a990586113">

try and create the table and get the error
<img width="944" alt="Screenshot 2024-10-18 at 2 05 30 PM" src="https://github.com/user-attachments/assets/3c9cf570-722a-421a-b301-d86754ae2148">

## System information

- OS: macOS
- Browser: firefox 132

**Comment by Hallidayo** [comment]
Hi @AmeanAsad - I also seem to be getting the same experience as you. I've just reached out to the team to see if some extensions have to be installed in the `extensions` schema in order to work. I'll update you with what I find out!

**Comment by Hallidayo** [comment]
Hi @AmeanAsad - I've spoken with the team and you'll need to add your newly created schema or schema that you have created to your search_path. So for example if you had an schema named `vector` you would need to do the following:

`alter role postgres set search_path = vector, public, extensions;`

Replace vector with your schema.

But be aware that your search path is PER ROLE, and your API uses a different role than Supabase Studio (anon or authenticated rather than postgres) the best way to resolve that is to go to your [API settings](
https://supabase.com/dashboard/project/_/settings/api) and add your new schema name to your Extra search path as needed.

Let me know how you get on 👍

**Comment by Hallidayo** [comment]
Hi @AmeanAsad , We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
