### ISSUE TITLE
3rd Party OAuth redirectTo doesn't respect Additional Redirect URLs

### ISSUE THREAD

**Issue by cbzehner** [supabase/supabase#3069]
# Bug report

## Describe the bug

When using the `auth.signIn` API with a 3rd party provider (Google, Facebook, etc.) the `redirectTo` parameter isn't respected if it doesn't match the value set in the Supabase dashboard for "Site URL".

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone https://github.com/cbzehner/supabase-additional-redirect-urls-repro (NextJS + Supabase minimal case)
1. Set up a new Supabase project with _any_ value for "Site URL" under Auth Settings and `http://localhost:3000` under the "Additional Redirect URLs"
1. Follow the steps to set up a Facebook App (https://supabase.io/docs/guides/auth/auth-facebook)
1. Set the following values in a `.env` file. `NEXT_PUBLIC_SUPABASE_URL` (project url) & `NEXT_PUBLIC_SUPABASE_KEY` (anon key)
1. Install dependencies with `npm install`
1. Run project with `npm run dev` & navigate to localhost:3000

## Expected behavior

When clicking the button in the Reproduction example, you should be redirected to `http://localhost:3000/api/auth/facebook/callback` and see a 404 page. (This endpoint doesn't exist in the example)

Instead you're directed to the value set in "Site URL", ignoring the `redirectTo` value from the source code.

## Screenshots

N/A

## System information

- OS: macOS
- Browser (if applies) Firefox
- Version of supabase-js: ^1.22.4
- Version of Node.js: v16.4.0

## Additional context

Please let me know what other information I can provide. This came up originally in a [Discord thread](https://discord.com/channels/839993398554656828/843999948717555735/883416157544149012)

**Comment by ankitjena** [comment]
Can anyone point me to where can I look into, to work on this. This is a needed fix for me to continue local development. Thanks

**Comment by awalias** [comment]
hey @cbzehner the Additional Redirect URLs need to be _exact_ matches including scheme, host, path, and query params, is the redirectTo string and the string in Additional Redirect Urls exactly the same?

for context - this is a security requirements since this field was initially introduced for the purpose of mobile deep links (which don't necessarily conform to the `scheme://host/path?query` format

@ankitjena the backend code for this is here: https://github.com/supabase/gotrue/blob/46df5fd65c6692635c672ce7c6811c069e6aa231/api/helpers.go#L126

**Comment by kiwicopple** [comment]
Looks like this could be an issue with spaces between the "redirect" links:
https://github.com/supabase/supabase/issues/3191#issuecomment-1002087764

I'll close this in favour of that one
