### ISSUE TITLE
Dashboard should trim spaces between "redirect" links

### ISSUE THREAD

**Issue by richiemcilroy** [supabase/supabase#3191]
# Bug report
redirectTo parameter doesn't seem to work for redirects.

## Describe the bug
The redirectTo parameter doesn't seem to work for redirects when using supabase.auth.signIn or supabase.auth.signUp (@supabase/supabase-js), and I can't find any reference to it, apart from in the docs on the website: https://supabase.io/docs/reference/javascript/auth-signin

## To Reproduce

 Using supabase.auth.signIn or supabase.auth.signUp with the redirectTo parameter (@supabase/supabase-js), as referenced in the docs URL above.

## Expected behavior

As per the docs, it should redirect you to a URL (if the base domain is the same as in auth settings)

## System information

- OS: macOS
- Browser: Chrome
- @supabase/supabase-js: 1.3.2

**Comment by Facundojs** [comment]
Hey could yoy fix this? Im now with same problem

**Comment by chipilov** [comment]
I see the same issue - the redirectTo param is NOT respected regardless of what I have in the "Site URL" or "Additional Redirect URLs" in the dashboard.

@awalias @kiwicopple It seems that the redirectTo param is only appended as a query param to the GoTrue auth requests, but the GoTrue implementation does NOT use this param at all. If you need help with fixing this, can you give us some pointers about how to go about fixing it (e.g. what is the expected flow)?

**Comment by awalias** [comment]
hey guys thanks for the report!

can you share what values you have in the "Site URL" and "Additional Redirect URLs" in the dashboard, and which url you're using in the client

**Comment by chipilov** [comment]
Sure, I am trying to redirect to '/profile' when the user logs in. I tried the following:

1)
redirectTo: '/profile'
Site URL: 'http://localhost:3000'
Additional Redirect URLs: 'https://localhost:3000'

2)
redirectTo: '/profile'
Site URL: 'http://localhost:3000'
Additional Redirect URLs: 'https://localhost:3000/profile'

3)
redirectTo: 'http://localhost:3000/profile'
Site URL: 'http://localhost:3000'
Additional Redirect URLs: 'https://localhost:3000/profile'

Do you think it's a config issue?

Even if it is, I am a bit puzzled because as @richiemcilroy mentioned, I don't see any uses of the redirect_to query param in the GoTrue server and in the JS clients, it seems like the redirectTo param is only used to populate the redirect_to query param.

**Comment by pmauchle** [comment]
This is my config which works:
![image](https://user-images.githubusercontent.com/3627771/135586370-df288a09-d808-447f-869d-3b2bc2fe3e71.png)

You have to provide the full path in `redirectTo`. I set the redirectTo with .env variables so it works both locally and live.

**Comment by chipilov** [comment]
Hi @pmauchle,

I did try to provide the full path in the redirectTo param (as specified in the third example above). The string I pass to the redirectTo parameter is "

Here is what I have in the dashboard:

![urls](https://user-images.githubusercontent.com/389130/135620524-a5c3d3b1-174b-4733-b672-255775ae49a8.png)

It's possible that I am doing something wrong but I am not sure where to look because I don't see any places in the code where ther redirect is actually used. I see that the redirectTo is used to add the redirect_to query param i the request to the GoTrue server:

https://github.com/supabase/gotrue-js/blob/4d57cb5db2c833bb08dcb72e1ce025615624efdd/src/GoTrueApi.ts#L89

But I don't see this query param used by the GoTrue server in the Token API:

https://github.com/supabase/gotrue/blob/70ffa779d7f1a58e5463a513289597f3abc9d8e6/api/token.go#L52

Am I missing something?

**Comment by pmauchle** [comment]
Hey @chipilov I also use v1.22.6 and it works with your site URL and additional URLs in my project, I just tested.

Can you share the part where you do the redirect in your code?

**Comment by chipilov** [comment]
I am literally using the Basic Auth example from supabase/ui: (https://ui.supabase.io/components/auth) and only passing the redirectTo prop to the Auth component, so it looks like this:

`const Container = (props: any) => {
  const { user } = Auth.useUser()
  if (user)
    return (
      <>
        <Typography.Text>Signed in: {user.email}</Typography.Text>
        <Button block onClick={() => props.supabaseClient.auth.signOut()}>
          Sign out
        </Button>
      </>
    )
  return props.children
}

function App() {
  return (
    <Auth.UserContextProvider supabaseClient={supabase}>
      <Container supabaseClient={supabase}>
        <Auth supabaseClient={supabase} redirectTo='http://localhost:3000/profile' />
      </Container>
    </Auth.UserContextProvider>
  )
}

export default App;`

In the network tab of the dev tools I see that the redirect_to query param is properly added but as soon as I sign in sucessfully, the page remains on the root path (i.e. it is NOT redirected to /profile).

Maybe I misunderstand the meaning of what is expected to happen and I need to do something additional? I know I can use ReactRouter to redirect on sucessful sign-in, but I don't understand the point of the redirectTo parameter.

**Comment by mvxt** [comment]
`redirectTo` is similarly not working for me. Using @supabase/supabase-js v1.25.2. I've made sure my Auth settings in Supabase and the URL I'm passing to `redirectTo` match:

![image](https://user-images.githubusercontent.com/2441695/140478225-21f83299-d315-4cfd-be81-c9b1d481288c.png)

In the code, I'm doing a direct call like so:
```javascript
    const { error } = await supabase.auth.signIn({
      email: info.email,
      password: info.password
    }, {
      redirectTo: 'http://localhost:3000/settings
    });
```

In the networking tab, I've confirmed that the library is passing the redirect URL correctly as a parameter to Supabase API. It makes the call twice, first with `OPTIONS` and then a `POST`.

<img width="718" alt="Screen Shot 2021-11-05 at 2 09 00 AM" src="https://user-images.githubusercontent.com/2441695/140479129-de61c5e2-ed82-405c-b348-2b3ebc9887e7.png">
<img width="716" alt="Screen Shot 2021-11-05 at 2 10 14 AM" src="https://user-images.githubusercontent.com/2441695/140479131-87ca753d-07b5-4f07-ab4a-3d09d869110a.png">

Am I missing something obvious here? This is getting frustrating.

**Comment by leggetter** [comment]
@mvxt are you using the latest version of the SDK?

See my update note here https://github.com/supabase/supabase/issues/3191#issuecomment-941153733

**Comment by mvxt** [comment]
@leggetter Yes, as mentioned I am using v1.25.2

**Comment by leggetter** [comment]
@mvxt how about specifically trying v1.24.0 as that did work for me?

**Comment by 10000multiplier** [comment]
Also experiencing this, setting the `redirectTo` param is not respected.

**Comment by riderx** [comment]
Same here, it's sometime respected, but seems not reliable, and fun fac if you copy the link in email and add the right URL to the link before load it, it work.
I will try to pseudo fix the issue by editing the email template

**Comment by varna** [comment]
Seems like the same issue as #2623 #3069 #4540

Only the first argument of **Additional Redirect URLs** is used while validating redirectURL.

If `redirectURL` is set to `http://localhost:3000`

This fails:
<img width="700" alt="This fails" src="https://user-images.githubusercontent.com/6717694/147564052-b6a3ff6e-3497-48ad-a5df-46b29e319ac2.png">

This works:
<img width="704" alt="This works" src="https://user-images.githubusercontent.com/6717694/147564097-21996e6a-28bd-4089-9db9-0b3c9f997b91.png">

I'm not sure how to run the tests... https://github.com/supabase/gotrue/pull/316 should fail

**Comment by bnjmnt4n** [comment]
There's a space after the comma which isn't recognized. Perhaps try removing the space? Maybe this should be changed on the studio frontend to flag this out as a common error, or GoTrue can be modified as well to trim leading/trailing whitespace.

**Comment by varna** [comment]
> There's a space after the comma which isn't recognized. Perhaps try removing the space? Maybe this should be changed on the studio frontend to flag this out as a common error, or GoTrue can be modified as well to trim leading/trailing whitespace.

This worked :D Thanks!

Input validator sounds nice.

**Comment by kiwicopple** [comment]
I've renamed this one based on @bnjmnt4n 's [comment](https://github.com/supabase/supabase/issues/3191#issuecomment-1002087764). We can fix this on the frontend, but afterwards we should also fix GoTrue to be consistent.

I think @MildTomato may want to change the format from a Comma list? Perhaps we can use a safer component here?

**Comment by varna** [comment]
I suggest Combobox with multiple items:
![image](https://user-images.githubusercontent.com/6717694/147581430-bcde7c33-3781-4dd4-a10b-1ae5e1dbf542.png)

**Comment by iamclaytonray** [comment]
It's now Feb 2022 and this is still broken. 2 months have passed without any movement on this very critical bug. And it's not documented, which means I pushed what I thought was a stable API to production. While I love GraphQL, why is that prioritized over simple things like this? Lack of communication here isn't breeding confidence.

**Comment by iamclaytonray** [comment]
@MildTomato - appreciate the response.

I was just reading through this [issue](https://github.com/facebook/flow/issues/7365) and my main takeaway was that the Flow maintainers kind of just dropped off the planet and didn't communicate that well. Obviously it's a different comparison (this is clearly an active business, etc) but I think the core pain point remains; if there are issues, transparency and communication often solves it.

I was unaware of the understaffed issue and I would assume most others are under the impression you have a full team as well. Being transparent about this doesn't hurt your credibility; it **_solidifies_** it. Openly communicating these problems welcomes the community to help as opposed to potential contributors thinking that you have plenty of people but just neglecting to work on certain issues.

---

More related on this specific issue; I think trimming will fix the OP issue but I don't see a reason it would fix the intermediate issue. Sometimes the proper `redirectTo` is used. Sometimes it isn't. All while no settings have been changed. Because this is such a major issue (again, users cannot login to my apps), I'll do my best to take a look around the code and hopefully come up with a solution.
