### ISSUE TITLE
Not working with React

### ISSUE THREAD

**Issue by Justiniscoding** [supabase/supabase#3460]
## Describe the bug
Supabase is not working with react.
The bug doesnt let me verify people with magic link. I am trying to use the example from https://supabase.io/docs/guides/with-react. When I run this and click send magic link, in the console it says
```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at parse (<anonymous>)
```
## To Reproduce
Copy the code from https://supabase.io/docs/guides/with-react
Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run the program with `npm start`
2. Open localhost:3000 in your browser
3. FIll in your email and click send magic link

## Expected behavior

It should send an email to the email stated with a magic link, to sign up.

## System information

- OS: MacOS El Capitan
- Browser Brave, Chrome and Safari
- Version of supabase-js: 1.24.0
- Version of Node.js: 14.15.4

**Comment by rodolphoasb** [comment]
Hey, @Justiniscoding! How are you doing?

I've just tested it out and seems to work fine for me (prints below).

![image](https://user-images.githubusercontent.com/8127858/136642781-8929f6f4-e648-43fa-9f42-74ca5cc3fd3e.png)

![image](https://user-images.githubusercontent.com/8127858/136642795-90b2248d-d065-42ca-ba2c-984cc7253925.png)

This 404 error is because your code could not find any route (endpoint) that matches what you are requesting.

So I would start checking if you have the .env file in the root directory and if the link matches the link inside Settings > API > Config URL.

My structure is the following (with URL and ANON_KEY modified for security reasons):

![image](https://user-images.githubusercontent.com/8127858/136642970-18bb2136-d88f-48c4-9f6b-d2bb949686c1.png)

Hope it helps!

**Comment by Justiniscoding** [comment]
Thanks @rodolphoasb turns out I didn’t use the right supabase url. The example works fine now
