### ISSUE TITLE
Creation of FK at table creation is not intuitive

### ISSUE THREAD

**Issue by activenode** [supabase/supabase#3471]
# Feature request

When you ALREADY have an existing table THEN it is possible to click on "Add new Column" and see the following screen:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/9058762/136689631-636bf01c-9da3-4d97-9f68-fe0b4eb3c3a0.png">

In this screen you can click on "Add Foreign Key Relation" to connect to another table. That is fine.

**BUT**: If you simply click on  "+ new table" then you see the following screen:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/9058762/136689662-4aa7af3c-164a-4cf4-8ef7-6503b7c97b31.png">
In this screen you cannot add any foreign key relation to any other table.

## Describe the solution you'd like

Click on the "config" button next to the column and be able to see the same screen as described initially to add a foreign key relation.

**Comment by kiwicopple** [comment]
good one @activenode 👍

**Comment by activenode** [comment]
I noticed  you CAN add a FK here. But it is not intuitive. It's the Link Icon.

**Comment by kiwicopple** [comment]
Oh true ... even I missed it. Agreed it's not intuitive. I'll let the team know

**Comment by MildTomato** [comment]
Think we can improve this. One of us should take a look.

**Comment by saltcod** [comment]
This interface has changed in the time since the last comment here. It now separates the link icon button, which helps a bit. 

<img width="360" alt="CleanShot 2022-09-02 at 13 06 39@2x" src="https://user-images.githubusercontent.com/105593/188186599-b5e5627c-8a32-4fc8-9f2c-fc2a37cb863c.png">


Would a key icon instead of a link icon help at all as a quick win? 
<img width="376" alt="CleanShot 2022-09-02 at 13 06 49@2x" src="https://user-images.githubusercontent.com/105593/188187041-935e3647-eb37-47dc-b208-88da274bcfff.png">

**Comment by activenode** [comment]
The separation is a good step already. I'm unsure about link vs key icon. Could you imagine something with a pointer/arrow somehow indicating it's pointing to somewhere? like an arrow that's pointing to a reference?

**Comment by kiwicopple** [comment]
> I'm unsure about link vs key icon.

Looks like it's been changed back to the link now (which I think is sensible). Let's close this for now - I'm sure we'll do a larger redo of the UI at some point, and we can consider an alternative approach then

Thanks again for this one @activenode  👍

**Comment by activenode** [comment]
Awesome, seen that, works well.
