### ISSUE TITLE
Dark / light theme switch on navbar

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#3643]
# Feature request

Add a dark / light theme switch to the navbar.

## Additional context

I noticed that there is a dark / light theme switch at the footer of the landing page, and I thought it would be better to add it to the navbar. For example just like the one on the docs page. What are your thoughts? I would love to know what you think about this feature request.
<img width="1280" alt="Screen Shot 2021-10-28 at 10 19 17 PM" src="https://user-images.githubusercontent.com/70828596/139362938-8f5179f3-ddf8-4053-88ad-bc3fcb2af82e.png">

**Comment by yeganathan18** [comment]
@Isaiah-Hamilton Great will fix and send a pull request.

**Comment by Isaiah-Hamilton** [comment]
@yeganathan18 any updates?

**Comment by MildTomato** [comment]
I'm not sure this is such a big issue - the only reason the toggle is there is because it's a docusarus default.

We are planning on using nextjs multizone to have all our apps deployed on the same domain, so they can share some of the same logic and i guess we can have these common settings like theme stored in cookies/localstorage.

From the supabase team perspective, we'd probably rather have theme picker not taking up navbar space on any of the nextjs apps. I quite like how Vercel do it, they keep it on the footer, and the option is also available through a user settings dropdown.

**Comment by MildTomato** [comment]
I see everyones point though. I'll keep the issue open for now 👍

**Comment by yeganathan18** [comment]
> @yeganathan18 any updates?

@Isaiah-Hamilton Currently having some issues with local development. After setting up the local development I started working on the issue but the result is not showing up in the localhost ☹️

I have mentioned the same in the [discussions](https://github.com/supabase/supabase/discussions/3719#discussioncomment-1570328), it would be great if you could help me to figure out what I'm doing wrong.

**Comment by yeganathan18** [comment]
If we just add a dark mode toggle on the navbar, it seems to be inconsistent with the rest of the design, any opinions?

After adding it:
<img width="1792" alt="Screenshot 2021-11-10 at 11 35 11 PM" src="https://user-images.githubusercontent.com/63534555/141168919-fae8c127-dbee-4eef-b96d-232fdf677b97.png">

**Comment by Isaiah-Hamilton** [comment]
@yeganathan18 instead of the switch being on the right it should be on the left and have no icons. For example, place the switch where the red circle is, and remove the icon
<img width="1392" alt="Screen Shot 2021-11-10 at 4 06 17 PM" src="https://user-images.githubusercontent.com/70828596/141193671-144e797f-da61-4cf4-b473-4e4ba539b0e0.png">
s.

**Comment by Isaiah-Hamilton** [comment]
I'm closing this issue because adding the theme switcher would not look good with the current navbar UI.
