### ISSUE TITLE
Generic dashboard links

### ISSUE THREAD

**Issue by joshenlim** [supabase/supabase#4320]
# Feature request

From Ant:
```
When writing documentation or providing customer support it would be useful to give someone a link directly to a certain page on their dashboard, without knowing their project reference,

it would be useful to set up some endpoints e.g. https://app.supabase.io/project/[ref]/database/backups that forwards to that page for their default (or most recent?) project
```

From Thor:
```
This is what firebase does and I quite like it:

Link without the project ID e.g. https://app.supabase.io/project/auth/templates shows a list of your projects
When you click the project it then goes to the above link with your project ID filled in https://app.supabase.io/project/zdtdtxajzydjqzuktnqx/auth/templates
I think that should we quite doable, might look into this myself if that's okay?
```

**Comment by DukeManh** [comment]
Hey @joshenlim, I thought of the same thing using Supabase today. I'd like to help make this happen.

Do you have any suggestions for implementation?

**Comment by thorwebdev** [comment]
@DukeManh that would be sweet indeed, I've been wanting to do this for so long but still haven't 🙈  Let's tag team!

The is the experience I envision:
- Hink without the project ID e.g. https://app.supabase.io/project/auth/templates loads a list of your projects, here we can reuse the [tiles from the "All projects" home view](https://github.com/supabase/supabase/blob/master/studio/components/interfaces/Home/ProjectList/ProjectList.tsx) I'd say, but only show the active projects, not the paused ones.
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/5748289/154648569-e76e7e0d-d27b-462d-a115-724ea18daf03.png">

- When you select a project it then redirects you to the relevant route with your project ID filled in, e.g. https://app.supabase.io/project/zdtdtxajzydjqzuktnqx/auth/templates

Wdyt, is that enough context for you to get started?

**Comment by DukeManh** [comment]
Hey @thorwebdev, that sounds good to me. I'll take to a look to see if I can help. I think there's probably a reason why the team didn't do it. maybe it's hard :).. I'll start working on it and let you know.

**Comment by thorwebdev** [comment]
No actually it isn't that hard, it mainly comes down to prioritisation 🙈 😂 So we appreciate you taking a look 💚

**Comment by DukeManh** [comment]
Alright, btw is it possible to connect my local studio server to use the hosted Supabase vs my docker containers?

**Comment by thorwebdev** [comment]
@DukeManh terribly sorry, while researching whether we can run the dashboard on a hosted supabase DB (answer is no as you need to run [the DB migrations here](https://github.com/supabase/supabase/tree/master/docker)) I ended up just implementing it. But would appreciate your review and feedback on it!

**Comment by DukeManh** [comment]
@thorwebdev, oh that's why we can't. I was trying hard to make my local studio work with the hosted supabase DB, without success

**Comment by MildTomato** [comment]
> This is what firebase does and I quite like it:

I can't get firebase to do this btw, if I use a URL without the correct project slug it just shows a permission error.

——

This is a really interesting issue since we want to support URLs that are more friendly for docs/support across all URLs. 
but we also need to improve how you know what org/project you are in, and it should be more obvious and easier to switch org/project. something me and @joshenlim have been talking about. So in other words, whatever we do today is a stepping stone solution for now, and we should really think about the layout/hierachy of the app in the long term as it's not efficient.

saying that let's make this better In the meantime :-) 💯 

I would have thought saving the 'active project' in local storage would have been sufficient, and then if a URL has no project ref, we could simply reroute it to the last known project ref in local storage. 

If the user doesn't have permission for that, then we reroute them back to `/` 

I'm not that keen on hacking our homepage as a generic link index (#5568), but, if that was the chosen solution, then we should probably implement it properly so the nav/sidebar is not being shown. A bit more like the actual firebase project index page.

**Comment by joshenlim** [comment]
okay managed to dig through firebase to get some prior art

this is how firebase does their generic links
`https://console.firebase.google.com/u/1/project/_/firestore`

it'll bring you to a page that lists all projects and prompt the user to choose which project to continue

clicking on the project card leads to the project with that url
e.g `https://console.firebase.google.com/u/1/project/{projectRef}/firestore`

we could go with a similar strategy here - i'll relook at the PR accordingly
