### ISSUE TITLE
Was able to create a folder with empty name

### ISSUE THREAD

**Issue by oliviercperrier** [supabase/supabase#4633]
# Bug report

When i was testing the api, i was able to upload an empty file to a folder without giving it any name.

When i logged in to the dashboard, i could se the folder without any name and tried to delete it, but wasnt not able to.

Trying delete the parent folder of this folder was not working too.

## To Reproduce

Using the api

1. Create a bucket named `avatars` for example
2. Create a folder in this bucket named `test` for example
3. Run the following code:
`const { data, error } = await supabase
  .storage
  .from('avatars')
  .upload('test//avatar.png', new File([], 'avatar.png');`

## Expected behavior

Name should be required

**Comment by i-pip** [comment]
this also happens if the upload path starts with a `/` (slash) because it gets appended to the ["finalPath" which already ends in a `/`](https://github.com/supabase/storage-js/blob/b9e407c911d28081b631736c57a8da6ce0f34b1f/src/lib/StorageFileApi.ts#L332) resulting in another empty folder like so `//` 

I've created a PR for this @phamhieu  @thebengeu

**Comment by jtkeyva** [comment]
Yep, I forgot to add folder name and it created an empty folder that I cannot delete or rename

**Comment by Isaiah-Hamilton** [comment]
Fixed with https://github.com/supabase-community/storage-go/pull/2
