### ISSUE TITLE
Supabase javascript SDK signup and login functionality does not work on Windows 11

### ISSUE THREAD

**Issue by JCaraballo113** [supabase/supabase#4752]
# Bug report

## Describe the bug

The issue is that the methods `signUp` and `signIn` do not work on Windows (11). Instead you get a 404 not found error for the POST routes.

## To Reproduce

1. Clone this [repo](https://github.com/JCaraballo113/vue-music)
2. Fire up a supabase project and make sure to set your callback URL to be `http://localhost:8080` as the default is `http://localhost:3000`
3. Add the following as an `.env` file:

```js
VUE_APP_SUPABASE_URL = "URL HERE";
VUE_APP_SUPABASE_ANON_KEY = "KEY HERE"
````

4. yarn install or npm install
5. npm run serve
6. Navigate to `http://localhost:8080` Try to sign up

## Expected behavior

`signUp` and `signIn` should work on Windows. I tested on macOS and it works fine!

## Screenshots

![Screenshot 2021-12-31 174558](https://user-images.githubusercontent.com/6374766/147840523-705bebe8-92e5-4620-972e-17dea9927a4c.jpg)

## System information

- OS: Windows 11
- Browser: Edge, also tested on Chrome
- Version of supabase-js: 1.29.1
- Version of Node.js: 16.3.1

**Comment by prescience-data** [comment]
Have you set your callback url in the Supabase admin panel to `https://localhost:8080` ?

**Comment by JCaraballo113** [comment]
@prescience-data  yes I have

**Comment by JCaraballo113** [comment]
Simply redownloading the whole repo fixed it

**Comment by bnjmnt4n** [comment]
The `unexpected token < in JSON at position 0` bug seems to be [pretty common](https://github.com/search?q=unexpected+token+%3C+in+JSON+at+position+0+user%3Asupabase&type=Issues&ref=advsearch&l=&l=). It seems like it's likely due to a problem with the Supabase instance, leading to Cloudflare sending back a HTML response page describing the error instead of the expected JSON response. It might be good to note that somewhere, and recommend a solution once the underlying cause is found (if there is one). Otherwise, if it is just due to unexpected server errors, recommending a restart of the instance might also be a good idea.
