### ISSUE TITLE
Please add new pricing tiers between FREE to 25$

### ISSUE THREAD

**Issue by topperspal** [supabase/supabase#4792]
25$ is not a piece of cake for everyone, especially for startups where FREE Quota is not enough and 25$ are more then enough. Please add a new pricing tier for 10$. This will remove the constraints of 2 org x 2 projects, and we will be able to host our hobby projects along with professional apps in a very affordable price.

**Comment by kiwicopple** [comment]
Any ideas for what you'd like included at a $10 range @topperspal ?

**Comment by topperspal** [comment]
Yup!

10$ is enough for providing these functionalities.

1. NEVER PAUSE
2. 2 GB Database with 15 GB Data Transfer Limit
3. 30 GB Storage with 60 GB Transfer limits
4. 2 days backup

If we compare it to 25$ plan, then we will be paying 40% for

1. 25% of database storage
2. 30% Database Transfer
3. 30% Storage
4. 30% Storage Data Transfer
and nothing else.

Almost 30% or less resources in 40% credit, sounds good both for supabase and develpoers.

**Secondly make it the base plan to test Functions.**

**Comment by Isaiah-Hamilton** [comment]
Instead of never pausing it should be a month until pausing. and with the $10 plan, we should have 50,000 users.

**Comment by jorgemndoza** [comment]
The only reason I haven’t migrated some of my client apps is because I’ll have to increase their monthly fee.

**Comment by kiwicopple** [comment]
Unfortunately we have some infra costs which are fixed, so reducing everything down to 30% doesn't reduce our costs to 30% 😓 

Regardless, this feedback is well received - we will take it on board and see what we can do. I'll close this now, but feel free to comment or turn this into a Discussion

**Comment by nbx3** [comment]
I'd like to have several development projects (i dont mind if these get paused) and one live one but on the free tier you are limited to two projects in total. Its not clear if i sign up for $25/project/month plan what i get - do i just get one extra project that doesn't pause with higher quotas etc or does this apply to all my projects? How do i get more than two organisations as well?

**Comment by kiwicopple** [comment]
thanks for the comment @jorgemndoza - you're absolutely correct. You get 2 free and unlimited Pro. The pro projects get higher limits and they will never pause

**Comment by mmaaaaz** [comment]
Would love to have a $10 tier. Please tell me you guys are working on it.

**Comment by hdoshi2** [comment]
@kiwicopple Let me start off my saying Supabase is awesome and helped me progress quickly as a new software developer. As someone who is learning and playing with Supabase regularly (no commercial or high usage projects yet), I feel the limit of two projects only is really restrictive. I also don't mind if inactive projects are paused in the free tier. And if usage for any projects is high enough then I also don't mind paying $25 or $10, but it's hard to keep small projects such as portfolio projects (which get minimal to no traffic) connected to Supabase if the fee is $25 ($300/yr) to just have an active DB. I had to permanently delete past useful learning projects that I built just so I can create a new project which also wont be seeing much traffic.

**Comment by topperspal** [comment]
I am agree with @hdoshi2

This is really a considerable issue.

**Comment by kiwicopple** [comment]
thanks for all the feedback everyone - it's incredibly useful for our pricing planning

As we start to support larger (Enterprise) customers, we can support  more indie devs. At the moment our user-base is skewed towards indie devs (which we love), who we support financially with free projects. We need to build a sustainable business so that you feel safe to build with us. 

I heard that Jeff Bezos said "There are two kinds of companies, those that work to try to charge more and those that work to charge less. We will be the second.". I think that's a good model for us too - over time our business economics will allow us to support more indie devs

**Comment by topperspal** [comment]
Supabase is the best Firebase alternative I think so. But let me tell you why do we you firebase

**Firebase** is good for -
1. You can create many projects
2. Pricing start from **0** to **pay as you go**
3. **Appcheck**
4. FirebaseUI
5. And some other services


The reasons most of developer searching for firebase alternative, are -
1. Firestore pricing plan
2. No easy pricing cap

Things where Supabase shines are -
1. Open source❤️
2. PostgreSQL is great
3. Loving community

But there are also some drawbacks -
1. Only two projects are allowed for testing, as @hdoshi2 mentioned
2. Paid plan is too high especially for countries where one dollar is almost equal to 100. I don't know whether you are using Googe Cloud, AWS or Microsoft Azure but all those products are expensive who are using all these services. DigitalOcean is more budget friendly. I personally use DigitalOcean for NodeJS apps and it is good.
3. Lastly supabase data can be accessed from any platform once the key has been stolen via reverse engineering. So please make it secure using Firebase app check or something similar.

**Comment by Saulmarti** [comment]
I think the gap between the free projects and the Pro plan is to big. It could be very beneficial to have a "Dev" plan for about 5$ with something like: never paused, 1gb database, 5gb file storage, 4gb bandwidth, etc. And another "Standard" plan for about 10$ like: 3gb database, 15gb file storage, 10gb bandwidth, 3 days backup, etc

As an example, i have about a 10 small projects that i would be interested in migrating to Supabase and only 1 would fit Pro plan, most of the others are very close to the Free plan and a couple in between.

To migrate these 10 projects would currently cost me 250$ per month, which is prohibitive.
With these or similar plans it could be something like this:

5$ x 8 small projects + 10$ x 2 medium projects + 25$ x 1 pro project, that its more affordable.

I think the Pro plan is very good but small developers also need something that fit them better.

I hope it helps

**Comment by SergejSachs** [comment]
I have one "app" on supabase that im working on. This needs two projects, one for dev and one for live.

I would like to migrate another app from firebase to supabase but that would be 50 euro/month.

I would not mind to pay a small amount just for more "free tiers" with the same quotas.

Im not sure if this is financially possible for supabase but would be cool.

**Comment by mahyuddin** [comment]
Couldn't agree more. $5/month and $10/month plans really help us for our rnd and serve our current clients.

**Comment by B3nten** [comment]
Personally I'd like an alternative paid plan that lets us have more active projects but share a resource pool. That way we can have many smaller projects that receive only tiny amounts of traffic, but if one starts to incur more usage we could pay for the $25/month plan for that one.

Right now I'm looking into self-hosting my projects elsewhere because I want to have more than two active. But I'd rather pay Supabase for their product!

**Comment by mimccio** [comment]
Something like this could be better : 

- basic plan: 5$ per project + 2 free projects (with same limits as free tier)
- pro plan: 25$ per project
- enterprise plan

That way we can have a lot of small projects and develop / staging environments per project without paying 25$ for a very little use.

**Comment by ak4zh** [comment]
Ability to increase just database size would be really useful.

- Free Tier = 500 mb
- Ability to increase database size at $5 per month per gb.

**Comment by phiberber** [comment]
I'm having the same problem as most people here. I want to migrate 30-50 apps to Supabase, but they are very simple and don't require anything from the Pro section. I would need though to pay something like 750$ per month for something I am not really using at all.

It makes sense that Supabase has fixed costs but paying 25$/month per project is not worth it. I would prefer a `pay as you go` but with a better thought database rate limiting (Everyone hates firebase because of that).

**Comment by git-Amarjeet** [comment]
Ended up here while searching for more pricing info on Supabase, and I cannot agree more than a $10 pricing tier is precisely what stops me from using Supabase.

**Comment by joeldrotleff** [comment]
@kiwicopple For my project, my big worry is storage. It's a video streaming app so I am worried about needing extra storage space. I'm not anticipating getting many users or anything, so $25/month is too steep. But I don't mind paying for extra storage.

Do you know if it is possible to pay-as-you go for storage on the free plan?

**Comment by kiwicopple** [comment]
We don't have PAYG storage on the free-plan yet @joeldrotleff , and admittedly no plans for it just yet.

I just want everyone to know that I read these comments and I'm taking them in. 

The cost isn't so much the size of the database, it's keeping the database running (y'all are getting 2 free servers). With that in mind, we're working on a way that we can quickly pause and restore databases "on demand" - they would have a very short warm-up time, similar to a serverless function. That would allow us to provide scale-to-zero databases, which would drastically reduce our costs and opens the possibility of a cheaper tier.

We're in a phase of the business where we still need to grow sustainably and that would be impossible at the $10 price tier that most people are asking for. There's a reason why Heroku is shutting down, and we don't plan to follow their lead.

**Comment by joeldrotleff** [comment]
Cool thanks for responding. Totally understand you folks need to find something sustainable.

In case it's helpful, here are my current musings on "Should I switch to Supabase from Firebase for my random 1-user side project."

- That Fireship guy said it was cool and he's cool so I'll try it out
- Supabase website looks so much better than dated janky Firebase website
- Oh cool edge functions is out of beta, and they have login
- Ah but Firebase is free for the foreseeable future, and by the time it costs anything I'm probably making more than enough to cover
- But Google kinda sucks, alright I'll try Supabase tutorial
- Oh no it doesn't have a first class Swift client package. At least there's some "community" ones...
- Ah, first thing I tried to do didn't work: https://github.com/supabase-community/gotrue-swift/issues/44
- Yea, I'm probably gonna go back to hacking around with my new timelapse video feature since I'm a server noob. But I'll check back later cause this project does look really promising.
