### ISSUE TITLE
Sign up emails being marked as spam

### ISSUE THREAD

**Issue by AJamesPhillips** [supabase/supabase#4858]
# "Bug" report

## Describe the bug

Sign up emails being marked as spam

## To Reproduce

Sign up for a new supbase account using an email on a google server

## Expected behavior

Should not be spam

## Screenshot

![Confirm_Your_Signup_-__-_centerofci_org_Mail](https://user-images.githubusercontent.com/526509/148545942-fec00436-df79-4673-a653-e4d5b397c7e5.png)

**Comment by kiwicopple** [comment]
The most immediate workaround for this is to add your own SMTP provider @AJamesPhillips.

We'll look into this in the meantime

**Comment by J0** [comment]
Hey all!

We're going to close for now in favour of an [internal issue to track this](https://github.com/supabase/infrastructure/issues/1476) but rest assured that it's being worked  on.

For now, the best bet might be to use a custom SMTP provider as mentioned.

Let me know if there are further questions.

Thanks

**Comment by vincelwt** [comment]
Hey, 

I'm getting this with a custom SMTP provider (Mailgun) with all the DKIM/SPF/DMARC set right. Trying to see with their support what can be done, otherwise will try a different provider. 

A couple things on Supabase's side that could be improved:
- The long link, sending to a different domain than the sender
- Email body not valid html spec (missing <html> and  <Doctype> tags) 
- No text/plain variation of the message body

**Comment by vincelwt** [comment]
@bdepascale I've temporarily solved this by using my gsuite as the SMTP sender.

Oh and the default SPF record supplied by google (v=spf1 include:_spf.google.com -all) still sent my mails to spam. Had to set their IPs manually for it to work: 
`v=spf1 mx ip4:209.85.220.41 ip4:209.85.220.65 ~all`

That said, I have 10+ domains on mailgun and this is the first time I had spam issues. So definitely think something about the way supabase sends the emails isn't helping.

**Comment by lewisd1996** [comment]
Im currently using a custom gmail/google domains SMTP and also have this issue

**Comment by guicoelho** [comment]
Hey guys, this is still an issue (Magic link emails being market as spam by Gmail).

Is there any fix available other than not using Supabase's SMTP servers?

Thank you

**Comment by jamesv-menklab** [comment]
Any update here?  We are seeing the same thing.

**Comment by Wamy-Dev** [comment]
I am using my own smtp and it is still being marked by spam. I am using improvmx.

**Comment by nkolenda** [comment]
Any updates? I'm facing this issue too.

**Comment by maelthi** [comment]
Same issue here, please respond

**Comment by monicakh** [comment]
One of our partners has some great insights on email deliverability. Check out the playbook they've put together, it's designed to help you improve this:
https://resend.com/docs/knowledge-base/how-do-i-maximize-deliverability-for-supabase-auth-emails

**Comment by AJamesPhillips** [comment]
As the OP (original poster) I'm happy to leave this issue thread unlocked or to have it locked now as the solution is to set up our own SMTP provider and there are many options like SendGrid, Resend etc.

Thank you sharing for that guide @monicakh https://resend.com/docs/knowledge-base/how-do-i-maximize-deliverability-for-supabase-auth-emails  is really clear and useful.

**Comment by LawrenceHunt** [comment]
For anyone who finds this wondering why their custom domain and subdomain aren't making any difference, I thought I'd add my own experience. 

I set up a SMTP subdomain using resend, and a matching custom domain for my cloud supabase DB - yet was still seeing all my reset password emails go straight to gmail's spam folder.

The fix was simply **adding some proper html for the email template**. Realise now I should have done this first!

Installing react-email into the project, running it locally, working on a simple layout in React and copying it over as a table html layout - this seems a decent workflow.

**Comment by logicminds** [comment]
Still seeing this issue today in about 30% of my emails being sent to resend.  Appears like recipients with gmail work fine.  What is the proper html spec I need to use?

**Comment by GrantlyNeely** [comment]
I am also struggling with Supabase emails being marked as "Dangerous" (was using Brevo SMTP, but I just moved to Resend SMTP as this thread suggested) with the switch to Resend I am still being marked as "Dangerous". I am not sure what to do because my customers are getting spooked?!

I have been able to get around being flagged as "Dangerous" if I construct the Magic Link server-side and send the email directly with the Resend API, but then I don't have access to password reset rate limiting etc.

**Comment by deepak-coding-art** [comment]
I am facing the same issue with custom SMTP server and domain is validated
The magic links have this domain
`.sendibt2.com`
And Gmail is saying that this link is suspicious

**Comment by MANTENN** [comment]
Still an issue. I am using AWS SES and supabase.co domain flags email as dangerous/phishing link type of content because of the redirect in it too. 

<img width="526" height="835" alt="Image" src="https://github.com/user-attachments/assets/84e9bc92-8f78-4849-abe2-eec81c8c005d" />

**Comment by MANTENN** [comment]
I tried setting up the custom domain however that is broken, so it seems like I do have to roll a bit of my own recovery mechanism if its possible.

**Comment by MANTENN** [comment]
<img width="1728" height="895" alt="Image" src="https://github.com/user-attachments/assets/bd34f6ea-4de2-4e9c-acc0-2aeef70452c0" />

I am using Amazon SES to send the emails. 

Custom domain does not work either. Wow. It must be the redirect mechanism.

**Comment by Velkamhell97** [comment]
“@MANTENN Did you find a solution? I’m having the same issue with the reset password email. Was the problem the SMTP provider or the template? I’m using Resend as the SMTP provider with the Supabase integration, but this email is always marked as spam

**Comment by themushdev** [comment]
it's most likely not an SMTP problem, it's the way the email is formatted (not proper HTML, missing tags all around)

using proper HTML formatting fixed for me
