### ISSUE TITLE
Docker /Composer images for arch/raspberry

### ISSUE THREAD

**Issue by Jujubalandia** [supabase/supabase#4887]
# Supabase running on Raspberry Pi

## Using docker and docker composer to run Supabase isn't working

Would be nice to allow users to use Supabase with this popular platform

**Comment by kiwicopple** [comment]
Hey @Jujubalandia - thanks for dropping in! If you can provide some more detail we'll be happy to dig into this. Could you please provide some steps to duplicate the issue and any errors you're facing?

I'll close this for now but feel free to comment and I can reopen

**Comment by zoocityboy** [comment]
> exec user process caused:

same on Oracle cloud with ampere CPU (aarch64)

**Comment by brkblgn** [comment]
Same issue with Raspberry Pi 4

> It seems like some supabase images are currently not running on the Raspberry's architecture, resulting in `standard_init_linux.go:228: exec user process caused: exec format error`

**Comment by kiwicopple** [comment]
got it, reopening this. If anyone can provide more logs to help with debugging that would be great

**Comment by BadochAlexandre** [comment]
Hello guys, 

I am also trying to self-host your wonderful project on my raspberry-pi.

I think the issue come from the fact that, raspberry-pi are based on ARM. And Docker images are mostly available for more standard architecture like x86.

This is the error I get when I am trying to run "docker-compose up"

![image](https://user-images.githubusercontent.com/74237941/157021467-da2dfd8a-0ed1-4957-9e39-bccf1a9d28dc.png)

**Comment by julienR2** [comment]
@BadochAlexandre did you manage to get it working ?!

I tried sometimes ago before all the images were compatible, but haven't tried again since then.

Really curious to see if now it got easier and more strait forward !

**Comment by notjustinshaw** [comment]
Got this working this evening on a Pi4.

All the docker images are built for x86 architectures, as that is by far the most common machine architecture these days. If you want it to run on an ARM/AARCH architecture like a Raspberry Pi, you just need to build the images yourself. Nothing was ever "broken" on Supabase's end (though the documentation was, admittedly, lacking).

I went through all the images listed in the `supabase/supabase` repo in the `docker/docker-compose.yaml` file. Pulled each one onto the pi and built that image locally, and tagged it with `:latest-arm64` then I updated each of the image names in the `docker/docker-compose.yaml` file to use my local copies instead of the default x86 ones.

That got the application up and running but it still had some bugs. I changed the `.env` file and added the JWT secrets as per the documentation, but that is *not enough*. You also need to change the `kong.yaml` file inside the `docker/volumes` directory as well as change the URLs in the `.env` file to point to the pi instead of localhost (though, to be fair, that last part was documented briefly in the self-hosting docs). On my home network, my pi is called `pi` and I had to change `http[s]://localhost:<port>/*` to `http[s]://pi:<port>/*`

**Comment by julienR2** [comment]
@notjustinshaw Thanks a lot for the walkthrough and the tips 👌 Make me more confident to try again soon !

**Comment by titogarrido** [comment]
> 

I am trying to build the supabase/postgres image in my RPi4 but it is taking hours... Did you rebuild them all just cloning and running docker build on each?

Thanks!

**Comment by notjustinshaw** [comment]
Heh. Yeah my build took 4.5 hrs for supabase/postgres — I just started it in the morning and then went about my day ;)

**Comment by kiwicopple** [comment]
Hey everyone - sorry for the late response here. We started building ARM images for all of our docker images now. 

![image.png](https://volta.s3.fr-par.scw.cloud/image_d036f00493.png)

I'll close this one for now, but if you have any problems, just drop a comment here and I can re-open
