### ISSUE TITLE
supabase/auth

### ISSUE THREAD

**Issue by jeevanantham123** [supabase/supabase#4962]
We have Auth users table where we are storing logged in user details. Is there any way to edit the table like adding particular columns to the same auth users table and querying it. Eventhough i added a column, supabase client not returning that column while querying. I have tried model updation and so on

**Comment by kangmingtay** [comment]
Hi @jeevanantham123, the auth users table is actually maintain by supabase and the schema shouldn't be modified because gotrue (supabase-auth) relies on it heavily. If schema changes need to be made, you can modify your own `public.users` table and add the id of the `auth.users` table as a foreign key.

**Comment by jeevanantham123** [comment]
Hi @kangmingtay , can i query `auth.users ` table using this [](https://supabase.com/docs/reference/javascript/select#query-foreign-tables) ? if i use **id** as a foreign key.

**Comment by kangmingtay** [comment]
yeah, you can
