### ISSUE TITLE
How to require current password before being able to updateUser?

### ISSUE THREAD

**Issue by leafblader1** [supabase/supabase#5383]
### Discussed in https://github.com/supabase/supabase/discussions/5341

<div type='discussions-op-text'>

<sup>Originally posted by **leafblader1** February  6, 2022</sup>
GoTrue API doesn't require users to confirm their current password before updating the users fields, including the new password. This is pretty insecure, how can I disable this endpoint (and only ask for password changes through email) or require current password?</div>

**Comment by GaryAustin1** [comment]
Dropping this here also:

The email password link ends up using the same API so if you shut that off then you can't update anyway.

There is work going on:
https://github.com/supabase/gotrue/pull/309
https://github.com/supabase/gotrue/issues/264

**Comment by leafblader1** [comment]
Shutting it down is not ideal, agreed.

Thanks. I just read through the PR's and it's exactly what I'm looking for. Glad it's being worked on. Hope to see it added soon. It is crucial for the development of our application - we want to offer as much security as possible.

**Comment by kangmingtay** [comment]
closing this in view of https://github.com/supabase/gotrue/pull/427

**Comment by tomekit** [comment]
I've enabled the: `GOTRUE_SECURITY_UPDATE_PASSWORD_REQUIRE_REAUTHENTICATION`, but now my users can't really use reset password workflow due to: "Password update requires reauthentication" error. 
Possible related: https://github.com/supabase/supabase/discussions/7310

Is the reauth feature for password update compatible with the password reset workflow?
