### ISSUE TITLE
Unable to create foreign key relationships in the Table Editor

### ISSUE THREAD

**Issue by geordidearns** [supabase/supabase#592]
# Bug report

## Describe the bug

Unable to create relationships between tables using the 'Add foreign key' function in the table editor. Go through the add foreign key flow as described below and receive `Could not find foreign keys between these entities. No relationship found between 'table_name' and 'table_name_2`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Got to a table, right click the column you wish to add a foreign key for
2. Select 'edit column'
3. Select 'Add foreign key relation' 
4. Select the table and column to make a foreign key for
5. Click save

## Expected behavior

You get feed back that a relationship has been created, the response in the payload shows a relationship exists and i'm able to query the tables using select as shown in the documentation

## Screenshots
![supabase_foreign_key](https://user-images.githubusercontent.com/5615153/105588309-c6177800-5d91-11eb-90ba-45b941d1c1e9.gif)

![Screenshot 2021-01-23 at 15 43 25](https://user-images.githubusercontent.com/5615153/105588440-cf084980-5d91-11eb-9d3e-3f35a16174c2.png)

## System information

- OS: MacOS
- Browser (if applies) Chrome
- Version of supabase-js: -
- Version of Node.js: -

## Additional context

Please reach out for more context, or to take a call if needed

**Comment by geordidearns** [comment]
@awalias hey! Just wondering if this is actually an issue, or if I'm trying to create the relationships incorrectly? If it is me, this can be closed 😅

I'm looking to fetch from a primary table and get related rows from from a secondary to able via foreign key

E.g fetch Posts, and get all comments from another table based on a unique identifier 

Thanks 😊

**Comment by joshenlim** [comment]
Hey @geordidearns! Sorry for the delay in response - we've managed to find where was going wrong in the editor and are pushing out a fix soon! Should fix the inability to create a foreign key relation via the editor.

On a separate note though,  i was trying to reproduce the bug by following your schema in the screen grab. Just note that the column that are you trying to create a reference to (`users.uuid` in your context) has to be a primary key column, otherwise you'll run into a SQL error: `There is no unique constraint matching given keys for referenced table "users"`

I'm presuming you might have run into some issues setting the primary key column for your `users` table as `uuid`, like having to manually insert a uuid to create a row. There's a workaround currently for that:

- Create a new table while unchecking the "Include primary key".
- Once the table is created, create a column (the first column that you create for a table that has no primary key will have a checkbox "Is primary key" thats checked) and select `uuid` as the type.
- You'll notice that you there'll be a default option of "Automatically generate UUID" in the default value field
- Go ahead and create the column and you shouldn't need to manually enter a UUID when creating a new row

It's really not the best experience - definitely hoping to reorganize the side panel fields to make everything more clear and seamless (e.g. Things like allowing you to specify the default value as automatically generate at the table creation step)

![image](https://user-images.githubusercontent.com/19742402/106305625-e070ba80-6297-11eb-8906-039ddfec5a5e.png)

![image](https://user-images.githubusercontent.com/19742402/106305660-eb2b4f80-6297-11eb-8928-6799c7f18d49.png)

**Comment by geordidearns** [comment]
hey @joshenlim 👋 

Thanks for the great reply! Great that you are able to fix it so fast 😄  (It's usually me mis-clicking in UI when it comes to these things)

And yes! In this case i was wanting to keep the INT primary key and have a uuid for it - but am re-thinking the need for that - and of course the foreign key should reference the primary key of the other table 🤦 Thanks for the reminder!

Really appreciate the response, great work with Supabase so far! 🥳 

Do you have an idea on the fix timeline? No problem if not!

**Comment by geordidearns** [comment]
@joshenlim I got it working by running a raw query and fixing the foreign key, i'll probably do this from now haha thanks again

**Comment by joshenlim** [comment]
@geordidearns the fix will perhaps be in production in a day or two - but gotcha! glad that you've nonetheless managed to resolve the issue!

**Comment by brunocrosier** [comment]
I think I'm still getting this error when building relationships via the GUI - just wanted to bump in case anyone else is also experiencing it

**Comment by StevAlberts** [comment]
@brunocrosier.

Make sure you have the same field type as the primary.

**Comment by LEvinson2504** [comment]
I faced issue when adding a foreign key, and yes make sure the types are the same to avoid this, also you might have to delete the column and try again because for some reason I wasn't able to update the column type, but deleted the old, created new column with proper type I want to add a foreign key to and it worked. Hope it helps someone.

**Comment by olefritsch** [comment]
I'm running into this issue when defining the column as an array. Types are the same, and single values work as expected.

**Comment by akiarostami** [comment]
I'm having the same issue, I add a foreign key to a table and save it, I see no error, but it actually doesn't get saved.

**Comment by juanzgc** [comment]
The bug is currently the following:

1. Create a new table: `table1` - set an additional column as a primary key. Let's call this column `slug`.
2. Now create a second table: `table2` - create a column (`table2_slug`). Lets add a Foreign Key to `table2_slug` and lets reference our `table1` -> `slug`. 

You will get the following error:
```
Error updating foreign key: there is no unique constraint matching given keys for referenced table
```

Now how to set a foreign key without causing the error:

Let's delete `table1` and recreate it:
1. Recreate `table1` - create column `slug` but this time instead of setting as a primary key, add the unique constraint.
2. Edit `table2` and add a foreign key to `table2_slug`. Lets reference our `table1` -> `slug`.

This time our foreign key should be created successfully.

**Bugs:**
1. So what is actually happening? It seems that Primary Keys in Supabase don't actually create a `UNIQUE` constraint. **bug**. This should be fixed asap since it may prevent many developers from creating foreign keys.

2. Within the Supabase UI, you are unable to add Unique constraints when adding a new column to an existing table. This is very frustrating, especially if you are dealing with bug #1. You are also unable to remove the unique constraint from an existing column.

3. You are unable to add new primary keys to an existing table.

**Comment by joshenlim** [comment]
Hey all! We've just pushed a couple of improvements to the table editor including some fixes/updates to managing your foreign keys - they should be working well now but do give a shout if anyone is still facing any issues.

Also, selecting a column to create a reference to in the side panels will automatically select the `Type` of the current column, to that of the column that you're creating a reference with as such for greater convenience:

<img src="https://user-images.githubusercontent.com/19742402/133034215-d8b294ab-bcfe-4579-b2db-a45555d1985a.png" width="500" />

**Comment by juanzgc** [comment]
@joshenlim Thanks for this fix! But unfortunately, it still doesn't solve the bug that I discovered.

**Note**:
After further examination I discovered that my hypothesis:

> It seems that Primary Keys in Supabase don't actually create a UNIQUE constraint

Is actually correct. I've examined the catalog schema from Supabase after creating a table with a Primary key and we see the following.

| name | type | primarykey |  uniquekey |
| :---- | :-----: | :------: | -------: |
| id | uuid | t | f |

So our bug is the following:
Primary keys in Supabase are not adding the Unique attribute. 


The SQL script to see the following schema info:
```
SELECT  
    f.attnum AS number,  
    f.attname AS name,  
    f.attnum,  
    f.attnotnull AS notnull,  
    pg_catalog.format_type(f.atttypid,f.atttypmod) AS type,  
    CASE  
        WHEN p.contype = 'p' THEN 't'  
        ELSE 'f'  
    END AS primarykey,  
    CASE  
        WHEN p.contype = 'u' THEN 't'  
        ELSE 'f'
    END AS uniquekey,
    CASE
        WHEN p.contype = 'f' THEN g.relname
    END AS foreignkey,
    CASE
        WHEN p.contype = 'f' THEN p.confkey
    END AS foreignkey_fieldnum,
    CASE
        WHEN p.contype = 'f' THEN g.relname
    END AS foreignkey,
    CASE
        WHEN p.contype = 'f' THEN p.conkey
    END AS foreignkey_connnum
FROM pg_attribute f  
    JOIN pg_class c ON c.oid = f.attrelid  
    JOIN pg_type t ON t.oid = f.atttypid  
    LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = f.attnum  
    LEFT JOIN pg_namespace n ON n.oid = c.relnamespace  
    LEFT JOIN pg_constraint p ON p.conrelid = c.oid AND f.attnum = ANY (p.conkey)  
    LEFT JOIN pg_class AS g ON p.confrelid = g.oid  
WHERE c.relkind = 'r'::char  
    AND n.nspname = '%s'  -- Replace with Schema name  
    AND c.relname = '%s'  -- Replace with table name  
    AND f.attnum > 0 ORDER BY number
;
```

**Comment by darora** [comment]
@juanzgc I can't reproduce what you're describing. Can you share the full schema of the table you're trying to reference? Using either `\d {table_name}` in psql or 
```
SELECT *
FROM 
   information_schema.columns
WHERE 
   table_name = '{table_name';
```

Note that in Postgres, a primary key is a stronger constraint than a unique one (c.f. https://www.postgresql.org/docs/13/ddl-constraints.html ), and can be used to create a foreign key relation.

One thing that I noticed is that you mentioned that "slug" was an _additional_ column, in which case you might've created a composite primary key.

**Comment by darora** [comment]
Based on a glance through this thread, it sounds like the bug affecting creation of foreign key relations has been fixed. Closing this out to avoid mixing in unrelated issues.

The UI around Unique constraints seems lacking, and is being tracked in #770

**Comment by juanzgc** [comment]
@darora - I don't believe this bug is completely solved considering I faced this bug last night.

> you might've created a composite primary key.

Correct it was a composite key.

If you are to create a composite primary key you will notice that it doesn't set it with a `UNIQUE` constraint. Please run the SQL script that will display which columns are primary keys and its unique constraint.

![image](https://user-images.githubusercontent.com/24414523/133097396-f550c0b6-3a88-429d-8801-3faefa168038.png)

![image](https://user-images.githubusercontent.com/24414523/133097676-e0c8de83-a615-480b-bc99-02676f871e7b.png)

`slug_foreign` was set with a `Foreign Key` which references `table1` -> `slug`. However, we are unable to since an error occurs.

![image](https://user-images.githubusercontent.com/24414523/133097815-dfef59b2-3b8b-44df-b45f-135e967bea11.png)

The error is due to `table1` -> `slug` not being considered with a `UNIQUE` constraint. Eventhough, a Primary Key should have a `UNIQUE` constraint by default.

![image](https://user-images.githubusercontent.com/24414523/133097994-d6f8487a-b3af-4dc7-8320-0af3634239d2.png)

As we can see from my SQL script - `slug` is a primary key (so is `id`). But they **do not** have a `UNIQUE` constraint.

fyi @joshenlim

**Comment by akiarostami** [comment]
This is not resolved for me. When I try to add a foreign key, I get this error:

Error: Cannot read property 'accept-version' of undefined

Screen shot is attached.

![CleanShot 2021-09-13 at 09 05 14](https://user-images.githubusercontent.com/1235113/133119265-a74906be-affb-42bd-82a7-ae6d7d4dedb9.png)

**Comment by joshenlim** [comment]
@juanzgc ahh okay, this might be an error on our UI - will look into this! 

it's a weird one but this is specifically happening only for when you're creating a table in the side panel with a column that's referencing another table with a composite primary key. If you need a workaround for now, what you can do is to add the relation after creating the table.

So create `table2` first without `slug_foreign`, then add the `slug_foreign` column with the relation thereafter (Or even, with the `slug_foreign`, let it error out but the column will be created still, then just add the relation to the column)

As @darora mentioned a primary constraint is stronger than a unique one - a column does not have to be both `primarykey` and `uniquekey` for another column to reference to it.

**Comment by juanzgc** [comment]
Thanks Josh, and yes I agree it does not require a Primary Key - it only requires a Unique Field. 

Im my opinion it might also be an SQL error since a primary key should by default have a Unique constraint to it. 

Also, in Supabase UI it does not allow to create a unique column after a table has already been created.

**Comment by joshenlim** [comment]
@akiarostami thanks for the catch! we'll look into this one too, and apologies for the really vague error message, we'll try to improve that so its much more clearer!

I tried to reproduce your issue too and have a tentative workaround for the UI if you need one: this error seems to be popping up when you're specifically trying to update a column from a numerical type (int, float) to uuid. Two ways around this, either

- Create a new `pid` column with the reference up front
- Cast your existing `pid` column to `text` type first, then to `uuid`

Sorry about this! I know it's not the best experience, but we'll definitely continue to ship improvements and make things better for everyone :)

**Comment by joshenlim** [comment]
@juanzgc ahh the option to *create* a unique column is actually available in the side panel when you select "new column" as such below the default value text input:
<img src="https://user-images.githubusercontent.com/19742402/133129970-f8b64f5d-0bdd-4f48-8cc2-b5f501da3feb.png"  width="500" />

let's try to keep the comments here related to managing foreign keys in the UI, if you do find any other UI quirks feel free to open a new issue!

**Comment by juanzgc** [comment]
@joshenlim Thanks! It seems that the UI has changed as of last night. Great to see this, very exciting!

I look forward to continue testing your services and I hope to be as helpful as possible!

**Comment by joshenlim** [comment]
Thank you so much for the support @juanzgc :) greatly appreciated 🙏

**Comment by juanzgc** [comment]
@joshenlim Would it also be possible to add the `Is Unique` attribute to the Edit Column modal as well.

We can see the attribute in the Create Column modal but not in the Edit Column modal. Thanks in advanced!

![image](https://user-images.githubusercontent.com/24414523/133143106-0b185fdc-829c-44d1-a146-970baef7de02.png)

**Comment by akiarostami** [comment]
Thank you @joshenlim for the update and all your help.

Going back to your suggestion, I had another issue which might be related to this.

When I originally created this table, I used the script below with no problem:

`create table petitions (
  id uuid generated by default as identity primary key,
  ...
);`

Now when I try to run the same script, I get the following error:

`identity column type must be smallint, integer, or bigint`

Is this related in any way? If not, why could I create UUID identity columns before, but not anymore?

**Comment by darora** [comment]
@juanzgc - from a SQL perspective, this is expected behaviour.

table1's primary key is `(id, slug)`, and as such, postgres does *NOT* guarantee uniqueness on the `slug` column in isolation. Therefore, trying to reference it as the foreign key fails.

If you set `slug` to be the primary key by itself, this would work. Or, as you noticed, additionally constraining it as unique, on top of `(id, slug)` being the primary key would also do the trick.

> @darora - I don't believe this bug is completely solved considering I faced this bug last night.
> 
> > you might've created a composite primary key.
> 
> Correct it was a composite key.
> 
> If you are to create a composite primary key you will notice that it doesn't set it with a `UNIQUE` constraint. Please run the SQL script that will display which columns are primary keys and its unique constraint.
> 
> Below I will include the steps to replicate this bug:
> 
> ![image](https://user-images.githubusercontent.com/24414523/133097396-f550c0b6-3a88-429d-8801-3faefa168038.png)
> 
> ![image](https://user-images.githubusercontent.com/24414523/133097676-e0c8de83-a615-480b-bc99-02676f871e7b.png)
> 
> `slug_foreign` was set with a `Foreign Key` which references `table1` -> `slug`. However, we are unable to since an error occurs.
> 
> ![image](https://user-images.githubusercontent.com/24414523/133097815-dfef59b2-3b8b-44df-b45f-135e967bea11.png)
> 
> The error is due to `table1` -> `slug` not being considered with a `UNIQUE` constraint. Eventhough, a Primary Key should have a `UNIQUE` constraint by default.
> 
> ![image](https://user-images.githubusercontent.com/24414523/133097994-d6f8487a-b3af-4dc7-8320-0af3634239d2.png)
> 
> As we can see from my SQL script - `slug` is a primary key (so is `id`). But they **do not** have a `UNIQUE` constraint.
> 
> fyi @joshenlim

**Comment by joshenlim** [comment]
@akiarostami ahh interesting - specifying a column to be `GENERATED AS IDENTITY` will automatically assign a unique *number* to each row under that column [[ref](https://www.postgresqltutorial.com/postgresql-identity-column/)].

This also implies that UUID types cannot be declared as `GENERATED AS IDENTITY` hence why the error message you saw `identity column type must be smallint, integer, or bigint`

I'm not too sure why you were able to run that query initially though, but if you're looking to create a UUID column with an automatically generated value for each row, you can also try using the following expression `uuid_generate_v4()` as such:
`CREATE TABLE petitions ( id uuid DEFAULT uuid_generate_v4() PRIMARY KEY, ... );`

**Comment by joshenlim** [comment]
@juanzgc so sorry but after digging into your issue further regarding referencing a column from a composite key, I realised you were right with what you said earlier.

- To create a column that references another column which is part of a composite key, the referenced column must specifically have a UNIQUE constraint *on top* of it being part of a composite primary key. (The composite PK doesn't help with the foreign key at all here)

- The workaround I mentioned earlier is incorrect: The UI was silently swallowing the error message that came from trying to add a column which references to a column of a composite key that doesn't have a UNIQUE constraint

- I realised we do not provide the option to set a column to be UNIQUE when creating a table in the side panel, when the column has been checked as "Is Primary Key"

We're gonna push out fixes for the latter 2 pointers so that you'll be able to correctly add a column to reference to another column that's part of a composite key!

**Comment by juanzgc** [comment]
@joshenlim Thank you for looking into it further. I'm glad we were able to come to a conclusion on the cause of the bug.

Overall, I am still a firm believer that the best solution to this problem is to set all `Primary Keys` by default as `UNIQUE`.

Especially considering that is technically the definition of a primary key. It is impossible to have _two_ of the same primary keys in a table.

This is also confirmed from PostgreSQL Documentation:

> Technically, a primary key constraint is simply a combination of a unique constraint and a not-null constraint.

cc @darora

**Comment by joshenlim** [comment]
@juanzgc there are certain use cases where by the columns which are part of a composite key are not individually UNIQUE though. Composite keys indicate that the selected group of columns function as a unique identifier for the row. A use case I can think of for example is:

Say I want to store a collection of all repositories on Github, I'd have a table that has a composite key of (organization, repository), followed by other columns such as owner, number of stars, etc. In this case, organization doesn't have to be UNIQUE. Example data:

| organization  | repository | num_stars |
| ------------- | ------------- | ------------- |
| postgres  | postgres  | 8000 |
| postgres  | pgadmin3  | 5000 | 
| postgres  | pgadmin4 | 4000 |
| postgres  | pgagent | 3000 |

So I'd think that we shouldn't implicitly set all primary keys to be UNIQUE by default, by rather let the user decide so

**Comment by juanzgc** [comment]
@joshenlim Thank you for that example! I agree 100% that composite keys should be left for their user to decide.

**Comment by joshenlim** [comment]
i'm going to close this ticket for now as it seems like the issue is now resolved :) thanks so much everyone for your inputs!

**Comment by selectboxit** [comment]
> I think I'm still getting this error when building relationships via the GUI - just wanted to bump in case anyone else is also experiencing it





https://github.com/angular/angular.js
