### ISSUE TITLE
supabase storage does not reflets the table of objects

### ISSUE THREAD

**Issue by alexandregiordanelli** [supabase/supabase#5960]
I woried about a problem.. in the dashboard of supabase, it is not showing me all my objects .. just 1000.. but I have more than 180k.. when I download a file using supabase client js, I received this error: { message: 'Access Denied', status: 400 }.. but my bucket is public.

**Comment by GaryAustin1** [comment]
You also asked this in discord.  
The 400 error is because you need to have object policies even for public buckets.  All public does is all a public url to access the files directly in storage.

The 1000 limit sounds like the default API limit being hit.  The Studio code for storage is not yet in this repository (I don't believe), so not sure what it might do for paging, but sounds like that is an issue if you don't see a way to page.

**Comment by alexandregiordanelli** [comment]
https://fttdipmtsfhnjcgijuot.supabase.co/storage/v1/object/public/cdn/a-companhia-adota-a-politica-de-classificar-dividendos-a-pag-804057-1
policy for SELECT
`((bucket_id = 'cdn'::text) AND (role() = 'anon'::text))`

**Comment by GaryAustin1** [comment]
After discussing is discord, the 400 error is occurring on the public url and in download.  Acts as if file is missing from storage.  Also the 1000 appears to be a new result with the UI and did work for more files before.

**Comment by joshenlim** [comment]
just a quick update on this one - we've done up a fix on the dashboard such that your storage items will incrementally load and will no longer be bounded by the default API limit

so you should be able to see more than 1000 items in your folder now

as for the 400 that you're facing, @GaryAustin1's right - you'll need to configure your policy properly

as the main topic of this issue is about the files not showing up - i'll go ahead to close this ticket first but feel free to open a separate issue / discussion if you're running into difficulties
