### ISSUE TITLE
Unable to refresh `graphql.rebuild_schema()` with `postgres` user

### ISSUE THREAD

**Issue by prescience-data** [supabase/supabase#6271]
# Bug report

## Describe the bug

When calling `graphql.rebuild_schema()` in a sql migration script, the function fails due to lack of permissions on the `postgres` user.

### Discussion item with context:
https://github.com/supabase/supabase/discussions/6262#discussioncomment-2493301

### Supabase code:
```pgsql
CREATE FUNCTION rebuild_schema
(
) RETURNS void
  LANGUAGE plpgsql
AS
$$
begin
    truncate table graphql._field;
    delete from graphql._type;
    refresh materialized view graphql.entity with data;
    refresh materialized view graphql.entity_column with data;
    refresh materialized view graphql.entity_unique_columns with data;
    refresh materialized view graphql.relationship with data;
    perform graphql.rebuild_types();
    perform graphql.rebuild_fields();
end;
$$;
ALTER FUNCTION rebuild_schema() OWNER TO supabase_admin;
GRANT EXECUTE ON FUNCTION rebuild_schema() TO postgres;
GRANT EXECUTE ON FUNCTION rebuild_schema() TO anon;
```

This seems like a possible bug given the EXECUTE grants to postgres, anon, and authenticated (which will fail due to lack of permissions).

Further, the `postgres` user does not have permissions to grant itself those methods, so it appears the only way to refresh is via the Dashboard?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a fresh project and enable `pg_graphql`.
2. Create a local sql migration which creates a table on the `public` schema and then calls `graphql.rebuild_schema()`.
3. Attempt to run migration via the passworded `postgres` user.

```
[2022-04-03 11:44:24] [42501] ERROR: permission denied for table _type
SELECT graphql.rebuild_schema( )
[2022-04-03 11:44:24] [42501] ERROR: permission denied for table _field
[2022-04-03 11:44:24] Where: SQL statement "truncate table graphql._field"

```

## Expected behavior

Unless I am misunderstanding the role of the passworded `postgres` user, this function should be able to execute via a migration script.

I believe that the bug may be that the `graphql.rebuild_schema()` function is intended to run as `SECURITY DEFINER` given the call post-creation to:
```pgsql
ALTER FUNCTION rebuild_schema() OWNER TO supabase_admin;
```

**Comment by olirice** [comment]
Thank you for reporting

> I believe that the bug may be that the graphql.rebuild_schema() function is intended to run as SECURITY DEFINER given the call post-creation to:

@dragarcia I think ^ is the right call since we've had similar issues before. I'll release another version of pg_graphql with ^ change tomorrow. Would you be able to get a release script/process together for it?

**Comment by prescience-data** [comment]
Thanks for that quick fix @olirice !

Semi-related, but do you have any visibility as to when this will occur automatically? (I note in the blog post that it will be eventually be triggered by DDL, so I assume at some point this will be reversed? https://github.com/supabase/pg_graphql/commit/0a2773b67b6770155bf2b3603b1c7f6ddcec28c9)

**Comment by olirice** [comment]
During development of the extension we intended for it to be automatic, triggered by a ddl event listener

I removed it at the last minute because (on free tier hardware) larger SQL can take several seconds to rebuild. That wouldn't be an issue except that it executes after every DDL operation inside the transaction. If you were executing a large migration with dozens of statements the migration might take minutes, where it previously it may have been instant.

To mitigate that, I'm planning to implement schema caching on first request, rather than after DDL. `graphql.rebuild_schema()` has been a big source of confusion so I'd expect to see it on the platform within a week or two.

From the linked commit you can see how I enabled rebuild on DDL for the test suite. Please don't do that in your project. It will cause postgres to detect a dependency between your code and `graphql.rebuild_on_ddl()` . That dependency will prevent us from being able to upgrade `pg_graphql` on your instance

**Comment by olirice** [comment]
@prescience-data could you please remove your code snippet for `graphql._rebuild_schema`?
that fix is going out to the platform today and it'll cause the same upgrade issue i mentioned ^ due to use of internal api

**Comment by prescience-data** [comment]
> If you were executing a large migration with dozens of statements

```
// migrations...
[2022-04-07 08:11:20] Summary: 273 statements executed in 22 sec, 264 ms
```

<img src="https://user-images.githubusercontent.com/65471523/162081352-093d2b26-255a-43e1-b494-60e6e46a7a7d.png" 
 width="50%" />

You're right, much faster doing it at the end 😂

```
SELECT graphql._rebuild_schema( )
[2022-04-07 08:11:16] completed in 2 sec, 891 ms
```
