### ISSUE TITLE
Kong doesnt start in supabase self host

### ISSUE THREAD

**Issue by 50l3r** [supabase/supabase#6423]
# Bug report

## Describe the bug

When i try to run supabase-kong from self hosted using portainer i recieve this error:

```
nginx: [warn] load balancing method redefined in /usr/local/kong/nginx-kong.conf:59
2022/04/12 17:00:14 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:490: error parsing declarative config file /var/lib/kong/kong.yml:
/var/lib/kong/kong.yml: Is a directory
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:490: in function 'init'
	init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:490: error parsing declarative config file /var/lib/kong/kong.yml:
/var/lib/kong/kong.yml: Is a directory
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:490: in function 'init'
	init_by_lua:3: in main chunk
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Deploy supabase-kong container
2. Ports doesnt up
3. View logs and see the error

## Expected behavior

The service should be executed correctly

**Comment by unusec** [comment]
try to run the kong container without KONG_DECLARATIVE_CONFIG env var
then open a ternimal in that container and do a cat /var/lib/kong/kong.yml to check its contents
i had some issues with this and copied my kong.yml directly in root from my linux machine using:
docker container ls - to get the id of the kong container
chmod 777 docker.yml (if in linux)
docker cp kong.yml kong_container_id:/kong.yml
and add KONG_DECLARATIVE_CONFIG env var to point to /kong.yml

**Comment by 50l3r** [comment]
> try to run the kong container without KONG_DECLARATIVE_CONFIG env var then open a ternimal in that container and do a cat /var/lib/kong/kong.yml to check its contents i had some issues with this and copied my kong.yml directly in root from my linux machine using: docker container ls - to get the id of the kong container chmod 777 docker.yml (if in linux) docker cp kong.yml kong_container_id:/kong.yml and add KONG_DECLARATIVE_CONFIG env var to point to /kong.yml

I dont have `KONG_DECLARATIVE_CONFIG` in my vars. Accessing container files and try to cat kong.yml it says that's a directory.

I dont have any kong.yml file for my part.

**Comment by eeve** [comment]
I encountered the same error in the vscode container environment. I guess it should be the docker compose mounting disk problem in the vscode container environment. If I try to start it in WSL, the problem will not exist.

**Comment by kiwicopple** [comment]
closed by @Towerful here: https://github.com/supabase/supabase/pull/6642 🚀 

Let me know if there are any more issues and I can reopen

**Comment by 50l3r** [comment]
> @50l3r did you manage to get it running in portainer? I'm currently working through it, and it seems like Portainer doesn't like mounting relative directories. So, I'm finding the db initialisation scripts are not being presented to the postgres container, and a bunch of other containers are restart-looping as they cannot access the tables they are expecting.
> 
> I think the current workaround is possibly: [portainer/portainer#6390 (comment)](https://github.com/portainer/portainer/issues/6390#issuecomment-1100954657)
> 
> Just wandering if you figured anything out, or if I should try and work through a solution and post a PR

At the moment I have paused this project. I couldn't make it work.

**Comment by Coronon** [comment]
I am facing the same issue. My "quick and dirty" fix was manually setting the volume binds by editing the containers after deploying them through portainer. -> Edit -> Volumes. Note that you will have to copy/clone/sparce checkout the supabase repos docker dir for that. Look at the compose file for the bind paths needed and simply set absolute paths in portainer ;)

**Comment by fundef1** [comment]
> editing the containers after deploying them through portainer.

ran into the same issue, and found a solution... only 2 hours old no less (on a closed issue ;-(
Thanks @Coronon

**Comment by cristian-milea** [comment]
I don't know what that #6642 PR fixed, but it still happens on the latest supabase docker compose. 

```
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:553: error parsing declarative config file /var/lib/kong/kong.yml:
/var/lib/kong/kong.yml: Is a directory
```

**Comment by joa-queen** [comment]
The same is happening to me. At least when using it with [testcontainers](https://node.testcontainers.org/). 

When I run it directly with docker compose, runs fine.

**Comment by developerautomationkit** [comment]
real nasty.. but i  figured it out ..

Basically by inspecting the kong container logs i found out that for some reason the 

kong.yml was treated as a directory not as file. I beliieve this always will happen if you your supabase crashes 
and now you try to restart it because the permission on the "hosts machine" for the kong.yml is restricted and cant be written to anymore :)



in your coolify settings you can find out where the file in question is on your hosts machine for example:

/data/coolify/services/f04gsggows0sgk8co88ooo4s/volumes/api/kong.yml 

now you need to fix the permissions so the file can be written to again

1. ssh into your hosts machine ( for me it was hetzner)
now run  using the path use see in storage coolify

something like : ls -l /data/coolify/services/f04gsggows0sgk8co88ooo4s/volumes/api/kong.yml

2. now you should see something like this : -rw-r--r-- 1 9999 root 5581 Dec  4 17:07 /data/coolify/services/f04gsggows0sgk8co88ooo4s/volumes/api/kong.yml

3. Now you change the permissions : 
chmod 644 /data/coolify/services/f04gsggows0sgk8co88ooo4s/volumes/api/kong.yml

4. you check again to see if it worked
 ls -l /data/coolify/services/f04gsggows0sgk8co88ooo4s/volumes/api/kong.yml
 
 5. now you do docker ps -a and fetch the id for your kong container
 
 6. docker restart supabase-kong-f04gsggows0sgk8co88ooo4s
 
 7. Voila your kong now starts because the file can be overwritten making the docker compose not crash because it cant write to the file :)

![image](https://github.com/user-attachments/assets/9d877230-0f4b-420d-a5ce-7c2f6f19a825)
