### ISSUE TITLE
Supabase is crashing on Auth Page

### ISSUE THREAD

**Issue by igdmitrov** [supabase/supabase#6866]
# Bug report
Accidentally I found a small bug on Auth Page Supabase which crashed the whole page on Safari.

## Describe the bug

Supabase is crashing on the auth page on Safari when a new user is created, but email isn't confirmed.
If the user confirms it, the email page works again.
Problem only with label - Awaiting confirmation.

I tested Google Chrome - it works.

## To Reproduce

Sign up a new user with email and password.
Open Supabase Auth page with users list on Safari:
https://app.supabase.io/project/[project id]/auth/users
Whole page is crashing.

## Screenshots

I recorded a short video for fun:
https://youtu.be/pE_bHcvG-d4

## System information

- OS: macOS 12.4
- Browser: Safari 15.5

**Comment by saltcod** [comment]
Hey @igdmitrov — we pushed a bunch of fixes for dates in Safari earlier this week. I wonder if this issue was tied up with that.  

Would you mind giving this another try and seeing if it's still an issue? I just tried it locally and on production, and it worked just fine for me. I'm wondering if it's been fixed, or if I'm doing the order of operations differently than you. 

With thanks!

**Comment by saltcod** [comment]
Awesome! Thanks for the report @igdmitrov!    I'll close this issue, but feel free to open back up if you experience it again!

**Comment by saltcod** [comment]
Thanks @bhopalg — the exact steps in the original message above are failing in Safari for you?

**Comment by bhopalg** [comment]
Hey @saltcod, yes it is, Iv tested against chrome, brave and Firefox works fine on those but fails on safari
