### ISSUE TITLE
Tooltips and find/replace interface partially covered in SQL editor UI

### ISSUE THREAD

**Issue by roseMix** [supabase/supabase#702]
# Bug report

## Describe the bug

In the SQL editor, any tooltips shown on hover (at line 1) are covered by the tabs bar. Addtionally find/replace is also covered.
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'SQL Editor'
2. Hover over anything that would display a tooltip in vscode
3. See error: Hover tooltip is under the tabs bar

-or-

1. Right-click any word
2. select 'Replace all occurrences' from dropdown
3. See error: Find/Replace inputs are covered by tabs, the UI displayed is showing only the bottom part.

## Expected behavior

Tooltips and find/replace UI should be displayed "above" the tabs (higher z-index)

## System information

- OS: Windows
- Browser chrome
- Version of supabase: Web UI

**Comment by kiwicopple** [comment]
Strange, I couldn't reproduce on Mac.

Chrome:

![image](https://user-images.githubusercontent.com/10214025/107519283-0cbafe00-6beb-11eb-8756-13f5ca592d73.png)

FF:

![image](https://user-images.githubusercontent.com/10214025/107519386-2e1bea00-6beb-11eb-9fab-f64752d64018.png)


Could you please share a screenshot @rosensuzie ? I don't doubt it's a problem, but will be useful for confirming when we fix it

**Comment by rosensuzie** [comment]
Sure here
I'm using chrome on windows 10,

Here is the issue by selecting 'change all occurrences' - happens when the text is on any line
![Screenshot (47)_LI](https://user-images.githubusercontent.com/43044854/107531288-abfbd900-6b8a-11eb-9b1d-3d218b22997e.jpg)

Here is the issue by the hover menu - only on the first line
![Screenshot (45)_LI](https://user-images.githubusercontent.com/43044854/107531560-f715ec00-6b8a-11eb-9200-f237b7eb9941.jpg)

**Comment by kiwicopple** [comment]
This is very helpful, thanks for taking the time to make a bug report @rosensuzie

**Comment by phamhieu** [comment]
Hi @roseMix, we updated dashboard app recently. Let me know if you are still facing the issue. Thank you.
