### ISSUE TITLE
Next.js todo-list example's code is different with live demo

### ISSUE THREAD

**Issue by koremp** [supabase/supabase#7119]
# Bug report

## Describe the bug

I downloaded [nextjs-todo-list-example](https://github.com/supabase/supabase/tree/master/examples/todo-list/nextjs-todo-list) and run `yarn` to install dependencies and `yarn dev` to run next script.

But localhost's login page was different from live-demo page. 

![localhost-image](https://user-images.githubusercontent.com/18482476/171562932-e0ca38f1-b774-4c3b-abac-bca1e1eb1176.png)
![live-demo-image](https://user-images.githubusercontent.com/18482476/171563245-002e064d-39f5-4838-b9cb-6a9168b9c2be.png)

It took long time to find the reason of this error(bug). I found user agent, media query, browser difference. But the reason is not that kind of things. The live demo page's `Auth` component is covered by normal `<div>`, no class. But local page's `Auth` component was covered by `<div class="sbui-auth">` div. 

I found supabase ui's Auth's css file and Auth code. 
<https://github.com/supabase/ui/blob/master/src/components/Auth/Auth.module.css>
<https://github.com/supabase/ui/blob/master/src/components/Auth/Auth.tsx>
Class `sbui-auth` makes `width:100%` in css file and code.

So when I covered that `Auth` component with normal `div`, then `Auth` Component looks like same as live-demo.

## To Reproduce

Just download this <https://github.com/supabase/supabase/tree/master/examples/todo-list/nextjs-todo-list> nextjs-todo-list code and install dependencies via `yarn`, and run `yarn dev`

## Additional context

I think the result of example todo-list code and live-demo have to show us same result.
If I miss something wrong, plz reply me. Thank you.

**Comment by andrejbroncek** [comment]
Seems like this problem is back. When I log in and refresh the page, I am seeing the same `sbui-auth` class applied to the to-do list, resulting in the UI being broken. Anyone else experiencing this? 

Also, Comparing the CSS from localhost to the example deployed at https://supabase-nextjs-todo-list.vercel.app, there seem to be differences in the code. Is it possible the repo is behind on some changes/fixes?

<img width="961" alt="Screenshot 2023-05-16 223857" src="https://github.com/supabase/supabase/assets/5059809/62e36e30-f720-4533-b998-165c8477840d">

**Comment by andrejbroncek** [comment]
I see what the problem might be now... I was blind and didn't notice I pulled the archived examples repo. The problem is it is still linked from production docs - https://supabase.com/docs/guides/resources/examples.
