### ISSUE TITLE
ui for adding row to any table

### ISSUE THREAD

**Issue by johndpope** [supabase/supabase#7153]
# Feature request

<img width="697" alt="Screen Shot 2022-01-02 at 18 10 40" src="https://user-images.githubusercontent.com/289994/147868889-3f1a19b4-2d4a-4569-b778-dab27e48e984.png">

is this slated for release any time soon - or is there a repo you can point to ?

**Comment by joshenlim** [comment]
hey there i'm gonna go ahead to close this issue as we've now moved the grid within the studio repository directly
this is because the grid library that we've written is scoped to the requirements of studio and it doesnt really work well as a standalone grid library such as react-data-grid for example

**Comment by johndpope** [comment]
N.B. the react-data-grid doesn't have all the smarts for postgres.
