### ISSUE TITLE
Supabase Swift SDK

### ISSUE THREAD

**Issue by smotched** [supabase/supabase#7209]
I think we're past due for a native SDK for the Apple ecosystem. 

With Swift Concurrency newly released with backward compatibility, its a great time and it would open Supabase up to a whole new world.

**Comment by awalias** [comment]
is this what you're looking for? https://github.com/supabase-community/supabase-swift (feel free to reopen if not!)

**Comment by smotched** [comment]
Not really, this is an older closure based API, it seems more like someones side project than an official supabase ios sdk. 

The mobile dev experience with supabase is terrible, nonexistent in most cases. With recent funding I was hoping some focus would go towards making our lives easier.

Is supabase actually investing anything at all in ios world? or just native dev for that matter?

**Comment by grsouza** [comment]
hey @smotched I have some initiatives on making the swift libraries better and modern, I've already added the new Concurrency model to the https://github.com/supabase-community/gotrue-swift and https://github.com/supabase-community/postgrest-swift .

I'm slowly improving the swift libraries while I build `Filly` a finance management app. If you have any ideia and you know of any missing thing, please open an issue and I'l be glad reviewing it and/or implementing it when I have time.

**Comment by smotched** [comment]
@grsouza Thanks for your work, I see you've done some work on storage but you don't really have the resources to make something that a company would actually use in production (which is what this is all about). Theres a lot more in docs, tests, and community work that need to be done. And obviously realtime, and eventually edge functions. sadly supabase management just doesnt gaf about iOS or Native atm.

For example [Firebase](https://github.com/firebase/firebase-ios-sdk) and [Amplify](https://github.com/aws-amplify/amplify-ios), both native modern Swift sdks constantly updated. This is unfortunate for folks that built on supabase and are now stuck or forced to switch when going to mobile.

**Comment by smotched** [comment]
@grsouza Thanks for your work, I see you've done some work on storage but you don't really have the resources to make something that a company would actually use in production (which is what this is all about). Theres a lot more in docs, tests, and community work that need to be done. And obviously realtime, and eventually edge functions. sadly supabase management (@kiwicopple, @awalias) just dont gaf about iOS or Native atm

For example [Firebase](https://github.com/firebase/firebase-ios-sdk) and [Amplify](https://github.com/aws-amplify/amplify-ios), both native modern Swift sdks constantly updated. This is unfortunate for folks that built on supabase and are now stuck or forced to switch when going to mobile.

**Comment by kiwicopple** [comment]
Hey @smotched , there's no need for ad-hominem attacks. In this case it's Ant & I, but if we see anything like that for any of the other maintainers or contributors in the community you'll be blocked immediately

With that out of the way, I completely understand. We definitely care, it's just a matter of getting everything right at the right time. We've grown a lot, and very fast, and it's not easy to juggle all of the community's requests. For the past 2 years we've worked on a [most demanded features first](https://supabase.com/blog) - which is not a short list. Each time we deliver something we move onto the next demanded feature. 

Let me remind you that this is also a community. @grsouza is working on this now, and since this is open source, you're under no obligation to pay @grsouza for his time and efforts (or Supabase). You're also under no obligation to show gratitude, but it seems reasonable that you treat everyone like a human, Ant & myself included.

If you would like to accelerate the Swift library, you're welcome to help @grsouza and the other maintainers. Thanks!

**Comment by smotched** [comment]
@kiwicopple Apologizes for being unprofessional, it might have came off more rude than I wanted (it was after a long session). I've managed to move away from supabase but I really do wish you guys the best and I'm sure you're doing great work for the web community. And I did enjoy using it, which is why I wanted to use it everywhere :)

I do have to call out one thing, I don't think you can say you care while putting in zero effort, or you care but just not enough atm, which is what I was trying to get at above but came off rude. Anyways, I'm sure you guys will make it work!
