### ISSUE TITLE
Cannot login wth GitHub

### ISSUE THREAD

**Issue by pulkitvyas08** [supabase/supabase#7357]
# Bug report

## Describe the bug

Not able to signin on to the website by using GitHub. Getting CORS errors.

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.supabase.io/platform/profile. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 500.`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to ['https://app.supabase.com/'](https://app.supabase.com/)
2. Click on Sign in with GitHub
3. Open browser console

## Expected behavior

Should just let me sign in I guess

## Screenshots

![image](https://user-images.githubusercontent.com/54947769/174734838-064b3e2d-f19e-4fee-ada6-f551f3d3ef0b.png)

## System information

- OS: Windows 11
- Browser (if applies) Firefox
- Version of supabase-js: N/A
- Version of Node.js: N/A

**Comment by w3b6x9** [comment]
Cloudfare is currently blocking us due to their ongoing incident. We are in touch with our contact at Cloudfare and will get this resolved on our end as soon as Cloudfare is once again functional.

<img width="958" alt="Screen Shot 2022-06-20 at 23 56 42" src="https://user-images.githubusercontent.com/5532241/174736003-94a8598b-110b-434c-aec8-9f56e2882abc.png">

**Comment by Isaiah-Hamilton** [comment]
Cloudflare and Supabase is back up and running.
