### ISSUE TITLE
The current Deno Supabase module is broken

### ISSUE THREAD

**Issue by cdcarson** [supabase/supabase#7524]
# Bug report
Not sure where to report this, because there seem to be (outdated?) repos in play, like [link-discord/supabase-js](https://github.com/link-discord/supabase-js) and [link-discord/gotrue-js](https://github.com/link-discord/gotrue-js). I'm reporting here because it looks like the official repo.

The current [Supabase Deno module](https://deno.land/x/supabase@1.3.1) is broken when you call `createClient`.

## Describe the bug
[This line](https://deno.land/x/gotrue@3.0.0/src/lib/helpers.ts#L17) in the current Deno version of GoTrue references `window.location`, resulting in...

```bash
error: Uncaught TypeError: Cannot read properties of undefined (reading 'href')
  if (!url) url = window.location.href
                                  ^
    at getParameterByName (https://deno.land/x/gotrue@3.0.0/src/lib/helpers.ts:17:35)
    at new GoTrueClient (https://deno.land/x/gotrue@3.0.0/src/GoTrueClient.ts:94:57)
    at new SupabaseAuthClient (https://deno.land/x/supabase@1.3.1/src/lib/SupabaseAuthClient.ts:6:5)
    at SupabaseClient._initSupabaseAuthClient (https://deno.land/x/supabase@1.3.1/src/SupabaseClient.ts:166:12)
    at new SupabaseClient (https://deno.land/x/supabase@1.3.1/src/SupabaseClient.ts:69:22)
    at createClient (https://deno.land/x/supabase@1.3.1/src/index.ts:11:10)
    at file:///Users/chriscarson/supabase-gotrue-deno-issue/main.ts:2:16

````

This is looks fixed in the [Supabase version of the js GoTrue client](https://github.com/supabase/gotrue-js).

## To Reproduce

Minimal repro: https://github.com/cdcarson/supabase-gotrue-deno-issue.git 

You need to have deno installed.

```bash
git clone https://github.com/cdcarson/supabase-gotrue-deno-issue.git 
cd supabase-gotrue-deno-issue.git
# The following takes two cli args, the Supabase URL and key, 
# but you can just use "foo bar". It doesn't matter - I get the same error with a real URL and key
deno run main.ts foo bar 
```

You should see the error above.

## System information

- OS: MacOs
- Version of supabase-js: https://deno.land/x/supabase@1.3.1
- deno 1.23.1 (release, aarch64-apple-darwin)
- v8 10.4.132.8
- typescript 4.7.2

**Comment by cdcarson** [comment]
Woops. I was using the wrong module URL. The right one is 
```ts
import { createClient } from "https://esm.sh/@supabase/supabase-js@1.35.4";
```

**Comment by sant123** [comment]
Hi! I'm curious if there are any plans to support supabase in deno.land/x? The reason is that if the module is hosted there, it will be served as an inmutable version so deno.lock won't have any issues resolving the module.

I see there are supabase names taken, not sure if it can be created using other name. 

Thanks.

**Comment by Evertt** [comment]
@egor-romanov Why did you label this as `wontfix`? Is it because you don't see a way of fixing this? Or just because you don't want to prioritize fixing this?

I've been using @cdcarson's work-around:

```typescript
import { createClient } from "https://esm.sh/@supabase/supabase-js@1.35.4";
```

But it seems like that `createClient` does not use the pooled API of supabase and so I worry that my project will get overwhelmed with connections once I make my project go public. Also, it looks like a pretty old version of `supabase-js` and I worry it will some day soon just stop working all-together. I would really like if the Deno module would just work and from what I've gathered, it shouldn't be that much of a hassle to fix it. But maybe I'm wrong, I don't know. Could you please share some light on this?

**Comment by egor-romanov** [comment]
@Evertt hi, i added wontfix because issue was closed by the author after the fix of import path. 

You don't need connection pool in supabase-js lib because it uses PostgREST under the hood which is HTTP API. So you don't need to worry about connections overflow. 

Please, open a discussion about support for native deno package. It will be easier for us to prioritize having it in the discussions. Thanks!
