### ISSUE TITLE
Wrong usage in the Svelte Kit tutorial

### ISSUE THREAD

**Issue by Olyno** [supabase/supabase#7623]
# Bug report

## Describe the bug

In the [Svelte Kit tutorial](https://supabase.com/docs/guides/with-sveltekit#create-an-upload-widget), it looks like there is an issue. The ``downloadImage`` function is used in the ``use`` directive, but produces an error because this one accepts only sync functions, and not async functions.

## To Reproduce

/

## Expected behavior

The docs should contain a function as:

```js
function downloadImage() {
  supabase.storage.from('avatars').download(path)
    .then(({ data, error }) => {
      if (error) throw error
      src = URL.createObjectURL(data)
    })
    .catch(error => console.error('Error downloading image: ', error.message))
}
```

## Screenshots

![See image here: https://cdn.discordapp.com/attachments/869406062036529193/994954741597618237/Screenshot_2022-07-08_at_14.10.47.png](https://cdn.discordapp.com/attachments/869406062036529193/994954741597618237/Screenshot_2022-07-08_at_14.10.47.png)

## System information

- OS: /
- Browser (if applies): /
- Version of supabase-js: /
- Version of Node.js: /

## Additional context

Reported by @continuata on the discord

**Comment by continuata** [comment]
also true of the `getProfile` function in `Profile.svelte`. Should look like this:

```ts
	function getProfile(node: HTMLElement) {
		try {
			loading = true;
			const user = supabase.auth.user();

			supabase
				.from('profiles')
				.select(`username, website, avatar_url`)
				.eq('id', user?.id)
				.single()
				.then(({ data, error, status }) => {
					if (data) {
						username = data.username;
						website = data.website;
						avatar_url = data.avatar_url;
					}
					if (error && status !== 406) throw error;
				});
		} catch (error: any) {
			alert(error.message);
		} finally {
			loading = false;
		}
	}
```

**Comment by tlancina** [comment]
Just ran into this as well - I think the main issue is that the guide is not TypeScript (if you check out the repo listed in the guide: https://github.com/yustarandomname/svelte-supabase-quickstart it's using JS).

You can't rethrow the error in `.then` because it's unhandled (both https://github.com/supabase/supabase/pull/7668 and https://github.com/supabase/supabase/issues/7623#issuecomment-1179105978 have runtime errors if `error` is not null) and you can't `.catch` without casting to `Promise` because `single()` returns a `Thenable`.

For anyone using TypeScript, one solution could be an async IIFE. Since the use directive is there for lifecycle timing and not doing any setup or teardown, it lets the action stay synchronous and keeps the autogenerated Svelte typings happy.

	function getProfile(_: any) {
	  (async function() {
	    try {
	      loading = true
	      const user = supabase.auth.user()
			
	      let { data } = await supabase
	        .from('profiles')
	        .select(`username, website, avatar_url`)
	        .eq('id', user?.id)
	        .single()

	      if (error && status !== 406) throw error	

	      if (data) {
	        username = data.username
	        website = data.website
	        avatar_url = data.avatar_url
	      }
	    } catch (error: any) {
	      alert(error.message)
	    } finally {
	      loading = false
	    }
	  })()
	}
