### ISSUE TITLE
Fully Self-Host Dashboard/ Studio

### ISSUE THREAD

**Issue by l0nax** [supabase/supabase#7665]
# Improve documentation

## Link 

* https://supabase.com/docs/guides/hosting/overview
* https://supabase.com/docs/guides/hosting/docker

## Describe the problem

Please correct me if I misunderstand anything because this project is really awesome and allows us to replace Google proprietary tools with Open-Source software.

The Studio [README.md](https://github.com/supabase/supabase/blob/master/studio/README.md) states
> Studio is designed to work with existing deployments […] that's out of scope.

which seems to be contrary to what can be found in the code base.
The studio source-code contains some traces of the SaaS-UI, i.e. the GitHub OAuth login: https://github.com/supabase/supabase/blob/048bc3a84ede25a0299d3043886161c4218f2db4/studio/components/interfaces/Home/Landing.tsx#L16-L22

It seems like that documentation is missing on how to completely deploy the app, allowing to use a full self-hosted variant of Supabase.

## Describe the improvement

From the Documentation it's not clear that the (self-hosted) deployment is not equivalent to the SaaS platform. 
It would be really helpful if the documentation would clarify it.

**Comment by kiwicopple** [comment]
Hey @l0nax - thanks for bringing this up! I want to make sure I understand you correctly, because it's always hard writing docs when you don't have a "fresh perspective" (like you!)

> it's not clear that the (self-hosted) deployment is not equivalent to the SaaS platform

I tried to cover it in this part in the README:

> It is not intended for managing the deployment and administration of projects - that's out of scope.

You will see that many of the "Settings" screens on Studio are not there. This is because you can [configure](https://supabase.com/docs/guides/hosting/docker#configuration) your deployment using environment variables. I see this docs don't explain very well how to configure a docker-compose setup. Is that what you mean?


> deployment .. of projects

Studio will never be able to do this, because that's very much a devops task. There are tools (terraform, k8s, pulumi, ansible, salt) and entire companies devoted to deploying servers into whichever target you want - cloud providers, baremetal, VPS, etc. It simply wouldn't be a good use of our time to do this since everyone has their own preferred tools & targets. That said, the docker-compose run _exactly_ the same tools that we run in production for each Supabase Project. FWIW, we use Pulumi at Supabase and it's very good!

> The studio source-code contains some traces of the SaaS-UI, i.e. the GitHub OAuth login:

That's right - the Studio code and the version you see on app.supabase.com are the same :). We just use some feature toggles to enable/disable some functionality depending on where it's running.

As a side note, there are some other pieces missing (as of today, such as the Storage interface) from Studio, but we _are_ intending to "toggle that on" for self-hosting - we just need to commit a bit more time getting it working with local file storage instead of s3 storage. Don't take it as a sign we're "gating" any features - that's definitely not the intent - we're just very stretched

**Comment by GQAdonis** [comment]
Good morning!  I keep reading hundreds of messages supposedly helping explain how to properly self-host Supabase, @l0nax, and I stay confused.  Obviously it IS possible, as the `supabase start` command silently executes the work of creating a local docker install that works perfectly.  However if I want this in my cloud (via Kubernetes or Docker) I cannot seem to get to where I can edit anything even though I reverse engineering every setting from the CLI local instance.

Can anyone shed light on this?  As cool as this is, none of my customers want this stuff running in your cloud, so self-hosting is a must for production use.

**Comment by sweatybridge** [comment]
We now have a compose file available to run in any self-hosted environments:

```bash
docker compose -f docker/docker-compose.yml up
```

Depending on the scale of your deployment, you might also want to run the containers using an orchestration platform like k8s. If you need any custom configs exposed or find the self-hosted UX lacking in any aspect, feel free to open new issues with your specific requests.
