### ISSUE TITLE
Error getting user: { message: 'Invalid Refresh Token', status: 400 }

### ISSUE THREAD

**Issue by lumenwrites** [supabase/supabase#7676]
# Bug report

## Describe the bug

I'm building an app with Supabase and Next.js

From time to time I'm seeing the following error in my logs:
```
Error getting user: { message: 'Invalid Refresh Token', status: 400 }
```

I'm relatively new to supabase, I don't really understand what that means, and I'd love some help with resolving this issue.

## To Reproduce

I set up the authentication by following the [@supabase/auth-helpers-nextjs tutorial](https://supabase.com/docs/guides/with-nextjs). I didn't do anything weird or unusual, just followed the instructions.

According to [this](https://github.com/supabase-community/auth-helpers/issues/171), it happens with all the Supabase and Next.js examples.

## Expected behavior

Not getting this error.

## System information

- OS: macOS
- Version of supabase-js: 1.35.4
- Version of Node.js: 16.14.2

**Comment by ARMATAV** [comment]
Yup, +1 - I'm scouring around to find an example that doesn't have this issue - tab away for 1 hour, tab back; your token is invalid. Wait on the page for an hour, refresh, you're now de-authed.

This is kind of fundamental to the library, it's really hard to use now since during local development, you have no access to `auth/settings` in the supabase dashboard and so you can't even scam the system by setting the expiration time to `1 week` like you can when doing it live.

I love the idea of Supabase, and I love the idea of hooking up Prisma (once they support multiple SQL schemas) to take care of the migration issues; but the biggest blocker is just a working NextJS example with no killer kinks in it.

**Comment by odiseo0** [comment]
Same here

**Comment by satyapalsharma** [comment]
@ARMATAV You can change the expiration time in gotrue config

**Comment by ARMATAV** [comment]
> @ARMATAV You can change the expiration time in gotrue config

Right you are - for future people, you can access the different variables in the container's config itself like this https://supabase.com/docs/gotrue/server/about by passing around envars. 

However, still going to bug out after `n` seconds at this point in time - but it looks like they're going to take a shot at fixing it - very important, very fundamental functionality.

**Comment by J0** [comment]
Hey @ARMATAV and @satyapalsharma  going to close this issue in favour of tracking this on the [gotrue-js](https://github.com/supabase/gotrue-js/issues/323) issue.

Feel free to re-open if there are still queries or you feel that there's merit in having this remain open though.
Thanks
Joel

**Comment by nestoremgi** [comment]
Hi guys, i dont know if this could be related whit all above, but i was working with opt  tokens auth  and  supabase was generating  tokens correctly but when ! start again the next,js app it doesn work anymore, and now im reciving this message {"code":400,"msg":"Verify requires a token"}, the stranger thing is that i was working without problems how i mentioneted but today something happened, and its really frustraiting because supabase is generiting opt token, but imediatly it said that it has expired !

**Comment by gregnr** [comment]
Hey @nestoremgi! I would open a GitHub discussion for this and someone can try to help you out there
