### ISSUE TITLE
Can´t migrate between projects

### ISSUE THREAD

**Issue by perezpefaur** [supabase/supabase#7938]
# Bug report
Running
`pg_dump --clean --if-exists --quote-all-identifiers -h XXX.supabase.co -U postgres > dump.sql `
Returns
```
pg_dump: error: connection to server at "XXX.supabase.co" (104.18.26.135), port 5432 failed: Operation timed out
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "XXX.supabase.co" (104.18.27.135), port 5432 failed: Operation timed out
	Is the server running on that host and accepting TCP/IP connections?
```

## To Reproduce

The exact steps in https://supabase.com/docs/guides/database#migrating-between-projects

## Expected behavior

Dump my db in a sql file

## System information

- OS: macOS

**Comment by justusbluemer** [comment]
I have the exact same issue

**Comment by ilrein** [comment]
Just ran into this today. Does the IP block go away after some time?

**Comment by lerayj** [comment]
Same here. Any update on how to handle this ?

**Comment by twgonzalez** [comment]
Same here.  Any update?  This is a showstopper.

**Comment by Jaaneek** [comment]
Same :(, updates?

**Comment by feliche93** [comment]
Also facing the same problem, anyone found any solution?

**Comment by twgonzalez** [comment]
I reached out to support (paid plan) and they resolved it.

**Comment by danilsizov** [comment]
The same for me, I entered wrong password few times, would be great to add a white list of IP's in settings of DB

**Comment by feliche93** [comment]
@dlchet the following from support helped: 

Thanks for contacting Supabase support. Checking here, there are banned IPs on your project caused by Fail2ban as it kicks in when attempting 2 wrong passwords in a row.

These bans will clear after 30mins but you can unban the IPs using the Supabase CLI https://supabase.com/docs/guides/cli following the commands below.

How to list the banned IPs:
% supabase network-bans get --project-ref <project_reference_id> --experimental

How to unban the IPs:
% supabase network-bans remove --db-unban-ip <ip_address> --project-ref <project_reference_id> --experimental
