### ISSUE TITLE
Password update requires reauthentication.

### ISSUE THREAD

**Issue by jishnair** [supabase/supabase#8200]
## Describe the bug

After logging in using the reset password link the method _supabase.auth.api
      .updateUser_ is throwing ```{
  "code": 401,
  "msg": "Password update requires reauthentication."
}```
This was working before in my app, I think a recent update is causing this error. 

## To Reproduce

1. Using NextJs

2. Generate reset link
```
 const { data, error } = await supabase.auth.api
  .resetPasswordForEmail('user@email.com')

```
4. Detect password recovery event and show the password reset form:
```
supabase.auth.onAuthStateChange(async (event, session) => {
            if (event === 'PASSWORD_RECOVERY') {
                router.push({
                    pathname: '/auth/password-recovery/[token]',
                    query: { token: session.access_token },
                });
            }
```
5. Update the password:
```
const { error, data } = await supabase.auth.api
      .updateUser(access_token, { password : new_password })
```

Response: 
```
{
  "code": 401,
  "msg": "Password update requires reauthentication."
}
```

The user is logged in, also this method returns the same error.
```
await supabase.auth.update({
            password: new_password,
        });
```

## System information

- Version of supabase-js: 1.35.4
- Version of Node.js: 16

## Additional context
There used to be a setting in the Supabase Dashboard for 'Password update requires reauthentication' but it's missing now.

**Comment by drishya-tech** [comment]
I am also facing the same issue and from discussions and bug tickets it looks like many are facing the same issue.
 @kiwicopple could you assign someone to look into this ASAP?

**Comment by J0** [comment]
Hey @jishnair ,

Thanks for your patience. The error is happening as reauthentication is required before a password update as a security measure(similar to how an app might ask you to re-enter your password)  as we want to be certain it is the intended user who is updating the password.

If possible, do consider using the

```ts
supabase.auth.api.resetPasswordForEmail(email, { redirectTo })
```

If you still need the method you will need to directly call `/reauthenticate` in order to get a `nonce` which you then pass in the nonce to the `/updateUser`  

We plan on updating the library soon and it should be clearer with the new release.


Hey @drishya-tech,

Thanks for flagging this. Could you please point us to the relevant discussions and tickets? Would love to jump in and get back to them as well.

Joel

**Comment by drishya-tech** [comment]
@J0 Here is the discussion: https://github.com/supabase/supabase/discussions/7310

**Comment by J0** [comment]
Thanks @drishya-tech

**Comment by jishnair** [comment]
@J0 Can you please confirm, that the password reset flow according to the [documentation](https://supabase.com/docs/reference/javascript/auth-api-resetpasswordforemail) is working? 
I have spent way too much time making it work without success.

**Comment by jishnair** [comment]
@J0 I have created a new Supabase instance, and the password reset is working there. So the issue was due to some breaking changes in the GoTrue server. You guys really need to document the breaking changes. 
Is there a way to upgrade my older instance ? Then I can close this issue.

**Comment by J0** [comment]
@jishnair Apologies for the delayed reply -- we can upgrade the older instance for sure. I will also see if I can look into the instance. Could you shoot us an email at support@supabase.io asking for "the Auth team to upgrade my instance  with project ref: <project_ref"? 

Thanks
