### ISSUE TITLE
Cannot add row level security for INSERT

### ISSUE THREAD

**Issue by Nick-Mazuk** [supabase/supabase#822]
# Bug report

## Describe the bug

I'm creating a table where anonymous users can insert rows, but cannot do anything else. However, when I insert a row-level permission with the same method as in the [screencast](https://supabase.io/docs/learn/auth-deep-dive/auth-row-level-security), I get the error:

```
Policies require either a Definition or a Check.
```

## To Reproduce

1. Create a new table
2. Go to Authentication > Policies
3. For the new table, click the lock button to enable row-level security
4. Click on "Add Policy"
5. Click "Advanced", then "Insert"
6. Provide a policy name, and for the definition, type `auth.role() = 'anon'`
7. Click save

## Expected behavior

I should be able to add the policy because a Definition is provided.

## Screenshots

<img width="1212" alt="Screen Shot 2021-03-06 at 11 44 19 AM" src="https://user-images.githubusercontent.com/5659171/110218963-4b9e4580-7e71-11eb-945e-6c1c3b016d24.png">

## System information

- OS: macOS 11.2
- Browser: Brave 1.21.73 on Chromium: 89.0.4389.72, also Safari 14.0.3

**Comment by kiwicopple** [comment]
Thanks for this @Nick-Mazuk. in this case the behaviour is correct but our UI isn't great - `

`INSERT` policies actually require you to add the the rule to the `with check` field rather than the `definition` field. We should hide the definition field when the `insert` clause is selected

Thanks for the bug report, i'll fix it now!

**Comment by kiwicopple** [comment]
Fixed now - this will go out in the next release :) (~monday)
