### ISSUE TITLE
Custom claims

### ISSUE THREAD

**Issue by xylys** [supabase/supabase#841]
# Feature request

## Is your feature request related to a problem? Please describe.

Adding custom claims on the JWT token like in firebase.
This would make multi tenancy and user roles easier to implement with RLS

## Describe the solution you'd like

The ability to add custom claims to the JWT token send to the user upon sign in.
For example one or multiple organisation ID's a user belongs to.

This would greatly simplify and speed up RLS policy creation, since the org_id from the token can be directly compared to the org_id of the row without doing an additional query.

eg. what currently uses an additional select query
```
create policy "Read messages if user is a member of the org" 
  on public.messages 
  for select using ( 
    auth.uid() in (
        select user_id from members where members.org_id = messages.org_id
    )
  );
```
  

 Would become a simple policy we could add in the web ui
```

auth.claims.organisation = org_id
```

A realtime listener or polling system could be implemented in the client library to automatically refresh the token in case a users custom claims would change.

**Comment by kiwicopple** [comment]
You can definitely use the `auth.raw_user_metadata` and `auth.raw_app_metadata` columns for this.

However I wouldn't recommend it. JWT is great for Authentication, but not so great for Authorization. What happens if a user is removed from an organization (in your example above)? Their token is still valid for 1 hour, and the Policies will continue to allow the user until the token is refreshed.

It's a tradeoff between simplicity for security.

I do think we need to set up a good multi-tenant solution, something which is simple and secure. I'll transfer this over to a Discussion, because I'd love to get comments/ideas. Here is a good article which could seed the discussion: 
https://cazzer.medium.com/designing-the-most-performant-row-level-security-strategy-in-postgres-a06084f31945
