### ISSUE TITLE
Esc behaviour while editing a table cell

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#8634]
# Bug report

## Describe the bug
Hitting Esc while editing a table cell should discard the changes. Currently, when you hit Esc, you will save these changes, not discard them.

**Example**

If you were typing into this cell, but didn't want to save these changes. It feels like hitting Esc here should mean "I want to cancel the changes I've just made". Instead, the changes are saved to the database.
<img width="307" alt="CleanShot 2022-08-24 at 16 39 34@2x" src="https://user-images.githubusercontent.com/105593/186503455-418f2de8-45e8-448f-94df-20aaf5d08e65.png">

**Comment by okellogabrielinnocent** [comment]
@saltcod From the investigation of this issue, I have discovered that updating escape functionality will touch the onBlur functionality on BlockKeys which saves the changes to databases,
At the moment it isn't clear from the issue how saving data should actually be handled since it was previously handled by blur event (escape or outside click), I would assume that the way to go here might be.

1. Discard change with `Esc`.
2. Insert a new line with `Shift + Enter`
3. Submit change with `Enter`
