### ISSUE TITLE
Supabase can't request to db on production (Vercel)

### ISSUE THREAD

**Issue by vixalien** [supabase/supabase#8680]
# Bug report

## Describe the bug

When deployed to production (Vercel), the supabase library (supabase-js) doesn't make requests to the postgres db and fails with an error. The error thrown is:

```
FetchError: node-fetch cannot load postgresql://postgres:PASSWORD@db.URL.supabase.co:5432/postgres/rest/v1/url. URL scheme "postgresql" is not supported.
```

## To Reproduce

Deploy your app to Vercel, I only have Vercel so I'm not sure if it is reproducible in other environments.

## Expected behavior

The request would go thru

## System information

- OS: Arch Linux
- Browser: Firefox 103
- Version of supabase-js: 1.35.6
- Version of Node.js: v16.17.0

## Additional context

None.

If you need any more details, I'd be happy to provide~

**Comment by GaryAustin1** [comment]
Looks like you are using the database connection string, rather than the api url when you initialize the supabase-js client....

Your url should look like `https://wezxxxxxxxxxdnbjf.supabase.co`

The connection string `postgresql://postgres:PASSWORD@db.wezxxxxxxxxxxxdnbjf.supabase.co:5432/postgres` is used to access the database directly and is not used by supabase-js.

**Comment by vixalien** [comment]
yep. that's true. thanks
