### ISSUE TITLE
API calls that fail (404 error) in self-hosted supabase studio

### ISSUE THREAD

**Issue by raffaelescala97** [supabase/supabase#8721]
# Bug report

## Describe the bug

In the self-hosted version of supabase there are several calls that fail in supabase studio (404 not found), is this normal or are there configuration errors?
Everything else seems to work correctly

In particular this api call (I can see it by ispecting network on chrome):
- https://[mydomain]/api/profile/permissions?returning=minimal
- https://[mydomain]/api/projects/default/subscription

## Screenshots
<img width="1792" alt="supabase-bug" src="https://user-images.githubusercontent.com/40289234/187465854-786b9536-618f-4993-83f8-545c398c8cdf.png">

## Additional context

Maybe they are useful calls for app.supabase.com cloud version, but I just want to be sure it is not a configuration problem for the self-hosting.

Thanks in advance

**Comment by rgfx** [comment]
Thanks for posting this. I thought it was something I did wrong.

**Comment by secretgspot** [comment]
dealing with same issue here https://github.com/supabase/supabase/discussions/8983 contacted supabase support by email and was told to post it up

**Comment by rgfx** [comment]
@secretgspot no one help me discord either, I was completely ignored.

**Comment by raffaelescala97** [comment]
@rgfx @secretgspot Maybe they are fixing it with this PR: #8988

**Comment by beeman** [comment]
I'm having similar issues with the self-hosted supabase studio using the supabase CLI.

![image](https://user-images.githubusercontent.com/36491/197347924-d3c903e8-42f3-4af3-aa43-b4206241ac2b.png)

I'm getting an error "Failed to update settings" when I tried to change something in my setup. 

I tried about everything [as described here](https://discord.com/channels/839993398554656828/1033157267253645412) to get it to a working state, but nothing helps.

Feel free to ping me on Discord `beeman#8333` if you are interested in troubleshooting the issue.

**Comment by kiwicopple** [comment]
Discussed on twitter: https://twitter.com/kiwicopple/status/1583874538734989314

These config pages shouldn't be appearing on the Studio if you are using the CLI or selfhosting

- CLI: update the `config.toml` file - https://supabase.com/docs/reference/cli/config
- Self-hosted Docker: update the settings directly inside the docker-compose or `.env` files.

I'll mark this one for the frontend to hide this page on self-hosted so that there is no confusion

**Comment by kiwicopple** [comment]
closing in favor of https://github.com/supabase/supabase/issues/9775

Feel free to comment here again if you have any issues

**Comment by beeman** [comment]
> I'll mark this one for the frontend to hide this page on self-hosted so that there is no confusion

For reference, this API Settings pages is linked through this page http://localhost:54323/project/default/api?page=users

**Comment by ravikiranp123** [comment]
This is occuring with cli version 1.42.4 again. Wasn't occuring with 1.26.0 though. What are the changes required in toml file to fix it? I couldn't find any details searching online.

**Comment by donalffons** [comment]
I'm using the unmodified `docker/docker-compose.yml` with `.env` copied from `docker/.example.env` with the most recent tag `v0.23.09` of this repository and also encounter these issues.

![image](https://github.com/supabase/supabase/assets/33040347/7c9b5a3d-d562-4b7b-b27d-ab2c92411d83)

There are a couple of HTTP-Requests with 404 responses that seem related:

```
http://localhost:8000/api/integrations/default-org-slug?expand=true
http://localhost:8000/api/projects/default/billing/subscription
```

**Comment by gobegi** [comment]
In reply to @donalffons Just posted this on (https://github.com/StanGirard/quivr/issues/1816). I was getting this issue for a couple of days until I went to jwt.io and verified the JWT tokens that I generated uisng https://supabase.com/docs/guides/self-hosting/docker. It turns out that if I changed the secret key, the generate JWT token did NOT create a valid JWT token! I pasted the token generated into jwt.io and pasted the secret key that I wanted to use into it and it re-generated the ANON_KEY and then did the same with the SERVICE_KEY. I no longer get an JWT not verified error when creating a new user ... I now hav successfully created a new user and I'm sure cleared up other functions as well. :-)

Side note: On my self-hosted Docker installation, I had to leave the "Default Organization" and "Default Project" alone for the JWT token to verify. I also did "docker compose down" and "docker compose up -d" a "docker compose restart" did not do the job because the client kept the old creds.
