### ISSUE TITLE
Can't make id column identity column

### ISSUE THREAD

**Issue by ericbrian** [supabase/supabase#8782]
# Bug report

## Describe the bug

Failed to update column "id": failed to update pg.columns with the given ID: column "id" of relation "coin" already has a default value

## To Reproduce

1. Click Edit Table
2. Cick Gear icon (extra options)
3. Select "Is Identity" checkbox
4. Click Save 

## Expected behavior

'id' column is identity column

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js: 1.35.6
- Version of Node.js: v18.8.0

**Comment by joshenlim** [comment]
Hey there @ericbrian! This is an expected behaviour actually from Postgres - in fact if you were to run the equivalent SQL code
```
alter table test_table alter column id add generated by default as identity;
```
You'll run into the same error message
```
Failed to run sql query: column "id" of relation "test_table" already has a default value
```

What you can do is just remove the default value of your column, and select the is identity checkbox before saving - i'll go ahead to close this ticket first but feel free to reopen if I misunderstood anything! It'll be great if you can attach a screen recording as well so it'll be easier for us to check where the issue might be
