### ISSUE TITLE
Can't read sb-access-token cookie on server side after signed in with Github

### ISSUE THREAD

**Issue by zett-8** [supabase/supabase#8901]
Thanks for your attention. and I'm sorry if this is not a bug nor Supabase's problem.

I'm trying to enable sign-in with GitHub.
The framework is Remix, so I want to handle everything on the server side.

## Current code
Call SupabaseClient function on client-side when user clicks `sign in with GitHub`.
```ts
import { supabase } from '~/services/supabase/supabase.client'

supabase.auth.signIn(
        { provider: 'github' },
        { redirectTo: `${window.location.origin}/login` }
      )
```
and it's redirected to `/login` via Supabase server.

```ts
// login.tsx (omitted unnecessary code)

import { parse } from 'cookie'

export const loader: LoaderFunction = async ({ request }) => {
  // ---

  // get supabase token from cookie
  const cookie = parse(request.headers.get('Cookie') || '')
  const sbAccessToken = cookie['sb-access-token']

  // get user from token
  const { user, error } = await supabase.auth.api.getUser(sbAccessToken)
  // ↑ yes! this works!
}
```

This code works without any problem on localhost environment, Remix(localhost) + Supabase(local emulator).
But in production, Remix(Cloudflare workers) + Supabase(real server), I can't access cookies that should exist in the header.
I can't find `sb-access-token`  nor `sb-refresh-token`.

```ts
  // get supabase token
  const cookie = parse(request.headers.get('Cookie') || '')
  const sbAccessToken = cookie['sb-access-token'] // <- THIS IS NULL in production 😰
```

Weirdly when I check devtool on client side I can find both of them.
This means I must have received both tokens after redirect.
But it's not accessible on server side.

I first thought the way of reading cookies is somehow wrong, 
so I tried several ways of reading cookies but was no luck in any way.

also thought it's because the domain is different but they are not `SameSite=strict` cookie so it should be accessible.

![Screenshot 2022-09-11 at 10 20 38](https://user-images.githubusercontent.com/33055097/189518706-cad3733e-3c58-464e-9bd3-408c74135ca9.png)

Does anyone have any idea to solve this problem?
I'm struggling for a long time.

Thank you in advance.

**Comment by Benjamin-Dobell** [comment]
I ran into this too. Sadly, it is user error 😅

I was a Next.js -> Remix convert and had been accustomed to accessing `sb-access-token`. In fact, locally (with local Supabase) it worked just fine. It wasn't until I deployed that I was unable to access `sb-access-token`.

However, the cookies set by `supabase.co` domain are very much tied to that domain. The reason it works in Next.js land is because https://www.npmjs.com/package/@supabase/auth-helpers-nextjs explicitly sets the `sb-access-token` for you, from an end-point on your domain (i.e. it's your site's cookie): https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/src/handlers/callback.ts#L35-L60. Prior to the existence of this library, I believe there were examples floating around that operated similarly?

However, there's no equivalent library for Remix (yet). So there's nothing setting those cookies on your domain.

Now, here comes the fun part...

The cookie spec has been around a while, prior to this whole origin isolation thing. Cookies (by default) are tied to a hostname _not_ an origin. What that means is if you've got too services running on the same hostname your cookies will leak across. Well, that just so happens to be the case if you're running your development server and Supabase locally. Also, a less than ideal coincidence, Supabase uses the same cookie names (as the Supabase SDKs) for communication with its auth server (`sb-access-token` and co.) End result is one very confused developer 😖

**Comment by zett-8** [comment]
Hey @Benjamin-Dobell!
Thank you for sharing your knowledge.

hmm...so we need to wait for `auth-helper-remix`...

For my project, I ended up navigating to the client side once and redirecting to the server side again with the token.
Not ideal but it seems the only way to auth.

anyway, I really appreciate you. 
Couldn't solve the problem but knowing it's impossible helps me a lot😅
